package.json
pnpm-lock.yaml

* `v4-client-js`
* updated: v0.32.0 -> v0.33.1

bump v4-client

---

src/hooks/useSelectedNetwork.ts
src/views/dialogs/ExchangeOfflineDialog.tsx

show exchange offline dialog until we switch to testnet3

show exchange offline dialog for testnet2

---

package.json
pnpm-lock.yaml

- bump v4-localization
- add back pnpm settings

bump v4-localization to use testnet3

---

package.json
pnpm-lock.yaml
src/constants/abacus.ts

* `@dydxprotocol/v4-abacus`
* updated: v0.5.4 -> v0.5.11
* `src/constants/abacus.ts`
* Update based on abacus changes

bump abacus

---

src/App.tsx

* `src/App.tsx`
* Do not gate reward page route

Do not hide rewardpage on prod

---

public/configs/env.json
src/constants/wallets.ts
src/views/dialogs/OnboardingDialog/GenerateKeys.tsx

action should read "dYdX Chain Onboarding" during signing message
since updating the message will change the derived dydx address, we will wait until testnet reset to update on testnet and remove the need to config then

update sign typed data domain name and action for non-testnet envs

---

public/configs/env.json

`public/configs/env.json`
- Update URL for staging and testnets

Update Squid URL

---

public/configs/env.json

Update configurations for testnet-4

TRCL-3010 Change test net chain ID and token denom

---

src/constants/wallets.ts
src/lib/wagmi.ts

Override walletconnect explorer recs

---

src/App.tsx
src/constants/routes.ts
src/layout/Header/HeaderDesktop.tsx
src/pages/PrivacyPolicyPage.tsx
src/pages/TermsOfUsePage.tsx
src/styles/articleMixins.ts
src/views/dialogs/OnboardingDialog/AcknowledgeTerms.tsx

add `/terms` and `/privacy` pages, content to be updated later

add empty terms + privacy pages

---

src/hooks/useDydxClient.tsx
src/hooks/useTokenConfigs.ts

* `src/hooks/useDydxClient.tsx`
* pass in token configs to validator params.

update v4-client init in useDydxClient

---

package.json
pnpm-lock.yaml
src/views/dialogs/OnboardingDialog.tsx
src/views/dialogs/OnboardingDialog/AcknowledgeTerms.tsx

* `src/views/dialogs/OnboardingDialog/AcknowledgeTerms.tsx`
* Update and add additional copies
* Add a close button
* `src/views/dialogs/OnboardingDialog.tsx`
* Disconnect if the dialog is closed when the user is on the acknowledgement dialog
* updated: v0.1.30 -> v0.1.32

Update acknowledge copies

---

public/configs/env.json

Indexer and validator are on https for DEV

---

public/configs/env.json

TODO:
Add the Polkachu RPC node as an additional option for testnet
---

Add Polkachu as RPC Node for Testnet

---

public/configs/env.json

Link to Intercom page... Currently only set for staging with the v3 link for testing.

Add link to help page

---

public/configs/wallets.json

Add Android config to wallets.json

---

package.json
pnpm-lock.yaml
public/configs/env.json
src/hooks/useSquid.tsx

* `public/configs/env.json`
* Add `squidIntegratorId` to environment configs for squid API
* bump abacus to 1.0.10

Configurable squid integrator id

---

public/configs/env.json

---
Update all dev4 endpoints to use https and wss

Update all dev4 endpoints to use https and wss

---

public/configs/env.json

Expected behavior when the parent ticket is completed - when "v4 Staging Forced Update" is selected in iOS app, it should switch to the forced update screen

TRCL-3077 Added an environment for testing. 

---

package.json
pnpm-lock.yaml
src/state/inputsSelectors.ts
src/views/forms/ClosePositionForm.tsx

- surface abacus close position input validation errors as AlertMessage and button action text

Surface close position input errors

---

src/views/forms/TransferForm.tsx
src/views/forms/TransferForm/TransferButtonAndReceipt.tsx

when send/transferring N native tokens, destination wallet should receive N native tokens, instead of N - fee.

Send native tokens inclusive fee

---

src/components/SearchInput.tsx
src/components/Table.tsx
src/hooks/useAccounts.tsx
src/pages/portfolio/Fees.tsx
src/styles/tradeViewMixins.ts
src/views/MarketsDropdown.tsx

- fix 24h volume sorting
- reduce font size and match font sizes across Table components
- search input autofocus
- bandaid fix on double border on table header + first tr in body

Market dropdown fixes and improvements

---

src/pages/portfolio/Portfolio.tsx
src/pages/rewards/DYDXBalancePanel.tsx
src/views/TransferStatusSteps.tsx

- Add additional onboarding entry points to profile side nav
- remove receive on rewards page token module
- Fix squid withdraw transaction URL

Add additional onboarding entry points

---

src/components/ToggleButton.tsx

add back border to toggle buttons

---

package.json
pnpm-lock.yaml

Market Orders execution changed from `IOC` -> `FOK`.
---
* `v4-abacus`
* updated: v1.0.24 -> v1.0.25
---

Bump Abacus 1.0.25

---

src/views/dialogs/OnboardingDialog/AcknowledgeTerms.tsx

so that on mobile view the button is on the bottom of the screen, similar to all other forms

nit: move buttons to footer in ack terms

---

src/components/Toast.tsx
src/components/ToastArea.tsx
src/layout/NotificationsToastArea.tsx

https://github.com/dydxprotocol/v4-web/assets/13111994/07b594ae-9e41-4d45-aeb1-db3fb952a756
---
* `<NotificationsToastArea>`
* Add pill button to stack/unstack toast notifications
* Button is revealed on hover
* `<Toast>`
* Use `Button.Shape`

Add button to stack/unstack Toast notifications

---

src/components/Button.tsx
src/layout/Footer/FooterDesktop.tsx

Fix Button component to handle href prop.
---
* `<FooterDesktop>`
* pass statusPage `href`
* `<Button>`
* handle href prop by wrapping button in anchor tag
---

Add href prop to button component

---

src/constants/markets.ts
src/hooks/useMarketsData.ts
src/hooks/useTestFlags.tsx
src/views/ExchangeBillboards.tsx

Add temporary filter to markets list and add test flag
---
* `<ExchangeBillboard>`
* filter stats based on `MARKETS_TO_DISPLAY`
* temporary hard-coded list of available markets
* `hooks/useTestFlags`
* add `displayAllMarkets` flag
* `hooks/useMarketsData`
* filter markets based on `MARKETS_TO_DISPLAY` 
---

Filter markets and add test flag

---

src/components/Input.tsx

https://developer.1password.com/docs/web/compatible-website-design/
repro:
- go to withdraw / transfer dialog / form, focus on address input

prevent 1password fill

---

public/configs/env.json

Config: Fix path to chainLogo

---

package.json
pnpm-lock.yaml

- Update Abacus for block reward info
- Update `WAGMI` for security
---
* `v4-abacus`
* 
* updated: v1.1.22 -> v1.1.23
* `wagmi`
* updated: v1.4.5 -> v1.4.12 
---

Bump v4-Abacus & WAGMI

---

src/views/forms/AccountManagementForms/DepositForm/DepositButtonAndReceipt.tsx
src/views/forms/AccountManagementForms/WithdrawForm/WithdrawButtonAndReceipt.tsx

Update receipt items and order in Withdraw Form. Update `slippage` -> `max slippage` in Deposit form receipt.
---
* `<WithdrawButtonAndReceipt>`/`<DepositButtonAndReceipt>`
* Change order of receipt items in `<WithdrawButtonAndReceipt>`
* Update `slippage` -> `Max Slippage` for both receipts
---

Update Withdraw form receipt

---

package.json
pnpm-lock.yaml

Fix good til time input for long term orders by bumping Abacus.
---
* `v4-abacus`
* updated: v1.1.24 -> v1.1.25
---

Update abacus to 1.1.25: Good til time fix

---

src/App.tsx
src/pages/AlertsPage.tsx
src/pages/PrivacyPolicyPage.tsx
src/pages/TermsOfUsePage.tsx
src/pages/portfolio/Portfolio.tsx
src/pages/rewards/RewardsPage.tsx
src/pages/settings/Settings.tsx

Speed up initial launch of website. Lazy load all pages/subpages
---
Update `App.tsx` and `Portfolio.tsx` to lazy load pages
---

Lazy load Pages

---

public/configs/env.json

Update link to `Secret Phrase export`  article within config

Export secret phrase help article

---

public/configs/cctp.json

- only goerli has cctp routes working with squid

remove testnet cctp chains

---

package.json
pnpm-lock.yaml
src/lib/wagmi.ts
src/views/forms/AccountManagementForms/TokenSelectMenu.tsx

- add kava and scroll support for wagmi
- Add token symbol in the token select dropdown during onboarding
- bump abacus to include https://github.com/dydxprotocol/v4-abacus/pull/196
Follow up: We should add custom chain support based on squid sdk-info response.

Add Kava support for onboarding, and add token symbol to token select

---

src/views/MarketDetails.tsx

Remove BasePositionNotional.
---
* `<MarketDetails>`
* Remove BasePositionNotional DetailItem
---

Remove BasePositionNotional DetailItem

---

public/configs/env.json
src/lib/wagmi.ts

---
* `lib/wagmi`
* 
* Add `Sepolia` chain info to wagmiConfig
* `env.json`
* testnet evmChainId: `5` -> `11155111` 
---

Update Testnet evmChain to Sepolia

---

src/lib/testFlags.ts
src/views/menus/AccountMenu.tsx

- add `mobilesignin` test flag option
- update to case-insensitive param
- remove cctp since it's no longer used

test flag for mobile sign in option

---

package.json
pnpm-lock.yaml

https://github.com/follow-redirects/follow-redirects/issues/237

downgrade follow-redirects since new version breaks safari

---

src/lib/testFlags.ts
src/views/forms/AccountManagementForms/SourceSelectMenu.tsx

remove cexdeposit testflag

---

src/App.tsx

---
* 
* 
* 
* New: ``
* 
* 
* 
* 
* New: ``
* 
* 
* New: ``
* 
* 
* 
* `lib/_____`
* 
* 
* 
* 
* 
* 
* 
* 
* 
---

Fix missing provider

---

package.json
pnpm-lock.yaml
src/pages/rewards/LaunchIncentivesPanel.tsx

Update "Powered By" to be all caps from PR [here](https://github.com/dydxprotocol/v4-localization/commit/b4064d61d52f5451324921eb17773e011463604c).

Update PoweredBy string key to use all caps version

---

public/.well-known/assetlinks.json

This creates an association between the Android app and the website.  [[More info](https://developer.android.com/training/app-links/verify-android-applinks#web-assoc)]

Config: Add Digital Asset Links for android app

---

.ladle/components.tsx
package.json
pnpm-lock.yaml
src/components/Details.stories.tsx
src/components/DropdownMenu.stories.tsx
src/components/DropdownSelectMenu.stories.tsx
src/components/Icon.stories.tsx
src/components/Link.stories.tsx
src/components/NavigationMenu.stories.tsx
src/components/SearchInput.stories.tsx
src/components/SearchSelectMenu.stories.tsx
src/components/SelectMenu.stories.tsx
src/components/Tabs.stories.tsx
src/components/Tag.stories.tsx
src/components/Tag.tsx
src/components/ToggleButton.stories.tsx
src/components/ToggleGroup.stories.tsx
src/components/WithLabel.stories.tsx
src/components/WithReceipt.stories.tsx
src/components/WithTooltip.stories.tsx
src/views/PositionTile.stories.tsx

Update ladle version from `v2.15.0` -> `v4.0.2` and fix parameter types in Stories
To Test:
- `pnpm ladle`

Fix ladle environment

---

package.json
pnpm-lock.yaml
src/hooks/usePotentialMarkets.tsx
src/pages/token/Governance.tsx
src/pages/token/Token.tsx
src/pages/token/staking/StakingPage.tsx
src/pages/token/staking/StakingPanel.tsx
src/pages/token/staking/StrideStakingPanel.tsx
src/views/dialogs/ExternalLinkDialog.tsx
src/views/dialogs/ExternalNavKeplrDialog.tsx
src/views/dialogs/ExternalNavStrideDialog.tsx

Uploading Screen Recording 2024-02-07 at 9.38.47 PM.mov…
- Add localization
- Add ExternalLinkDialog for Keplr

Liquid staking language and localization

---

src/components/Details.tsx
src/components/DetailsDialog.tsx

wrap details item + fix cancel reason overflow/overlay

---

src/hooks/usePageTitlePriceUpdates.ts
src/state/perpetualsSelectors.ts

CT-428 Update browser tab title to be mid market price

---

package.json
pnpm-lock.yaml
src/pages/token/rewards/RewardHistoryPanel.tsx
src/pages/token/rewards/RewardsPage.tsx

will update this again after https://github.com/dydxprotocol/v4-web/pull/298 is shipped -- but want to ship this to testnet asap

show trading rewards in testnet

---

package.json
pnpm-lock.yaml
src/views/dialogs/ExternalNavKeplrDialog.tsx

https://github.com/dydxprotocol/v4-web/assets/13111994/343116b8-672a-4bd9-8dd8-b413fff55a53
Add additional language for Keplr links.
---
* `<ExternalNavKeplrDialog>`
* Add updated strings
* `@dydxprotocol/v4-localization`
* updated: v1.1.29 -> v1.1.30
---

Updated Keplr language

---

src/pages/token/rewards/LaunchIncentivesPanel.tsx

replace hardcoded season number with query
i think abacus will support this soon, but just in case this get launches in the next few days we're ready

fetch chaos labs latest season

---

src/lib/testFlags.ts
src/views/forms/AccountManagementForms/SourceSelectMenu.tsx

Enable Cex withdrawal by removing CEX withdraw testflag

Remove CEX withdraw testflag

---

package.json
pnpm-lock.yaml
src/constants/analytics.ts
src/constants/notifications.ts
src/hooks/useNotificationTypes.tsx
src/hooks/useNotifications.tsx

---
* `src/constants/analytics.ts`
* Add `AnalyticsEvent.NotificationAction`
* `src/hooks/useNotificationTypes.tsx`
* add support for `NotificationType.ChaosLabs`
* Set expiration date to be 2024-03-08
* trigger the notification. Hardcode the values
* Navigate to token page on click
* `src/hooks/useNotifications.tsx`
* Add `NotificationType.ChaosLabs`
* Add tracking for whenever notifications are clicked to `onNotificationAction`
* Update v4-localization

Add notification for season 3 incentives

---

package.json
pnpm-lock.yaml

bump abacus to include: https://github.com/dydxprotocol/v4-abacus/pull/229

bump abacus to have USDC default for CCTP

---

src/constants/notifications.ts
src/hooks/useNotificationTypes.tsx

Remove "Rewards and Full Trading Live" notification

Remove trading is live notification

---

src/lib/testFlags.ts

Handle BrowserRouter when determining testflags

Handle BrowserRouter for testFlags

---

src/views/AccountInfo/AccountInfoConnectedState.tsx

Update transfer button style in accordance with design:

Update transfer button style

---

public/configs/v1/env.json

disable Reduce only in configs

Disable reduce-only

---

public/configs/otherMarketData.json
scripts/validate-other-market-data.ts

ASTR, FLOKI, and FLOW added. PORTAL removed with 3 robust oracles.

chore(newmarkets): astr, floki, flow, edit portal

---

.github/workflows/commitlint.yml
commitlint.config.ts

Remove subject-case enforcement.

build(commitlint): Remove subject-case ENFORCEMENT

---

src/components/RadioButtonCards.stories.tsx
src/components/RadioButtonCards.tsx

https://github.com/dydxprotocol/v4-web/assets/13111994/840e2c9d-85e0-4471-b5d8-98ae3738e6b9
Create new component.
---
* New: `<RadioButtonCards>`
* Add new RadioButtonCards component and component story
---

feat(radiobuttoncards): add new radio button cards component

---

src/hooks/useNotifications.tsx

This reverts commit 844648966774326ee05c495e438d96a4357c4a76.

Revert "Adam/ote 207 user local storage exceeding limits (#358)"

---

src/constants/notifications.ts
src/hooks/useNotificationTypes.tsx
src/hooks/useQueryChaosLabsIncentives.ts
src/pages/token/rewards/LaunchIncentivesPanel.tsx
src/views/notifications/IncentiveSeasonDistributionNotification.tsx

Add new notification for Season 2 `dydxRewards` distribution. Localization to follow a long with prepping for future distribution notifications.
---
* New: `<IncentiveSeasonDistributionNotification>`
* Add new notification
* `constants/notifications`
* add new notification Id
* `hooks/useNotificationTypes`
* Add new notification in `NotificationTypes.ReleaseUpdates`
* `hooks/useQueryChaosLabsIncentives` `<LaunchIncentivesPanel>`
* Move query hook from `<LaunchIncentivesPanel>` to its own dedicated file to be re-used.
---

chore(notification): Add Chaos Labs Season 2 Distribution notification

---

package.json
pnpm-lock.yaml
src/constants/notifications.ts
src/hooks/useLocalNotifications.tsx
src/lib/abacus/rest.ts
src/lib/squid.ts
src/views/forms/AccountManagementForms/DepositForm.tsx
src/views/forms/AccountManagementForms/WithdrawForm.tsx

Add the squid requestId provided through abacus to the squid status header for better squid status tracking. Also includes a fix for a status tracking race condition bug.

fix(onboarding): Add requestId to squid status

---

package.json
pnpm-lock.yaml

@wdio/sync is deprecated and not needed. It is breaking Vercel builds

fix(e2e): remove @wdio/sync

---

src/constants/analytics.ts
src/views/forms/AccountManagementForms/DepositForm.tsx
src/views/forms/AccountManagementForms/WithdrawForm.tsx

Added additional metadata to deposit events
I tested with unit tests (`pnpm run test`)

chore(onboarding): Add additional metadata to deposit events

---

scripts/validate-other-market-data.ts

---
* 
* 
* 
* New: ``
* 
* 
* 
* 
* New: ``
* 
* 
* New: ``
* 
* 
* 
* `lib/_____`
* 
* 
* 
* 
* 
* 
* 
* 
* 
---

ci(validate-other-market-data): validate that exchanges are unique in other market data validation

---

public/configs/v1/env.json

update feature flag `usePessimisticCollateralCheck` to false for testnet

feat(collat check): use optimistic collat check for testnet

---

src/main.tsx

fix(polyfills): re-add polyfill

---

src/hooks/useNotificationTypes.tsx

Remove trigger for S2 distribution
---
* `hooks/useNotificationTypes`
* comment out s2 distribution notifs but keep to use for future distributions
---

chore(remove-notifs): Remove trigger for S2 distribution

---

public/configs/v1/env.json
src/hooks/useURLConfigs.ts
src/pages/token/rewards/RewardsHelpPanel.tsx

Add help link to env configs
---
* `<RewardsHelpPanel>`
* use url from url hook
* `hooks/useURLConfigs`
* alphabetize and add new link
* `env.json`
* Add new link 
---

chore: Add help link to env configs

---

public/configs/v1/env.json

miscommunicated testnet version -- reverting back to use pessimistic collat check on testnet

feat(collat check): use pessimistic collat check on testnet

---

package.json
pnpm-lock.yaml

https://github.com/dydxprotocol/v4-abacus/pull/262

fix(validation): bump abacus for slippage validation update

---

src/hooks/tradingView/useTradingView.ts

make sure there's one active chart

fix: trading view chart error

---

src/constants/websocket.ts
src/lib/abacus/websocket.ts

custom ping message support is removed from indexer
update our ws implementation to no longer rely on ping/pongs, since heartbeat already exists on indexer [side](https://github.com/dydxprotocol/v4-chain/blob/d83ea90e937721c02f08a31bf1ee9a37b7d6c5f1/indexer/services/socks/src/websocket/index.ts#L153)
tested on testnet

fix: remove pingpongs from ws since no longer supported

---

scripts/install-local-abacus.js

Adds a new `--clean` flag to the `install-local-abacus` script that will clean a bunch of things up. Recommend running`pnpm run install-local-abacus --clean` once and then continuing to use `pnpm run install-local-abacus` for all development.

build: Add --clean flag to install-local-abacus

---

public/configs/v1/env.json

turn on reduce only and withdrawal safety for release

feat: update reduceonly and withdrawal safety feature flags

---

src/pages/portfolio/Overview.tsx
src/pages/portfolio/Positions.tsx
src/pages/trade/HorizontalPanel.tsx
src/state/accountCalculators.ts
src/views/tables/PositionsTable.tsx
src/views/tables/PositionsTable/PositionsActionsCell.tsx

I forgot that the positions tables on Portfolio + Overview should support SL/TP - right now state looks sorta broken because I don't render the actions column
- Update in this PR to render the actions column there, just without the close positions button
ugh sorry running to dentist, can flesh out more later if this isn't straight forwards
Note that SlTp does not show up in table after i refresh (cuz the flag is no longer on):
https://github.com/dydxprotocol/v4-web/assets/70078372/1f7a85b2-61a3-4a98-ad9c-dd052e2dcf95
---
* 
* 
* 
* New: ``
* 
* 
* 
* 
* New: ``
* 
* 
* New: ``
* 
* 
* 
* `lib/_____`
* …

fix(sltp): fix positions tables in non trade views when sltp flag is on

---

package.json
pnpm-lock.yaml
public/configs/v1/env.json

https://github.com/dydxprotocol/v4-abacus/pull/304
tested locally, FE validation should now be much more optimistic, and let protocol fail

feat: bump abacus and use optimistic collat check for staging and testnet

---

package.json
pnpm-lock.yaml
public/configs/otherMarketData.json
scripts/validate-other-market-data.ts

updated the json with the latest data
new coins: ETHFI, PENDLE, JASMY, XAI, QNT

feat(widget): json update

---

public/configs/markets.json

Fix rendering assetIcon by adding `dydx-usd` to markets config.

fix(asset-info): add dydx to market config

---

src/constants/notifications.ts
src/hooks/useNotificationTypes.tsx
src/views/notifications/IncentiveSeasonDistributionNotification.tsx

- I will follow up with localization.

chore(notification): Add notification for s3 rewards distribution

---

src/state/configs.ts

[context](https://dydx-team.slack.com/archives/C03GKH23YAZ/p1714411927605929)

chore: default to all markets in table views to be true

---

public/configs/otherMarketData.json

1. added a filter for existing markets
2. market id increments by 1 as intended

feat: update json with the latest data

---

src/views/forms/AccountManagementForms/SourceSelectMenu.tsx

withdrawals non-privy wallet
deposits non-privy wallet
withdraw with privy wallet
deposits with privy wallet

feat: enable regular withdrawals for privy users [OTE-282]

---

src/components/Details.tsx
src/views/forms/NobleDeposit.tsx

fix: make noble addres selectable

---

package.json
pnpm-lock.yaml

* `abacus`
* 
* updated: v1.7.3 -> v1.7.4: https://github.com/dydxprotocol/v4-abacus/pull/342
Tested that orders + fills still update as expected on UI.

chore(perf): update abacus to pull in batched subaccount orders

---

src/views/forms/AccountManagementForms/WithdrawForm/WithdrawButtonAndReceipt.tsx

https://github.com/dydxprotocol/v4-web/pull/461/files#diff-7f1d8617fc4bfc99bd9e04caff0dbec3ebf08549d1567d30a71e68fa29323c39R113
artifact left from local testing before i understood how to trigger gas/bridge fees to display on the UI

fix: hardcoded gasfee from local testing

---

public/configs/v1/env.json

- update `env.json` to support dev3 environment

feat(dev-3): add dev3 environment

---

src/views/forms/AccountManagementForms/DepositForm.tsx

check that cctp deposits have minimum value of 10 usdc

fix: deposit value check

---

src/state/accountCalculators.ts
src/views/tables/PositionsTable.tsx

pre isolated margin:
post isolated margin:

fix: positions table close/action column title

---

src/components/Table/TableCell.tsx

fix: stacked styling default

---

public/configs/v1/env.json
src/hooks/useEnvFeatures.ts
src/views/forms/AccountManagementForms/SourceSelectMenu.tsx
src/views/forms/AccountManagementForms/TokenSelectMenu.tsx

with CCTPDepositOnly enabled
with CCTPDepositOnlyDisabled

chore: add CCTPDepositOnly FF

---

src/views/dialogs/HelpDialog.tsx

Add release version, also helpful for debugging.

chore: Add latest version to web help dialog

---

README.md
public/configs/env.json

make it a bit more clear what `env.json` vs `v1/env.json` is.

chore: note in env file about deprecation

---

.eslintignore
.eslintrc.json
src/main.tsx
src/state/account.ts
src/state/inputs.ts
src/state/inputsSelectors.ts
src/state/perpetualsSelectors.ts

Prefer ?? over || and removed unnecessary ignores.

chore: New es-lint rule, clean up some easy es-lint fixes

---

package.json
pnpm-lock.yaml
src/constants/abacus.ts

to pull in https://github.com/dydxprotocol/v4-abacus/commit/5eaad167b6ba3d19c1872ee81673798abb6a0d2c

chore: update abacus, fix import

---

src/lib/analytics.ts

missing amplitude event data because of mismatched name :(

fix: missing analytics data

---

src/hooks/Orderbook/useDrawOrderbook.ts
src/hooks/tradingView/useChartLines.ts
src/hooks/tradingView/useTradingViewTheme.ts
src/hooks/useAccounts.tsx
src/hooks/useDydxClient.tsx
src/hooks/useEndpointsConfig.ts
src/hooks/useMarketsData.ts
src/hooks/useQueryChaosLabsIncentives.ts
src/hooks/useSubaccount.tsx

chore: run lint-fix on /hooks

---

package.json
pnpm-lock.yaml

chore: update localization for updated buying power tooltip text

---

src/components/Button.tsx
src/components/Collapsible.tsx
src/components/ComboboxMenu.tsx
src/components/DiffOutput.tsx
src/components/DropdownMenu.tsx
src/components/NavigationMenu.tsx
src/components/PageMenu/PageMenuRadioGroup.tsx
src/components/Panel.tsx
src/components/SearchInput.tsx
src/components/Tabs.tsx
src/components/ToggleGroup.tsx
src/components/WithHovercard.stories.tsx
src/components/visx/XYChartThreshold.tsx
src/components/visx/XYChartTooltipWithBounds.tsx

chore: run auto fixer on /components

---

src/hooks/useSubaccount.tsx
src/views/forms/TriggersForm/TriggersForm.tsx

remove loading state -> show order toasts instead
https://github.com/dydxprotocol/v4-web/assets/9400120/d816f926-938d-4e19-a213-698a4b773574

chore: update transition states for triggers form

---

.eslintignore
.eslintrc.json
src/views/AccountInfo.tsx
src/views/ExchangeBillboards.tsx
src/views/MarketDetails.tsx
src/views/MarketLinks.tsx
src/views/MarketStatsDetails.tsx
src/views/MarketsDropdown.tsx
src/views/MarketsStats.tsx
src/views/MidMarketPrice.tsx
src/views/PositionInfo.tsx
src/views/PositionTile.stories.tsx
src/views/PositionTile.tsx
src/views/TradeBoxOrderView.tsx

Ran auto fix and fixed some errors manually

chore: apply eslint to top level files in /views

---

.eslintignore
src/constants/objects.ts
src/hooks/useMarketsData.ts
src/lib/typeUtils.ts
src/views/menus/AccountMenu.tsx
src/views/menus/NotificationsMenu.tsx
src/views/menus/useGlobalCommands.tsx
src/views/tables/FillsTable.tsx
src/views/tables/FundingPaymentsTable.tsx
src/views/tables/LiveTrades.tsx
src/views/tables/MarketsTable.tsx
src/views/tables/Orderbook.tsx
src/views/tables/OrdersTable.tsx
src/views/tables/OrdersTable/OrderActionsCell.tsx
src/views/tables/PositionsTable.tsx
src/views/tables/PositionsTable/PositionsActionsCell.tsx
src/views/tables/PositionsTable/PositionsTriggersCell.tsx
src/views/tables/TransferHistoryTable.tsx

chore: eslint the rest of easy views

---

src/views/forms/AccountManagementForms/DepositForm.tsx
src/views/forms/AccountManagementForms/SourceSelectMenu.tsx
src/views/forms/AccountManagementForms/TokenSelectMenu.tsx
src/views/forms/AccountManagementForms/WithdrawForm.tsx
src/views/forms/NewMarketForm/NewMarketSelectionStep.tsx
src/views/forms/TradeForm/LeverageSlider.tsx
src/views/forms/TradeForm/PlaceOrderButtonAndReceipt.tsx
src/views/forms/TriggersForm/LimitPriceInputs.tsx
src/views/forms/TriggersForm/OrderSizeSlider.tsx
src/views/forms/TriggersForm/TriggerOrderInputs.tsx
src/views/forms/TriggersForm/TriggerOrdersInputs.tsx
src/views/forms/TriggersForm/TriggersForm.tsx

chore: run auto fix on views/forms

---

package.json
pnpm-lock.yaml
src/components/Table.tsx
src/lib/abacus/websocket.ts

These should make other changes easier and maybe even reduce bundle size.

chore: pnpm cleanup tasks: prune, dedupe

---

src/pages/trade/Trade.tsx

feat: make the order table bigger on medium desktop

---

public/configs/env.json
public/configs/v1/env.json

Config only.  The force update content only impacts mobile.

fix: Update mintscanBase and add android force update test data

---

src/lib/tradeData.ts
src/views/tables/PositionsTable.tsx
src/views/tables/PositionsTable/PositionsMarginCell.tsx

Use subaccount quoteBalance instead of position.

fix: position margin calculation for cross margin positions

---

src/components/Table.tsx
src/pages/portfolio/Fees.tsx
src/views/tables/FillsTable.tsx
src/views/tables/MarketsCompactTable.tsx
src/views/tables/MarketsTable.tsx
src/views/tables/OrdersTable.tsx
src/views/tables/PositionsTable.tsx
src/views/tables/TradingRewardHistoryTable.tsx
src/views/tables/TransferHistoryTable.tsx

Now the records are correctly checking for exhaustivity and value types matching.

fix: type check records correctly

---

package.json
pnpm-lock.yaml
src/constants/notifications.ts
src/hooks/useNotificationTypes.tsx

Update for S5; params [here](https://dydx-team.slack.com/archives/C05FB5XECHZ/p1716566286293399)
~~Jk we don't want this merged until s5 starts I can't read~~; also dependent on https://github.com/dydxprotocol/v4-localization/pull/467

chore(incentives): Update notification for incentives season 5

---

src/components/Details.tsx
src/pages/portfolio/Fees.tsx
src/styles/articleMixins.ts
src/styles/formMixins.ts
src/styles/tableMixins.ts
src/styles/tradeViewMixins.ts

Should be the last of them...I think.

chore: properly type more style mixins

---

src/pages/portfolio/Overview.tsx
src/pages/portfolio/Positions.tsx
src/pages/trade/HorizontalPanel.tsx
src/pages/trade/UnopenedIsolatedPositions.tsx
src/views/tables/OrdersTable.tsx

feat: show unopened isolated market positions on portfolio pages

---

src/pages/trade/UnopenedIsolatedPositions.tsx
src/state/accountSelectors.ts

Filter to just unopened isolated positions that have actual margin

fix: use nonzero unopened isolated positions

---

src/hooks/Orderbook/useDrawOrderbook.ts

orderbook looks borked when super zoomed out (e.g. 33% on chrome / macbook):
looks like canvasWidth/canvasHeight isn't updated correctly (draw canvas functions are using older values); update to store them in local state as fix

chore: fix super zoomed out orderbook

---

src/views/MarketsDropdown.tsx

should be performant enough because it'll be <200/300 rows

fix: switch market selector dropdown to infinite scroll

---

package.json
pnpm-lock.yaml
src/views/dialogs/AdjustIsolatedMarginDialog.tsx
src/views/forms/AdjustIsolatedMarginForm.tsx

feat: polish adjust isolated margin form

---

src/views/tables/PositionsTable.tsx
src/views/tables/PositionsTable/PositionsTriggersCell.tsx

feat: disabled isolated trigger editing

---

.github/workflows/validate-other-market-data.yml
scripts/validate-other-market-data.ts

remove datadog from other market validation, reduce block time, and print out errors at the end

feat: update validation flow to finish despite errors

---

src/components/Tabs.tsx
src/views/TradeBoxOrderView.tsx

No visual difference but on hover mouse becomes a disabled pointer

fix: disable order type change when wallet disconnected

---

scripts/validate-other-market-data.ts

---
* 
* 
* 
* New: ``
* 
* 
* 
* 
* New: ``
* 
* 
* New: ``
* 
* 
* 
* `lib/_____`
* 
* 
* 
* 
* 
* 
* 
* 
* 
---

feat(new market widget): fix long type of validation script

---

package.json
pnpm-lock.yaml
public/configs/v1/env.json
src/constants/notifications.ts
src/hooks/useNotificationTypes.tsx
src/hooks/useURLConfigs.ts

Two notifs, but the second will not run until the proposal passes.

chore: market wind down notifications

---

src/hooks/usePageTitlePriceUpdates.ts

chore: add min fraction digits to price for page title

---

src/views/forms/AccountManagementForms/DepositForm.tsx

https://github.com/dydxprotocol/v4-web/assets/1062252/91bcc44b-2cbd-443b-bebd-1814e02ad72c

fix: set abacus source address when deposit form initialize

---

package.json
pnpm-lock.yaml
src/state/perpetualsSelectors.ts
src/views/forms/AdjustIsolatedMarginForm.tsx

Add validation to the form using FE elements. Add to Abacus as new validator for follow up.
---
* `<AdjustIsolatedMarginForm>`
* Handle validation on the FE for now.
* `state/perpetualsSelector`
* add `getMarketMaxLeverage` selector
* `v4-abacus`
* updated: v1.7.71 -> v1.7.72
---

chore(adjust-isolated-margin): handle validation on web

---

src/components/Details.tsx
src/components/Tag.tsx
src/index.css
src/views/charts/TvChart.tsx
src/views/forms/NobleDeposit.tsx

feedback that people want to copy / select things, especially position size etc., and just in general
allow user selection almost everywhere except charts + sliders

chore: make almost everything selectable

---

src/views/forms/AdjustIsolatedMarginForm.tsx

Add additional validation based on the transfer `amount` input.
---
* `<AdjustIsolatedMargin>`
* Add `amount` validation because `PostOrder` states become null when the inputs are overly offensive.
---

chore(adjust-margin): add additional validation

---

src/views/forms/NewMarketForm/NewMarketSelectionStep.tsx

---
* `<NewMarketSelectionStep>`
* Remove `isDev` filter
---

fix(new-market-filter): remove isolated filter

---

package.json
pnpm-lock.yaml

chore: bump abacus

---

src/hooks/Orderbook/useOrderbookMiddleRowScrollListener.ts
src/hooks/usePageTitlePriceUpdates.ts
src/state/perpetualsSelectors.ts
src/views/CanvasOrderbook/OrderbookRow.tsx
src/views/CanvasOrderbook/index.tsx
src/views/tables/Orderbook.tsx

spread looks broken / product wants to just replace it with mid market price

chore: replace spread row with mid market price row

---

public/configs/v1/env.json
src/App.tsx
src/hooks/useEnvFeatures.ts
src/layout/Header/HeaderDesktop.tsx
src/lib/testFlags.ts
src/pages/token/Token.tsx
src/pages/token/rewards/GovernancePanel.tsx
src/pages/token/rewards/NewMarketsPanel.tsx
src/pages/token/rewards/RewardsHelpPanel.tsx
src/pages/token/rewards/RewardsNavPanel.tsx
src/pages/token/rewards/RewardsPage.tsx
src/pages/token/rewards/StakingPanel.tsx

enabled for everything except mainnet; lmk if we don't want it on testnet but figured it's easier for bugbashing anyways
---

chore(staking): update staking to be flagged in env.json

---

src/pages/markets/Markets.tsx
src/views/ExchangeBillboards.tsx
src/views/MarketsStats.tsx
src/views/tables/MarketsCompactTable.tsx

The aim of this PR is to improve the style of the markets page, recovering some vertical space and improving the formatting of the 'Earned by Stakers' statistic

feat: improve markets page style

---

src/App.tsx
src/constants/routes.ts

Update default page
---
* `<App>`
* change default redirect to Markets page
---

chore(default-page): change default page to /markets

---

public/configs/v1/env.json
src/hooks/useURLConfigs.ts
src/pages/token/rewards/RewardsHelpPanel.tsx

per slack thread [here](https://dydx-team.slack.com/archives/C06FEME7771/p1719001454470359?thread_ts=1718920886.326169&cid=C06FEME7771)

chore(staking): remove last faq question

---

src/constants/analytics.ts
src/views/dialogs/StakingRewardDialog.tsx
src/views/forms/StakeForm/index.tsx
src/views/forms/UnstakeForm/index.tsx

Added tracking to StakingForm, UnstakingForm, and StakingRewardDialog to track on submit transactions. 
Also refactored the AnalyticsEventData type to be more readable.

feat: add tracking to staking

---

package.json
pnpm-lock.yaml
src/pages/markets/NewMarket.tsx

Update copy on New Markets page.
---
* `<NewMarket>`
* Update copy for Section Header
* updated: v1.1.134 -> v1.1.138
---

chore(new-market): update header copy

---

src/pages/trade/UnopenedIsolatedPositions.tsx
src/pages/trade/types.ts
src/views/StakeRewardButtonAndReceipt.tsx
src/views/dialogs/CancelAllOrdersDialog.tsx
src/views/forms/CancelAllOrdersInMarketForm.tsx

https://linear.app/dydx/issue/TRA-408/expand-unopened-isolated-positions-if-user-has-zero-active-positions
https://linear.app/dydx/issue/TRA-440/isolated-vs-cross-positions-table-filter-does-not-work-properly

fix: isolated positions bug fixes + auto-open

---

README.md
package.json

Developing on l10n is annoying b/c I always forget to link my local package to see the changes live. so i added some stuff to the readme and made a command for it.
TBH the command itself probably isn't useful, but i'm thinking we can eventually make a robust CLI for this app that lets you select what downstream dependencies you want and alias them to certain configurations.

chore: install-local-l10n command

---

src/hooks/Orderbook/useDrawOrderbook.ts
src/views/CanvasOrderbook/CanvasOrderbook.tsx

mine circle opacity
spread row sticky

fix: orderbook bugs

---

src/components/Table.tsx
src/lib/abacus/dydxChainTransactions.ts
src/lib/abacus/index.ts
src/views/MarketsStats.tsx

Change cursor on Table Headers depending on Sort
---
* `<MarketStats>`
* Remove padding-bottom from `SectionHeaders`
* `<Table>`
* use `cursor: pointer` for sortable headers
---

style(tables): update table header styling

---

src/constants/analytics.ts
src/views/forms/StakeForm/index.tsx

add the default validator as part of `StakeTransaction` event

chore(staking): add default validator as part of stake transaction event

---

package.json
pnpm-lock.yaml
public/configs/v1/env.json
src/hooks/useURLConfigs.ts
src/pages/token/rewards/RewardsHelpPanel.tsx

i clicked on it and it worked woohoo

chore(staking): update faq to have see more here link to published help article

---

src/components/DiffOutput.tsx
src/components/Output.tsx
src/hooks/Orderbook/useDrawOrderbook.ts
src/hooks/usePageTitlePriceUpdates.ts
src/lib/consistentAssetSize.ts
src/views/MarketsDropdown.tsx
src/views/charts/DepthChart/index.tsx
src/views/charts/PnlChart.tsx
src/views/charts/TradingRewardsChart.tsx
src/views/forms/AccountManagementForms/WithdrawForm.tsx
src/views/tables/FillsTable.tsx
src/views/tables/FundingPaymentsTable.tsx
src/views/tables/MarketsCompactTable.tsx
src/views/tables/OrdersTable.tsx
src/views/tables/TransferHistoryTable.tsx

Rename and reorder some props, remove locale as an option and use the app locale everywhere. 
I thought about making the props responsive to the type but it got annoying so I bailed out.

chore: minor output cleaning

---

scripts/generate-tag.js

adds `-s` to add tag signing to script

fix: add signing to tag script

---

src/App.tsx
src/components/Table/AssetTableCell.tsx
src/constants/routes.ts
src/hooks/useMarketsData.ts
src/layout/Header/HeaderDesktop.tsx
src/lib/search.ts
src/pages/vaults/Vault.tsx
src/pages/vaults/VaultFilter.tsx
src/pages/vaults/Vaults.tsx
src/pages/vaults/VaultsTable.tsx
src/state/vaultSelectors.ts
src/state/vaults.ts
src/views/VaultDetails.tsx

feat: vaults pages v0

---

package.json
pnpm-lock.yaml

Upgrade abacus to get decimal bugfixes into release
https://github.com/dydxprotocol/v4-abacus/pull/499

feat: upgrade abacus for skip release

---

public/configs/v1/env.json
src/hooks/useComplianceState.tsx
src/hooks/useEnvFeatures.ts

Check for config per network instead of checking for mainnet, so that cayman can avoid this config.

feat: let geo gating be configurable per network

---

src/views/CanvasOrderbook/OrderbookControls.tsx

chore: orderbook UI combines units/grouping

---

.eslintrc.json
public/configs/cctp.json
src/constants/__test__/cctp.spec.ts
src/constants/__test__/newFile.ts
src/constants/cctp.ts
src/constants/tooltips/deposit.ts
src/constants/tooltips/withdraw.ts
src/views/forms/AccountManagementForms/LowestFeesText.tsx
src/views/forms/AccountManagementForms/SourceSelectMenu.tsx
src/views/forms/AccountManagementForms/TokenSelectMenu.tsx

update CCTP json to include Base USDC and Polygon USDC to our CCTP list
Base: https://basescan.org/token/0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913
Polgyon: https://www.oklink.com/polygon/token/0x3c499c542cef5e3811e1192ce70d8cc03d5c3359

feat: increase cctp coverage [OTE-484]

---

package.json
pnpm-lock.yaml

https://github.com/dydxprotocol/v4-abacus/pull/507

fix: bump abacus for isolated sweep fix

---

package.json
pnpm-lock.yaml

bump abacus to get in https://github.com/dydxprotocol/v4-abacus/commit/4001a2c5ab5cdcfef7e11a0b367ab62f1712b8f5 (per request of jared)

chore: update abacus to re-add margin validation

---

src/hooks/useShouldShowTriggers.ts
src/pages/portfolio/Overview.tsx
src/pages/portfolio/Positions.tsx
src/pages/trade/HorizontalPanel.tsx
src/views/forms/TradeForm.tsx
src/views/forms/TradeForm/PlaceOrderButtonAndReceipt.tsx
src/views/tables/PositionsTable.tsx

- Only allow tradeType to be `Market` when the complianceState is `CLOSE_ONLY`
- create `useShouldShowTriggers` for displaying tp/sl trigger column to also check if `complianceState === ComplianceStates.FULL_ACCESS`

fix(compliance): limit close only to market orders

---

src/hooks/useNotificationTypes.tsx

my bad, this value was not updated for last notif distribution 🫠

fix(incentives): fix chaos labs query for rewards earned notification

---

src/App.tsx
src/constants/routes.ts

Context: https://dydx-team.slack.com/archives/C03GKH23YAZ/p1721164024409099?thread_ts=1719960752.546849&cid=C03GKH23YAZ

feat: homepage is trade (ETH-USD) again

---

src/views/dialogs/MnemonicExportDialog.tsx
src/views/dialogs/MobileSignInDialog.tsx

i misread the tag and thought the the p tag was wrapping the necessary text

fix: move hotjar suppression to correct tag

---

package.json
pnpm-lock.yaml

bump abacus to get skip route fixes "one last bugfix? "one last bugfix"

chore: bump abacus to get route fixes

---

package.json
pnpm-lock.yaml
src/views/forms/AdjustIsolatedMarginForm.tsx

fix: disabled adjust isolated margin CTA with action

---

src/components/Table/AssetTableCell.tsx
src/constants/abacus.ts
src/hooks/Orderbook/useOrderbookValues.ts
src/hooks/useMarketsData.ts
src/hooks/usePerpetualMarketsStats.ts
src/lib/marketsHelpers.ts
src/lib/typeUtils.ts
src/pages/vaults/VaultPositionsTable.tsx
src/state/perpetualsSelectors.ts
src/views/MarketsDropdown.tsx
src/views/MarketsStats.tsx
src/views/forms/AdjustIsolatedMarginForm.tsx
src/views/forms/AdjustTargetLeverageForm.tsx
src/views/menus/useGlobalCommands.tsx
src/views/tables/FillsTable.tsx
src/views/tables/FundingPaymentsTable.tsx
src/views/tables/MarketsCompactTable.tsx
src/views/tables/MarketsTable.tsx
src/views/tables/OrdersTable.tsx
src/views/tables/PositionsTable.tsx

feat: show max leverage instead of asset tag

---

package.json
pnpm-lock.yaml

https://github.com/dydxprotocol/v4-abacus/pull/532

fix: bump abacus to include slippage update

---

src/state/perpetualsSelectors.ts
src/views/MarketsDropdown.tsx

feat: show current market leverage in dropdown

---

.github/workflows/validate-other-market-data.yml
scripts/markets/add-markets.ts
scripts/markets/help.ts
scripts/markets/validate-other-market-data.ts

Add an automated script that adds markets to a testing environment

feat(new market): add new market script

---

src/pages/token/RewardsPage.tsx

https://github.com/dydxprotocol/v4-web/pull/774/files#diff-ff4932ccc6b6034047870b2e7de58d3e1c988aa75fadb5b02b7ad10f48be89a4R146
on prod:

fix: dangling semicolon getting rendered

---

public/configs/markets.json

Fix items within market-json to prep for statically typed Abacus
* `public/configs/markets.json`
* Ensure whitepaperLink member exists so it does not break serialization on Abacus side
* remove member vars that do not belong or are flat-out wrong
---

chore(market-json): fix market-json

---

src/pages/token/LaunchIncentivesPanel.tsx

swap cta link from blogpost (which will be deleted) to chaos labs forum link https://dydx.forum/t/launch-of-season-5-of-the-launch-incentive-program/2725/2
https://linear.app/dydx/issue/OTE-382/removing-reward-blogpost-httpsdydxexchangeblogv4-full-trading

feat: swap reward blogpost for chaos labs link [OTE-382]

---

src/components/SearchInput.tsx

fix: search not updating

---

.vscode/settings.json
README.md

adds tailwind vscode configs as prescribed here: https://github.com/dydxprotocol/v4-web/pull/849

chore: add tailwind vscode configs [OTE-668]

---

documentation/RELEASE_PROCESS.md

docs(release): add release process md

---

.github/CODEOWNERS

chore(codeowners): add owners

---

src/lib/errors.ts

better route coming soon messaging - we want to recommend users attempt a different route

feat: better route coming soon messaging [OTE-656]

---

package.json
pnpm-lock.yaml
public/configs/v1/env.json
src/constants/notifications.ts
src/hooks/useNotificationTypes.tsx
src/hooks/useURLConfigs.ts

feat: add notification for discovery program [OTE-704]

---

package.json
pnpm-lock.yaml

https://github.com/dydxprotocol/v4-abacus/pull/568

chore: bump abacus to update Deleveraged -> Liquidated and Offsetting -> Deleveraged on orders + fills

---

package.json
pnpm-lock.yaml
src/views/forms/TriggersForm/TriggersForm.tsx

chore: add sltp info strings to triggers form

---

src/components/Table.tsx

I have been staring at heap dumps for 15 hours and cannot tell you why this leak exists but I know this approach is simpler and fixes it.

fix: memory leaks in table

---

src/lib/tradingView/utils.ts

context: https://dydx-team.slack.com/archives/C07DRA7TZS7/p1724173168660419?thread_ts=1723654679.130969&cid=C07DRA7TZS7

fix(ohlc): update to use orderbook vals if trades <= 10

---

package.json
pnpm-lock.yaml
src/hooks/useStatsig.tsx
src/lib/statsig.ts
src/types/statsig.ts

configurable max safe fee from dynamic config
This PR adds dynamic config values to the statsigconfig object

feat: configurable max safe fee [OTE-663]

---

src/constants/networks.ts
src/lib/statsig.ts

map mode to statsig's environment tier

chore: add environment tier to statsig

---

scripts/markets/validate-other-market-data.ts

---
* 
* 
* 
* New: ``
* 
* 
* 
* 
* New: ``
* 
* 
* New: ``
* 
* 
* 
* `lib/_____`
* 
* 
* 
* 
* 
* 
* 
* 
* 
---

feat(other-market-validation): do not consider id when finding differentmarkets to validate

---

public/configs/v1/env.json
src/constants/statsig.ts
src/hooks/useNotificationTypes.tsx
src/hooks/useStatsig.tsx

and fixed my spacing woohoo
tried passing in a non existent flag and verified no errors were thrown

fix(notifications): follow up to make dynamic config more robust to non existent flags

---

package.json
pnpm-lock.yaml
src/constants/notifications.ts
src/hooks/useNotificationTypes.tsx

Add notification to accompany changes from [proposal 148](https://www.mintscan.io/dydx/proposals/148)
---
* `constants/notifications`
* Add new `MarketUpdateNotificationIds` enum
* Add new `MarketUpdate` NotificationType
* `hooks/useNotificationTypes`
* Add trigger for liq tier update notification
* updated: v1.1.186 -> v1.1.187
---

chore(liq-tier-notif): Add liquidity tier notif

---

public/configs/v1/env.json

---
* 
* 
* 
* New: ``
* 
* 
* 
* 
* New: ``
* 
* 
* New: ``
* 
* 
* 
* `lib/_____`
* 
* 
* 
* 
* 
* 
* 
* 
* 
---

feat: replace dev2 validators with load balancer URL

---

public/configs/v1/env.json

---
* 
* 
* 
* New: ``
* 
* 
* 
* 
* New: ``
* 
* 
* New: ``
* 
* 
* 
* `lib/_____`
* 
* 
* 
* 
* 
* 
* 
* 
* 
---

chore: Fix env.json dev5 validator link

---

package.json
pnpm-lock.yaml
src/constants/notifications.ts
src/hooks/useNotificationTypes.tsx

feat: Add Keplr launch notification

---

package.json
pnpm-lock.yaml
src/constants/notifications.ts
src/hooks/useNotificationTypes.tsx

chore: add notif for incentives program ending

---

src/constants/wallets.ts
src/hooks/useDisplayedWallets.ts
src/hooks/useWalletConnection.ts
src/views/dialogs/OnboardingDialog.tsx

feat: Suggest Metamask wallet if users have no injected wallets detected

---

src/layout/Header/HeaderDesktop.tsx

update documentation text to api documentation

chore: documentation->api documentation

---

package.json
pnpm-lock.yaml
src/components/Tag.tsx
src/constants/notifications.ts
src/constants/statsig.ts
src/hooks/useIncentivesSeason.ts
src/pages/token/LaunchIncentivesPanel.tsx

chore: cleanup incentives s6 flags and update to use concluded tag

---

package.json
pnpm-lock.yaml
src/hooks/tradingView/useChartLines.ts
src/hooks/tradingView/useChartLines.tsx
src/lib/__test__/orderModification.spec.ts
src/lib/orderModification.ts
src/lib/orders.ts

|Limit order|Stop loss|Take profit|
|----------|-----------|---------|
|<img width="368" alt="image" src="https://github.com/user-attachments/assets/20f6a102-11cc-48dc-83ea-8b00b43e1cf8">|<img width="274" alt="image" src="https://github.com/user-attachments/assets/baf13c34-094a-4c5d-971f-0398b358b56e">|<img width="335" alt="image" src="https://github.com/user-attachments/assets/e71252a3-3245-4ccf-9a93-496e474d7f87">|

feat: Add order modification error strings

---

src/clients/metadataService.ts
src/lib/metadataService.ts

Add metadata service client
---
* `lib/metadataService`
* Add simple client for querying metadata
* add `VITE_METADATA_SERVICE_URI`
---

feat(metadata-client): add client for metadata service

---

package.json
pnpm-lock.yaml
public/configs/markets.json
src/constants/markets.ts
src/hooks/useMarketsData.ts
src/views/MarketsDropdown.tsx

Add `Forex` filter
---
* add filter
* `hooks/useMarketsData`
* add filter fn
* updated: v1.1.198 -> v1.1.199
---

feat(forex): add forex filter

---

src/views/dialogs/CancelAllOrdersConfirmationDialog.tsx

missed an edge case
test cases, assuming current market is ETH-USD:
- only orders in non-ETH markets
- only orders in ETH market
- orders in both ETH and non-ETH markets
- no orders

fix: update options for cancel all when no current market orders

---

package.json
pnpm-lock.yaml
src/constants/abacus.ts
src/lib/abacus/index.ts

fix: fix for breaking change

---

scripts/markets/add-markets.ts
scripts/markets/validate-other-market-data.ts
src/components/ValidatorIcons.tsx
src/hooks/useStakingValidator.ts
src/views/forms/NewMarketForm/NewMarketPreviewStep.tsx
src/views/forms/StakingForms/StakeForm/StakeFormInputContents.tsx
src/views/forms/StakingForms/StakeForm/StakeFormPreviewContents.tsx
src/views/forms/StakingForms/StakeForm/ValidatorDropdown.tsx
src/views/forms/StakingForms/shared/ValidatorName.tsx

these commits got stripped out of https://github.com/dydxprotocol/v4-web/pull/814 during the rebase 😢

fix: stop deep importing [OTE-651]

---

package.json
pnpm-lock.yaml
public/configs/v1/env.json
src/constants/notifications.ts
src/constants/skip.ts
src/hooks/useAccountBalance.ts
src/hooks/useEndpointsConfig.ts
src/hooks/useEnvConfig.ts
src/hooks/useLocalNotifications.tsx
src/hooks/useNotificationTypes.tsx
src/hooks/useSubaccount.tsx
src/lib/__test__/skip.spec.ts
src/lib/abacus/dydxChainTransactions.ts
src/lib/abacus/index.ts
src/lib/skip.ts
src/views/forms/AccountManagementForms/WithdrawForm.tsx
src/views/notifications/TransferStatusNotification/TransferStatusSteps.tsx
src/views/notifications/TransferStatusNotification/index.tsx

cleans up all the squid code!
some variable renaming, package removal, env var deletion
had to regenerate the lockfile b/c it was throwing errors as is 😢

chore: cleanup squid code [OTE-813]

---

package.json
scripts/check-pnpm-version.js

https://dydx-team.slack.com/archives/C042V24U87Q/p1726844438529629
Quick script to check pnpm version so we don't keep changing the lockfile, this has happened a few times before

chore: check pnpm version [OTE-820]

---

src/views/forms/AccountManagementForms/DepositForm.tsx

https://dydx-team.slack.com/archives/C03GKH23YAZ/p1727306349116669

fix: flip source address for deposits

---

src/components/Dialog.tsx
src/components/DropdownHeaderMenu.tsx
src/layout/Footer/FooterMobile.tsx
src/layout/Header/HeaderDesktop.tsx
src/pages/trade/UnopenedIsolatedPositions.tsx
src/styles/layoutMixins.ts
src/styles/popoverMixins.ts

fix: add back backdrop filter for mobile

---

package.json
pnpm-lock.yaml
src/hooks/vaultsHooks.ts
src/lib/do.ts
src/pages/vaults/VaultDepositWithdrawForm.tsx

feat: vault errors and notifications

---

package.json
pnpm-lock.yaml

https://github.com/dydxprotocol/v4-abacus/pull/696

fix: remove stop order self trade validation

---

src/constants/analytics.ts
src/hooks/vaultsHooks.ts
src/lib/analytics/analytics.ts
src/pages/portfolio/AccountOverviewSection.tsx
src/pages/portfolio/Positions.tsx
src/pages/vaults/VaultDepositWithdrawForm.tsx
src/pages/vaults/VaultPage.tsx

Just the basics for amplitude. Errors going to datadog.

feat: vault monitoring

---

src/components/CollapsibleTabs.tsx
src/components/Separator.tsx
src/components/Tabs.tsx
src/hooks/tradingView/useTradingView.ts
src/hooks/usePrevious.ts
src/views/charts/TradingView/TvChart.tsx

ahhh tv chart crashing on screen resize qq
also console errors complaining about values on styled components not having $; there're probably more places that do this but i'm just fixing the ones i immediately see for now

fix: tv chart not ready / console errors

---

src/views/forms/AccountManagementForms/WithdrawForm.tsx

fix: fix address validation for solana-devnet

---

src/pages/trade/MobileTopPanel.tsx

https://github.com/user-attachments/assets/1ac33667-81c5-458d-8fe3-b22275316ed8

chore: update mobile web to default to price chart

---

public/configs/markets.json
public/configs/otherMarketData.json
public/configs/v1/env.json

Fix atomicResolution in `otherMarketsData.json`

fix: update trumpwin atomicResolution

---

package.json
pnpm-lock.yaml
src/components/Output.tsx
src/components/ToggleGroup.tsx
src/lib/do.ts
src/pages/portfolio/AccountOverviewSection.tsx
src/pages/portfolio/History.tsx
src/pages/portfolio/PortfolioNavMobile.tsx
src/pages/vaults/VaultDepositWithdrawForm.tsx
src/pages/vaults/VaultInfoSections.tsx
src/pages/vaults/VaultLockedSharesTable.tsx
src/pages/vaults/VaultPnlChart.tsx
src/pages/vaults/VaultPositionsTable.tsx
src/views/ExportHistoryDropdown.tsx

This is like 10 linear tickets so I won't link them all.

fix: misc small vault fixes

---

src/hooks/useNotificationTypes.tsx

Display TRUMPWIN-USD notification.
---
- `hooks/useNotificationTypes`
- Update expiration date
---

feat(trumpwin-notif): update expiration date for trumpwin-usd notification

---

package.json
pnpm-lock.yaml
src/constants/statsig.ts
src/hooks/useDydxClient.tsx
src/lib/abacus/dydxChainTransactions.ts

using the statsig flag as killswitch; testing looks good to me tho

chore: use timestamp nonce in validator config

---

src/pages/portfolio/Portfolio.tsx
src/pages/vaults/VaultTransactions.tsx

just added a column, logic copied from the transfers table

feat: vault transactions link to mintscan

---

src/hooks/tradingView/useTradingViewDatafeed.ts
src/views/charts/TradingView/TvChart.tsx

testing:
- go to trading (a market that's not ticksize decimals = 2), check price scale
- navigate to a different market with different tick size, check price scale
- repeat

fix: price scale didn't change with market/actual tick size decimals

---

src/components/ToggleGroup.tsx

https://github.com/user-attachments/assets/b6f8015f-80ef-4a40-8a84-fa4df7f53ee5

fix: toggle group bandaid?

---

public/configs/v1/env.json
src/App.tsx
src/constants/abacus.ts
src/constants/graz.ts
src/constants/notifications.ts
src/constants/transfers.ts
src/hooks/transfers/skipClient.tsx
src/hooks/transfers/useTransfers.tsx
src/hooks/useAccounts.tsx
src/hooks/useSubaccount.tsx

Some refactors, cleanup, and config set up to enable withdrawals via v4-web only onboarding
the meat of this PR is adding prefetching for chains and assets in the App.tsx level as we prepare to actually start using the skipClient

feat: cctp withdrawals: setup [1/n]

---

package.json
pnpm-lock.yaml
src/constants/solana.ts
src/hooks/transfers/skipClient.tsx
src/lib/__test__/fixtures/skipCctpDeposit.ts
src/lib/__test__/fixtures/skipCctpWithdrawal.ts
src/lib/__test__/fixtures/skipNonCctpDeposit.ts
src/lib/__test__/fixtures/skipNonCctpWithdrawal.ts
src/lib/skip.ts
src/lib/wagmi.ts

For some reason it's fine now! so weird! 👯

feat: add skip client in again

---

src/hooks/tradingView/useBuySellMarks.ts

Clear marks if the toggle is off OR if the account is disconnected

fix: clear marks when account is disconnected

---

src/constants/analytics.ts
src/hooks/useAnalytics.ts

this PR adds analytics for tracking whether or not the user has selected 'remember me' during the onboarding flow

feat: add analytics for remember me option

---

scripts/markets/help.ts
scripts/markets/validate-other-market-data.ts

Update new market validation.
---

chore(new-market-validation): validate atomic resolution

---

package.json
pnpm-lock.yaml
src/lib/testFlags.ts
src/pages/vaults/VaultInfoSections.tsx
src/pages/vaults/VaultPnlChart.tsx
src/pages/vaults/VaultPositionsTable.tsx

- positions -> holdings
- divide by equity no matter what
- remove some columns on mobile in the positions table

fix: tiny vault changes 4

---

src/lib/typeUtils.ts
src/views/forms/TransferForm.tsx
src/views/forms/TransferForm/TransferButtonAndReceipt.tsx

removing optional chaining did us an oopsie here!

fix: correct optional chaining for transfer form

---

package.json
pnpm-lock.yaml
src/constants/funkit.tsx
src/icons/logo-short.tsx

- Bump `funkit/connect` version to `v3.4.5`
- Fixed logo height
- Fixed dydx address 
---
- New: `<ViewComponentName>`
- 
-
- `<ViewComponentName>`
- 
- New: ``
- Rename: `→`
-
- New: `<ComponentName>`
- 
-
- `<ComponentName>`
- 
- New: ``
- Rename: `→`
-
- `styles/_____`
- 
- New: ``
- Rename: `→`
-
- `constants/_____`
- 
-
- `lib/_____`
- 
-
- `hooks/_____`
- 
-
- `state/_____`
- 
-
- `package-name`
- 
- updated: v** -> v**
- `workflow-name.yml`
- 
-
---

chore(funkit): bump funkit version

---

.nvmrc
package.json

this probably warrants a good amount of testing.
https://dydx-team.slack.com/archives/C03UV6K4KFY/p1729626302569169

chore: bump node v

---

README.md
template.html

This PR makes it easy to parametrize instructions for internet crawlers depending on the deployment environment.

feat(seo): Parametrize HTML meta tag "robots"

---

src/pages/portfolio/AccountOverviewSection.tsx

fix: remove vault cta

---

src/views/charts/FundingChart/Tooltip.tsx

I may have been the one to break this tbh

fix: funding rate tooltips

---

src/constants/notifications.ts
src/hooks/useComplianceState.tsx
src/hooks/useNotificationTypes.tsx

Remove expired notifications and unnecessary notifications on initialization.
---
- `constants/notifications`
- body should always be a string. Push Notification API does not know what to do when given a ReactNode.
- `hooks/useNotificationTypes`
- DELETE ITEMS
- move complianceMessage from `body` -> `slotDescription`
---

chore(notifications): remove old notifications

---

package.json
pnpm-lock.yaml
public/configs/v1/env.json
src/hooks/useURLConfigs.ts
src/layout/Header/HeaderDesktop.tsx
src/pages/markets/MarketsBanners.tsx
src/views/dialogs/LaunchMarketDialog.tsx
src/views/forms/NewMarketForm/v7/NewMarketSelectionStep.tsx

https://linear.app/dydx/issue/TRA-845/show-number-of-listed-and-listable-markets-on-the-markets-page
https://linear.app/dydx/issue/TRA-843/change-launch-page-message
https://linear.app/dydx/issue/TRA-842/remove-launch-market-button-on-trade-page-header
https://linear.app/dydx/issue/TRA-851/add-help-doc-link-to-the-launch-page-message
---
- `<MarketsBanner>`
- add count of Launchable and Active markets to PML Banner
- `<HeaderDesktop>`
- remove Launch Market button
- `<LaunchMarketDialog>`, `<NewMarketPreviewStep>`
- Update description copy 
- `env.json`, `useUrlConfigs`
- add `launchMarketLearnMore` 
- `v4-localization`
- updated: v1.1.238 -> v1.1.239
---

chore(pml-misc): Various PML touch up items

---

src/components/Tabs.tsx
src/pages/trade/MobileTopPanel.tsx

https://linear.app/dydx/issue/CT-1270/make-chart-on-market-page-larger-40-50percent-of-page-size
https://dydx-team.slack.com/archives/C03GKH23YAZ/p1730760904947139?thread_ts=1729617964.032689&cid=C03GKH23YAZ

fix: mobile top bar jiggling bug and make it bigger

---

src/icons/mobile.svg
src/views/MobileDownloadLinks.tsx

https://linear.app/dydx/issue/CT-1256/[fast-follow]-update-mobile-dropdown-in-page-header

fix: update mobile dropdown to match ui refresh designs

---

src/hooks/tradingView/useChartMarketAndResolution.ts

- previously, the second useEffect that handled changing resolutions wouldn't run consistently because changes in the `chartResolution` variable above wouldn't trigger a rerender
- this PR instead (1) handles the initial render and (2) adds a subscription callback to handle resolution changes

fix: chart resolution logic should also follow react state rules

---

src/hooks/useReferralAddress.ts
src/views/dialogs/ReferralDialog.tsx

| Before | After | Light mode |
|-------|-------|------------|
|<img width="540" alt="image" src="https://github.com/user-attachments/assets/95006b7e-877f-447a-9c8a-83dda7a0fad9">|<img width="536" alt="image" src="https://github.com/user-attachments/assets/32d704be-8ce0-48b2-9dfd-44926a2e0019">|<img width="571" alt="image" src="https://github.com/user-attachments/assets/4bcdabf2-3c4f-4061-97bf-dc55edb5abc5">|

feat(affiliates): referral dialog polishes

---

package.json
pnpm-lock.yaml
src/pages/Profile.tsx
src/pages/portfolio/Orders.tsx
src/pages/portfolio/Overview.tsx
src/pages/portfolio/Portfolio.tsx
src/pages/portfolio/Positions.tsx

https://linear.app/dydx/issue/CT-1308/[fast-follow]-update-tables-on-other-pages-ie-portfolio-to-also-be

fix: sync up table rendering across the app

---

src/views/forms/NewMarketForm/v7/NewMarketPreviewStep.tsx

Clear tx error on ticker change
---
- `<NewMarketPreviewStep>`
- add side effect to clear local tx error state on ticker change
---

fix(PML): Clear error on ticker change

---

src/state/_store.ts

devtools good, tradingview state BIG, bad

chore: kill the tradingview state in devtools

---

public/configs/v1/env.json

fix: get rid of failing testnet validators for now

---

src/hooks/useAffiliatesInfo.ts
src/lib/safeFetch.ts

Note: they are all still untyped garbage for some reason

fix: affiliates fetches

---

src/state/_store.ts

chore: slim redux devtools again

---

package.json
pnpm-lock.yaml
src/pages/markets/Markets.tsx
src/pages/markets/MarketsBanners.tsx
src/state/dismissable.ts
src/state/dismissableSelectors.ts
src/views/Affiliates/CriteriaDialog.tsx
src/views/Affiliates/cards/AffiliateStatsCard.tsx
src/views/Affiliates/cards/ProgramStatusCard.tsx
src/views/AffiliatesBanner.tsx

- Make Affiliate/Pml banners consistent
- Make banners dismissable
- VIP -> Vip Affiliate

chore(banners): Make banners consistent, VIP Affiliate

---

src/App.tsx
src/constants/routes.ts
src/pages/affiliates/AffiliatesPage.tsx
src/views/AffiliatesBanner.tsx
src/views/dialogs/ReferralDialog.tsx

Update App routes and remove Program Stats.
Update Referral Dialog value prop ordering.
---
- `<AffiliatesPage>`
- remove program stats. Treat Leaderboard as the only Referral route.
- `<AffiliatesBanner>`
- bold `Invite friends` 
- `<App>`
- Remove unused routes
- `<ReferralDialog>`
- Update order of value props
- Display refCode (username) instead of truncated address. 
- `constants/routes`
- Remove unused routes
---

chore(affiliate): update routes and dialog

---

src/constants/dialogs.ts
src/hooks/useAffiliatesInfo.ts
src/pages/affiliates/AffiliatesPage.tsx
src/views/Affiliates/CriteriaDialog.tsx
src/views/Affiliates/cards/AffiliateStatsCard.tsx
src/views/dialogs/ShareAffiliateDialog.tsx

- fixes the parsing of the staked dydx amount in the criteria dialog
- dont show your QR code if you dont have a referral code (eg youre not eligible yet) in the share affiliates dialog

feat: more affiliates fixes

---

package.json
pnpm-lock.yaml
src/components/DropdownMenu.tsx
src/components/Tag.tsx
src/pages/token/LaunchIncentivesPanel.tsx

Update copy for IncentivesPanel on the Rewards page.
---
- `<LaunchIncentivesPanel>`
- Update copy
- Add tooltip to shed light on point distribution
- New: `<SuccessTag>`
- Tag component with `var(--color-success)`
- `v4-localization`
- updated: v1.1.248 -> v1.1.250
---

chore(incentives): Update incentives copy

---

src/constants/statsig.ts
src/hooks/tradingView/useChartLines.tsx
src/hooks/tradingView/useTradingViewLimitOrder.ts

remove feature flags to always turn feature on

chore: clean up statsig flags for order modification

---

src/hooks/useAccounts.tsx
src/hooks/useAffiliatesInfo.ts
src/hooks/useReferralCode.ts
src/hooks/useReferredBy.ts
src/views/dialogs/ReferralDialog.tsx

Skip dialog view if the user already has an affiliate registered on-chain

fix: dont show referral dialog if user already has affiliate address registered

---

package.json
pnpm-lock.yaml

Add delay to Isolated Margin order placement so that the order always occurs .25 seconds after the transfer.
---
- `v4-abacus`
- updated: v1.13.32 -> v1.13.34
- [Adds delay to placing an order](https://github.com/dydxprotocol/v4-abacus/pull/759)
- [Trading rewards learn more data](https://github.com/dydxprotocol/v4-abacus/pull/758)
---

fix: Isolated Order race condition

---

src/constants/markets.ts
src/hooks/useMarketsData.ts
src/views/tables/MarketsTable.tsx

- add dydx (and other dexes) to defi tag
- ensure that favorites when no favorites displays something sane (instead of loading spinner forever)

fix: markets table fixes

---

src/components/Dialog.tsx
src/views/dialogs/UnlimitedAnnouncementDialog/UnlimitedAnnouncementDialog.tsx

fix: unlmiited dialog close

---

src/views/forms/TradeForm/TradeFormInputs.tsx

It is annoying and why would you want a limit order at mid market?

fix: stop setting limit price for the user

---

package.json
pnpm-lock.yaml

Fixed validation logic for Isolated Orders, disregard whether account is below minimum equity tier limit after an order that would reduce the position.
---
- `v4-abacus`
- updated: v1.13.34 -> v1.13.35
---

fix: unable to close position with limit order

---

src/lib/abacus/stateNotification.ts

much requested, though Jared may veto this

fix: throttle orderbook updates

---

package.json
pnpm-lock.yaml
src/components/Table.tsx
src/constants/tooltips/affiliates.ts
src/views/Affiliates/CriteriaDialog.tsx

there already was a tooltip but it wasn't showing because of the `pointer-events: none` property 🙃 
but also updated the text!

feat: tooltip for affiliate commissions

---

src/components/ComboboxMenu.tsx
src/constants/menus.ts
src/constants/notifications.ts
src/hooks/useNotificationTypes.tsx
src/views/menus/NotificationsMenu.tsx

Make search for ticker work in notifications at least. Not perfect but better.

fix: searchable notifications

---

src/views/Affiliates/cards/ProgramStatusCard.tsx

feat: add learn more link in VIP affiliates section

---

package.json
pnpm-lock.yaml
src/components/ComboboxDialogMenu.tsx
src/constants/funkit.tsx
src/hooks/useFunkitBuyNobleUsdc.ts
src/views/menus/NotificationsMenu.tsx

Followup changes as requested by dYdX team
1. Bump `@funkit/connect` to `v4.0.2` (major release, some breaking changes to themeing)
3. SDK: Disable Card as a checkout option
5. SDK: Show market maker gas fees in collapsed preview
6. SDK: LP cost now in dollar form
7. SDK: Show dollar value in source token amount
8. SDK: Copy changes in checkout confirmation page
9. SDK: Copy changes on checkout history page 
10. App: Revert hover button color 
11. App: Fix notification drawer overlay issue
**Card disabled, notification drawer overlay bug**
https://drive.google.com/file/d/1hy5xTLVhkr3kSeFoPGA5PcFqkcGg73Gq/view?usp=sharing
**Fees preview**
https://drive.google.com/file/d/1qctbnjjcWdOXwdcuWXMgv7DB_8kaTjK7/view?usp=sharing

feat(funkit): funkit integration finetune (4.0.2)

---

public/configs/v1/env.json
src/constants/localization.ts

Move locale restriction to env.json instead of env var

chore: restrict locales from config env instead of env var

---

public/configs/v1/env.json

Needed for the WalletConnect upgrade to the iOS app

chore: Add appGroup to mobile app config

---

src/hooks/useAffiliatesLeaderboard.ts

because they are SNEAKY and did not make their affiliate link through the FE!

feat: dont show affiliates that have no referral code

---

src/constants/dialogs.ts
src/layout/DialogManager.tsx
src/layout/Header/HeaderDesktop.tsx
src/lib/testFlags.ts
src/views/dialogs/DepositDialog2/DepositDialog2.tsx

new modal under test flag `deposit_rewrite`

feat: add placeholder for new deposit flow

---

src/components/Dialog.tsx
src/constants/tokens.ts
src/views/dialogs/DepositDialog2/AmountInput.tsx
src/views/dialogs/DepositDialog2/DepositDialog2.tsx
src/views/dialogs/DepositDialog2/DepositForm.tsx
src/views/dialogs/DepositDialog2/TokenSelect.tsx

This PR creates the token amount input box for the new deposit flow.
Design reference [here](https://www.figma.com/design/fMQodZKzn9B5aZTN5G0fLJ/dYdX-%E2%80%BA-Desktop?node-id=36627-11787&node-type=canvas&t=gT6n2z2KcejahxMp-0)
https://github.com/user-attachments/assets/81f48662-aea8-4ec9-9541-6d98c3c381ad

feat: Add token amount input box

---

src/components/Dialog.tsx
src/constants/chains.ts
src/constants/solana.ts
src/constants/tokens.ts
src/state/wallet.ts
src/views/dialogs/DepositDialog2/AmountInput.tsx
src/views/dialogs/DepositDialog2/DepositDialog2.tsx
src/views/dialogs/DepositDialog2/DepositForm.tsx
src/views/dialogs/DepositDialog2/TokenSelect.tsx
src/views/dialogs/DepositDialog2/queries.ts
src/views/dialogs/DepositDialog2/types.ts
src/views/dialogs/DepositDialog2/utils.ts

This PR introduces the token select list for the new deposit flow:
https://github.com/user-attachments/assets/6d69ee02-59f2-409b-890f-60b2b61437b2

feat(deposit2): token selector

---

package.json
pnpm-lock.yaml
src/views/forms/AccountManagementForms/DepositForm/FunKitToggle.tsx
src/views/notifications/FunkitDepositNotification.tsx

1. **Chore:** Bump `@funkit/connect` to `v4.0.3`. Full version changelog in [CHANGELOG.md](https://www.npmjs.com/package/@funkit/connect?activeTab=code)
2. **Feat:** Limit copy in `FunkitToggle` dynamically updates with Funkit widget's toggle via `useFunkitMaxCheckoutUsd()`
3. **Fix:** Mobile height issues on Funkit widget

chore(funkit): bump funkit version 4.0.3

---

src/views/MarketStatsDetails.tsx

feat: annualized funding in tooltip

---

src/abacus-ts/rawTypes.ts
src/abacus-ts/rest/assets.ts
src/constants/assetMetadata.ts

---
- Include `priceData` within `type AssetInfo`
- Combine info/prices into same queryfn
---

chore: store metadata prices in rawAssets

---

src/abacus-ts/calculators/assets.ts
src/abacus-ts/rawTypes.ts
src/abacus-ts/rest/assets.ts

Have priceData on the same level as assetInfo
---

fix: raw asset structure

---

src/abacus-ts/rest/lib/compositeClientManager.ts
src/abacus-ts/rest/lib/indexerQueryStoreEffect.ts
src/abacus-ts/rest/lib/useIndexer.ts

fix(bonsai-core): don't import store directly and kick off lots of accidental side effects

---

src/abacus-ts/ontology.ts
src/abacus-ts/rest/funding.ts
src/abacus-ts/rest/lib/compositeClientManager.ts
src/abacus-ts/websocket/orderbook.ts
src/abacus-ts/websocket/trades.ts
src/state/_store.ts
src/state/perpetualsSelectors.ts

- Add query for historical funding and export from ontology
- Add selector for currentMarketIdIfTradeable and update usage in orderbook/trades

feat(bonsai-core): funding query

---

src/constants/dialogs.ts
src/layout/DialogManager.tsx
src/lib/testFlags.ts
src/pages/portfolio/Portfolio.tsx
src/views/AccountInfo/AccountInfoSection.tsx
src/views/dialogs/OnboardingDialog.tsx
src/views/dialogs/WithdrawDialog2/AddressInput.tsx
src/views/dialogs/WithdrawDialog2/AmountInput.tsx
src/views/dialogs/WithdrawDialog2/ChainSelect.tsx
src/views/dialogs/WithdrawDialog2/WithdrawDialog2.tsx
src/views/dialogs/WithdrawDialog2/WithdrawForm.tsx
src/views/forms/StakingForms/shared/StakeRewardButtonAndReceipt.tsx
src/views/forms/TradeForm/PlaceOrderButtonAndReceipt.tsx
src/views/menus/AccountMenu.tsx
src/views/tables/TransferHistoryTable.tsx

Update testFlag usage for rewrites. Add views for WithdrawDialog2
---
- New: `<WithdrawDialog2>`
- New WithdrawDialog & Form
- 0 functionality, views only
---

feat(withdraw-dialog): withdraw dialog rewrite 1/n

---

src/constants/candles.ts
src/hooks/useDydxClient.tsx
src/lib/abacus/websocket.ts
src/lib/tradingView/dydxfeed/__test__/utils.spec.ts
src/lib/tradingView/dydxfeed/cache.ts
src/lib/tradingView/dydxfeed/index.ts
src/lib/tradingView/dydxfeed/streaming.ts
src/lib/tradingView/utils.ts
src/state/perpetuals.ts
src/state/perpetualsSelectors.ts

- give up caching, let trading view do it (it does do it)
- fix 1m time interval to correctly be 1 minute
- don't make multiple requests when we already have all the data
- correctly set volume on new candles
- stop unsubscribing every time someone tries to subscribe and breaking everything

fix: basic candle processing fixes

---

src/abacus-ts/websocket/parentSubaccount.ts
src/types/indexer/indexerManual.ts

access and save using symbol as key instead of assetId

fix(bonsai-core): asset position update

---

.eslintrc.json
src/abacus-ts/calculators/subaccount.ts
src/abacus-ts/types/summaryTypes.ts

fix import rule and change unopened isolated position struct

fix(bonsai-core): unopened isolated position struct change

---

src/abacus-ts/websocket/lib/indexerValueManagerHelpers.ts
src/abacus-ts/websocket/lib/indexerWebsocket.ts
src/abacus-ts/websocket/lib/reconnectingWebsocket.ts
src/abacus-ts/websocket/lib/websocketDerivedValue.ts

Everything is slightly simpler + one more retry

fix(bonsai-core): indexer websocket cleanup and refactor, handle another error type

---

src/abacus-ts/websocket/lib/reconnectingWebsocket.ts

Only count connections that last 5s as backoff resets.

fix(bonsai-core): exponentially backoff even when initial connection is successful

---

src/abacus-ts/calculators/markets.ts
src/abacus-ts/ontology.ts
src/abacus-ts/rest/sparklines.ts
src/abacus-ts/selectors/base.ts
src/abacus-ts/selectors/markets.ts
src/abacus-ts/storeLifecycles.ts
src/state/raw.ts
src/types/indexer/indexerChecks.ts
src/types/indexer/indexerManual.ts

add fetch rest request to storeLifecycle

feat(bonsai-core): sparkline rest

---

src/abacus-ts/calculators/fills.ts
src/abacus-ts/types/summaryTypes.ts
src/lib/orders.ts
src/views/tables/FillsTable.tsx
src/views/tables/enumToStringKeyHelpers.ts

I missed this tiny line in the fill processor in abacus

fix: fill type calculation

---

src/pages/trade/UnopenedIsolatedPositions.tsx

fix: don't popup unopened isolated panel, add a number

---

src/abacus-ts/calculators/accountActions.ts
src/abacus-ts/calculators/funding.ts
src/abacus-ts/calculators/markets.ts
src/abacus-ts/lib/loadable.ts
src/abacus-ts/ontology.ts
src/abacus-ts/rest/funding.ts
src/abacus-ts/selectors/accountActions.ts
src/abacus-ts/selectors/summary.ts
src/views/charts/FundingChart/index.tsx

... so consumers can easily understand output types without looking at implementations

feat(bonsai): add types for all ontology exports

---

src/bonsai/calculators/markets.ts
src/bonsai/websocket/trades.ts

fix: no next gen array functions yet

---

src/components/QrCode.tsx
src/views/dialogs/DepositDialog2/DepositDialog2.tsx
src/views/dialogs/DepositDialog2/TokenSelect.tsx

This PR fixes an issue where tabbing through the Deposit Form while the token select was not visible would cause it to shift right to an empty screen.
It also fixes an issue with the Coinbase QR code shrinking if you click the "copy" icon by wrapping the QrCode component in a React.memo.

fix: deposit form tab indexing and coinbase qr code issue

---

package.json
pnpm-lock.yaml
src/components/AssetIcon.tsx
src/components/Dialog.tsx
src/constants/notifications.ts
src/hooks/transfers/skipClient.tsx
src/hooks/useNotificationTypes.tsx
src/hooks/useSubaccount.tsx
src/hooks/useUpdateTransfers.tsx
src/state/transfers.ts
src/state/transfersSelectors.ts
src/views/dialogs/DepositDialog2/AmountInput.tsx
src/views/dialogs/DepositDialog2/DepositDialog2.tsx
src/views/dialogs/DepositDialog2/DepositStatus.tsx
src/views/dialogs/DepositDialog2/TokenSelect.tsx
src/views/dialogs/DepositDialog2/utils.ts

This PR adds deposit notifications~
TODO: add explorer links whenever relevant
https://github.com/user-attachments/assets/dc6db5de-f269-41b8-802d-f19c8d67a45e

feat: add deposit notifications

---

src/hooks/transfers/skipClient.tsx
src/views/dialogs/DepositDialog2/AmountInput.tsx
src/views/dialogs/DepositDialog2/DepositDialog2.tsx
src/views/dialogs/DepositDialog2/DepositForm.tsx
src/views/dialogs/DepositDialog2/RouteOptions.tsx
src/views/dialogs/DepositDialog2/utils.ts

This PR adds support for Keplr and Solana USDC deposits. For Keplr, we support Noble, Osmosis, and Neutron deposits. I also updated the logic to get the correct signer based on the source account.

feat: solana + keplr + privy deposit flow support

---

src/hooks/useNotificationTypes.tsx
src/hooks/useUpdateTransfers.tsx
src/state/transfers.ts
src/views/dialogs/DepositDialog2/DepositForm.tsx
src/views/dialogs/DepositDialog2/DepositStatus.tsx

feat: use finalized deposit amounts

---

src/views/dialogs/DepositDialog2/DepositForm.tsx

Sometimes the external wallet can get disconnected so manually reconnect if that happens

feat: deposit reconnect wallet flow

---

src/hooks/useCurrentMarketId.ts
src/lib/abacus/stateNotification.ts
src/state/perpetuals.ts

fix: abacus current market id setting

---

src/hooks/useNotificationTypes.tsx
src/hooks/useUpdateTransfers.tsx
src/state/transfers.ts
src/state/transfersSelectors.ts
src/views/dialogs/DepositDialog2/RouteOptions.tsx
src/views/dialogs/DepositDialog2/utils.ts
src/views/dialogs/WithdrawDialog2/WithdrawDialog2.tsx
src/views/dialogs/WithdrawDialog2/WithdrawForm.tsx
src/views/dialogs/WithdrawDialog2/WithdrawStatus.tsx
src/views/dialogs/WithdrawDialog2/queries.ts
src/views/dialogs/WithdrawDialog2/utils.ts

- generalizes the useNotificationTypes hook
- updates transfers state and selectors
- adds status page
- update route options component and display estimated duration

feat: add transfer notification and status page

---

package.json
pnpm-lock.yaml
src/constants/funkit.tsx

Bump `@funkit/connect` from `v4.1.7` -> `v5.0.1`. See [CHANGELOG.md](https://www.npmjs.com/package/@funkit/connect?activeTab=code) for version changes.

chore(funkit): bump funkit version 5.0.1

---

package.json
pnpm-lock.yaml
src/constants/statsig.ts
src/hooks/useNotificationTypes.tsx
src/layout/Header/HeaderDesktop.tsx
src/pages/portfolio/Portfolio.tsx
src/views/AccountInfo/AccountInfoSection.tsx
src/views/dialogs/CoinbaseDepositDialog.tsx
src/views/dialogs/TransferDialogs/DepositDialog2/AmountInput.tsx
src/views/dialogs/TransferDialogs/DepositDialog2/DepositForm.tsx
src/views/dialogs/TransferDialogs/DepositDialog2/DepositStatus.tsx
src/views/dialogs/TransferDialogs/DepositDialog2/DepositSteps.tsx
src/views/dialogs/TransferDialogs/DepositDialog2/depositHooks.ts
src/views/dialogs/TransferDialogs/RouteOptions.tsx
src/views/dialogs/TransferDialogs/WithdrawDialog2/WithdrawForm.tsx
src/views/dialogs/TransferDialogs/WithdrawDialog2/WithdrawStatus.tsx
src/views/dialogs/TransferDialogs/WithdrawDialog2/withdrawHooks.ts
src/views/dialogs/TransferDialogs/utils.ts
src/views/menus/AccountMenu.tsx

Use statsig flag for withdraw rewrite

feat: statsig flags for withdraw

---

src/components/Table.tsx
src/components/Table/TablePaginationRow.tsx
src/hooks/useTablePagination.ts
src/pages/portfolio/EquityTiers.tsx
src/pages/portfolio/Fees.tsx
src/pages/vaults/VaultLockedSharesTable.tsx
src/pages/vaults/VaultPositionsTable.tsx
src/pages/vaults/VaultTransactions.tsx
src/state/appUiConfigs.ts
src/state/appUiConfigsSelectors.ts
src/views/Affiliates/AffiliatesLeaderboard.tsx
src/views/Affiliates/CriteriaDialog.tsx
src/views/MarketsDropdown.tsx
src/views/forms/StakingForms/StakeForm/ValidatorDropdown.tsx
src/views/tables/FillsTable.tsx
src/views/tables/LiveTrades.tsx
src/views/tables/MarketsCompactTable.tsx
src/views/tables/MarketsTable.tsx
src/views/tables/OrdersTable.tsx
src/views/tables/PositionsTable.tsx
src/views/tables/TradingRewardHistoryTable.tsx
src/views/tables/TransferHistoryTable.tsx

This is my Valentine's day present for Lawrence

feat: save table page size in local storage

---

src/components/DiffOutput.tsx
src/constants/dialogs.ts
src/constants/numbers.ts
src/views/dialogs/CoinbaseDepositDialog.tsx
src/views/dialogs/TransferDialogs/DepositDialog2/AmountInput.tsx
src/views/dialogs/TransferDialogs/DepositDialog2/DepositForm.tsx
src/views/dialogs/TransferDialogs/DepositDialog2/OtherDepositOptions.tsx

https://linear.app/dydx/issue/BUG2-273/add-back-button-to-coinbase-deposit-modal
https://linear.app/dydx/issue/BUG2-269/minimum-deposit-values-malfunctioning
- Add back button on Coinbase Deposit Modal
- Move other deposit options below Deposit Funds CTA
- Add estimated received amount to receipt
- fix min deposit validation
- hide coinbase button when starting normal deposit flow

feat: ux changes for deposits

---

src/components/AssetIcon.tsx
src/components/Notification.tsx
src/components/PortfolioCard.tsx
src/components/Table/MarketTableCell.tsx
src/hooks/useNotificationTypes.tsx
src/pages/token/StakingPanel.tsx
src/pages/token/StakingRewardPanel.tsx
src/pages/trade/TradeHeaderMobile.tsx
src/pages/vaults/VaultDepositWithdrawForm.tsx
src/views/MarketDetails/MarketDetails.tsx
src/views/PositionTile.tsx
src/views/dialogs/DetailsDialog/FillDetailsDialog.tsx
src/views/dialogs/DetailsDialog/OrderDetailsDialog.tsx
src/views/dialogs/StakingRewardDialog.tsx
src/views/dialogs/TransferDialogs/DepositDialog2/AmountInput.tsx
src/views/dialogs/TransferDialogs/DepositDialog2/TokenSelect.tsx
src/views/dialogs/TransferDialogs/WithdrawDialog2/AddressInput.tsx
src/views/dialogs/TransferDialogs/WithdrawDialog2/ChainSelect.tsx
src/views/forms/NewMarketForm/v7/NewMarketPreviewStep.tsx
src/views/forms/StakingForms/StakeForm/StakeFormPreviewContents.tsx
src/views/forms/StakingForms/UnstakeForm/UnstakeFormPreviewContents.tsx
src/views/forms/TransferForm.tsx
src/views/menus/AccountMenu.tsx
src/views/tables/FillsTable.tsx
src/views/tables/PositionsTable.tsx

- Add container component to <AssetIcon>
- Refactor h/w changes to css var --asset-icon-size
- Removes white border on icons by moving the bg-color to $Container and scaling image by 1.05

style: remove white border from AssetIcon

---

package.json
pnpm-lock.yaml
src/views/dialogs/HelpDialog.tsx

fix: help text

---

src/bonsai/calculators/transfers.ts
src/bonsai/selectors/account.ts

- remove vault transfers from transfers page and stored transfers
- fix type names for transfers out

fix: transfers

---

src/bonsai/calculators/apiState.ts
src/bonsai/lib/loadable.ts
src/bonsai/rest/height.ts
src/bonsai/rest/lib/indexerQueryStoreEffect.ts
src/bonsai/types/summaryTypes.ts
src/hooks/useApiState.ts
src/hooks/useWithdrawalInfo.ts
src/lib/asyncUtils.ts
src/state/raw.ts

also, now we ignore the state when we haven't made requests recently.

fix: rewrite api state for stability

---

src/bonsai/calculators/apiState.ts
src/bonsai/rest/height.ts

give up on offline and background polling

fix: rewrite api state again

---

package.json
pnpm-lock.yaml
src/constants/notifications.ts
src/hooks/useNotificationTypes.tsx

chore(upgrade-notif): add link to proposal for upgrading certain markets

---

package.json
pnpm-lock.yaml
src/views/dialogs/TransferDialogs/DepositDialog2/DepositForm.tsx
src/views/dialogs/TransferDialogs/DepositDialog2/DepositStatus.tsx
src/views/dialogs/TransferDialogs/RouteOptions.tsx
src/views/dialogs/TransferDialogs/WithdrawDialog2/WithdrawStatus.tsx

- Add ViewTxn string and remove tag styling
- Add call out for gas fees when user selects the slow route for Deposits

chore: view txns, and add gas fee callout

---

src/constants/notifications.ts
src/hooks/useNotificationTypes.tsx

chore: remove expired notifs

---

src/bonsai/calculators/orders.ts
src/bonsai/forms/triggers/errors.ts
src/bonsai/forms/triggers/summary.ts
src/bonsai/forms/triggers/triggers.ts
src/bonsai/forms/triggers/types.ts
src/bonsai/types/summaryTypes.ts
src/hooks/tradingView/useChartLines.tsx
src/hooks/useSubaccount.tsx
src/hooks/useTriggerOrdersFormInputs.ts
src/lib/orderModification.ts
src/state/inputsSelectors.ts
src/views/forms/TriggersForm/TriggerOrderInputs.tsx

- correctly remove orders from trading view when they disappear from orders state
- show trigger size when modifying an order that has size
- fix trigger price 0% change
- correctly allow removing an existing trigger order by clicking "clear"
- fix changing orders on trading view

fix: misc triggers fixes

---

src/bonsai/rest/lib/compositeClientManager.ts
src/hooks/useDydxClient.tsx
src/lib/abacus/dydxChainTransactions.ts

fix: enable timestamp nonce everywhere

---

src/views/TradeBoxOrderView.tsx
src/views/forms/TradeForm/useTradeTypeOptions.tsx
src/views/tables/PositionsTable/PositionsTriggersCell.tsx

fix: show tp/sl name in tab

---

src/bonsai/lifecycles/nobleBalanceSweepLifecycle.ts
src/bonsai/lifecycles/usdcRebalanceLifecycle.ts

- Add sleep after tx's are sent to give them the opportunity to complete before semaphore runs nextFn
- beef up logs
- search for subaccount to withdraw usdc for gas

fix: beef up logs and fix lifecycle bug

---

src/bonsai/lifecycles/nobleBalanceSweepLifecycle.ts
src/bonsai/lifecycles/usdcRebalanceLifecycle.ts

- invalidate balances post transaction

fix: invalidate queries

---

src/bonsai/lifecycles/nobleBalanceSweepLifecycle.ts
src/bonsai/lifecycles/usdcRebalanceLifecycle.ts

When errors happened, these were running over and over

fix: always sleep in rebalance lifecycles

---

src/views/forms/TradeForm.tsx

This is the parsed error but that should be okay.

fix: datadog log on place order failure

---

package.json
pnpm-lock.yaml
src/constants/tooltips/vault.ts
src/pages/vaults/VaultInfoSections.tsx

fix: vault tooltip->90d

---

src/bonsai/rest/nobleBalance.ts
src/views/dialogs/TransferDialogs/WithdrawDialog2/AddressInput.tsx
src/views/dialogs/TransferDialogs/WithdrawDialog2/WithdrawDialog2.tsx

- Fix sweep by adding refetch/stale time
- remove address population side-effect

fix: add refetch time to noble balance query

---

src/views/ExportHistoryDropdown.tsx

Not localized anymore but that seems fine.

fix: full precision numbers for trade export

---

src/hooks/Orderbook/useDrawOrderbook.ts

fix: canvas orderbook flickers

---

src/bonsai/ontology.ts
src/lib/transformOntology.ts
src/state/_store.ts

feat: add ontology to redux devtools

---

src/hooks/useUpdateTransfers.tsx
src/views/dialogs/TransferDialogs/DepositDialog2/depositHooks.ts
src/views/dialogs/TransferDialogs/WithdrawDialog2/withdrawHooks.ts

- set gas fallback and set simulate to false
- add bonsai info logs for deposit/withdraw

fix: add logs and remove simulation

---

src/bonsai/lifecycles/reclaimChildSubaccountBalancesLifecycle.ts
src/views/charts/DepthChart/index.tsx
src/views/dialogs/UnstakeDialog.tsx
src/views/forms/StakingForms/UnstakeForm/UnstakeFormPreviewContents.tsx

I thought this would do more tbh

chore: run lint fix and prettier autofix

---

src/bonsai/calculators/accountActions.ts
src/bonsai/forms/trade/summary.ts
src/bonsai/forms/trade/tradeInfo.ts
src/views/forms/ClosePositionForm.tsx
src/views/forms/TradeForm/AmountCloseInput.tsx

*  only look at open positions, since immediately after close they are still in the data map, just as closed with size 0
* fix close position bug - round down not up so we don't show 100% when it's 99.9
* fix trade size floating point bug - gotta make sure size is never in floating point hell if at all possible

fix: misc trade fixes

---

src/bonsai/forms/trade/errors.ts
src/bonsai/forms/trade/reducer.ts
src/bonsai/forms/trade/tradeInfo.ts
src/lib/numbers.ts
src/views/forms/TradeForm.tsx

- keep size when switching side if its a text input
- show clear button when limit is populated
- fix GTT validation bug
- fix place order error text

fix: misc trade form fixes 2

---

src/bonsai/forms/trade/errors.ts

fix: isolated min order size check

---

src/bonsai/AccountTransactionSupervisor.ts
src/bonsai/lib/operationResult.ts
src/lib/errors.ts

I think I broke this in all of bonsai

fix: error handling

---

src/bonsai/forms/trade/fields.ts
src/bonsai/forms/trade/reducer.ts
src/bonsai/forms/trade/summary.ts
src/bonsai/forms/triggers/errors.ts
src/bonsai/forms/triggers/summary.ts
src/bonsai/forms/triggers/types.ts
src/bonsai/lifecycles/cancelTriggerOrdersLifecycle.ts
src/bonsai/lifecycles/reclaimChildSubaccountBalancesLifecycle.ts
src/hooks/useSubaccount.tsx

- default trade form is market
- fix bug where trigger orders cancel if orders load before parent subaccount
- fix similar potential bug with reclaiming funds
- parallelize trigger submission

fix: misc trade fixes 4

---

src/bonsai/AccountTransactionSupervisor.ts
src/bonsai/forms/trade/errors.ts
src/views/MarketsDropdown.tsx

- markets open faster
- don't enforce isolated minimum if >20 in present equity
- log time to fail

fix: misc trade fixes 5

---

src/bonsai/ontology.ts
src/hooks/transferHooks.ts
src/state/closePositionForm.ts
src/state/inputsSelectors.ts
src/state/tradeForm.ts
src/state/tradeFormSelectors.ts
src/views/forms/AdjustIsolatedMarginForm.tsx

Just because I like there being one entrypoint

chore: bonsai forms

---

src/bonsai/selectors/apiStatus.ts

fix: more conservative block estimate

---

src/bonsai/lib/subaccountUtils.ts
src/bonsai/websocket/parentSubaccount.ts

fix: enforce open perpetual positions are actually open

---

src/hooks/useNotificationTypes.tsx

maybe this was causing the liquidation bug ?

fix: fill key

---

src/main.tsx

it breaks stuff like notifs close button

fix: remove global styles from twin

---

src/bonsai/websocket/orderbook.ts
src/hooks/Orderbook/useDrawOrderbook.ts
src/state/raw.ts

fix: orderbook update speed

---

src/views/forms/ClosePositionForm.tsx

max considered dangerous from here on

fix: close position input

---

src/hooks/useNotificationTypes.tsx
src/hooks/useNotifications.tsx

Currently no link which is awkward but I think we need this out asap since it will go into effect so soon

fix: slightly more generic wind down notifications + wind down for EOS, SKITTEN, BTRUMP

---

src/bonsai/logs.ts
src/bonsai/websocket/lib/indexerWebsocket.ts

this way we aren't only logging weird things

feat: sample request time metrics

---

src/constants/statsig.ts
src/hooks/useDisplayedWallets.ts

chore: remove keplr statsig flag

---

scripts/set-last-commit-and-tag.sh

fix script to show human readable last version tag

fix: last version tag

---

src/components/BackButton.tsx
src/components/SimpleUiHeader.tsx
src/hooks/useNotificationTypes.tsx
src/pages/AlertsPage.tsx
src/pages/portfolio/SimpleUiHistory.tsx
src/pages/settings/SettingsHeader.tsx
src/views/DisplaySettings.tsx
src/views/Lists/Alerts/AlertsList.tsx

- Consolidate header styling and re-use `<BackButton>`
- Update isUnseen logic in Notifications to include triggered status

feat(simple-ui): Setttings page header

---

src/bonsai/appStartupTimer.ts
src/bonsai/websocket/markets.ts
src/bonsai/websocket/orderbook.ts
src/hooks/useCurrentMarketId.ts
src/hooks/useInitializePage.ts
src/lib/tradingView/dydxfeed/index.ts

I feel like there should be a better way to do this

feat: log startup metrics

---

src/pages/settings/Settings.tsx
src/views/DisplaySettings.tsx

fix: allow scrolling on settings page

---

src/pages/markets/simple-ui/markets-view/PositionRow.tsx

feat(simple-ui): add trending icon

---

src/pages/funding/FundingPaymentsTable.tsx

---
Filter out payment values smaller than 0.0001 and make payments show 4 decimal places.
- New: `<ViewComponentName>`
- 
-
- `<ViewComponentName>`
- 
- New: ``
- Rename: `→`
-
- New: `<ComponentName>`
- 
-
- `<ComponentName>`
- 
- New: ``
- Rename: `→`
-
- `styles/_____`
- 
- New: ``
- Rename: `→`
-
- `constants/_____`
- 
-
- `lib/_____`
- 
-
- `hooks/_____`
- 
-
- `state/_____`
- 
-
- `package-name`
- 
- updated: v** -> v**
- `workflow-name.yml`
- 
-
---

feat: Filter 0 values and make payments have 4 decimal places

---

src/bonsai/forms/trade/errors.ts

I kind of wonder if we should just remove this check since it worries me in other cases too but I guess it's fine for now.
Current issue is that if you are <0 free collateral and try to sell a position you are prevented.

fix: margin use check

---

src/hooks/useUpdateTransfers.tsx

I think this is a bug with our logs

fix: latest

---

src/views/menus/UserMenuContent.tsx

When user is not in compliant state
Full Access

feat(simple-ui): conditional rendering of onboarding buttons

---

public/configs/v1/env.json
src/hooks/transfers/skipClient.tsx

fix: use skip proxy

---

src/constants/launchableMarkets.ts
src/views/forms/NewMarketForm/index.tsx
src/views/forms/NewMarketForm/v7/NewMarketPreviewStep.tsx
src/views/forms/NewMarketForm/v7/NewMarketSelectionStep.tsx

- create lockup duration constant
- update NewMarket steps and receipts to use constant
Fixes this:

fix: update constant for lockup duration

---

src/constants/skip.ts
src/views/dialogs/TransferDialogs/DepositDialog2/DepositForm.tsx
src/views/dialogs/TransferDialogs/DepositDialog2/queries.ts

- Update min go Fast amounts for ETH L2s
-  Fix function to allow Arbitrum ETH deposit

feat: Update Skip Go Fast min transfer amounts

---

src/App.tsx
src/components/BaseButton.tsx
src/components/ComboboxDialogMenu.tsx
src/components/ComplianceBanner.tsx
src/components/Dialog.tsx
src/constants/analytics.ts
src/constants/statsig.ts
src/hooks/tradingView/useTradingView.ts
src/hooks/tradingView/useTradingViewLaunchable.ts
src/hooks/tradingView/useTradingViewTheme.ts
src/hooks/useAnalytics.ts
src/hooks/useDisplayedWallets.ts
src/hooks/useSimpleUiEnabled.ts
src/lib/testFlags.ts
src/pages/AlertsPage.tsx
src/pages/portfolio/Portfolio.tsx
src/pages/settings/Settings.tsx
src/pages/settings/SettingsHeader.tsx
src/views/charts/TradingView/TvChart.tsx
src/views/charts/TradingView/TvChartLaunchable.tsx
src/views/dialogs/OnboardingDialog.tsx
src/views/dialogs/OnboardingDialog/ChooseWallet.tsx
src/views/dialogs/OnboardingDialog/GenerateKeys.tsx
src/views/dialogs/OnboardingTriggerButton.tsx
src/views/dialogs/TransferDialogs/DepositDialog2/AmountInput.tsx
src/views/dialogs/TransferDialogs/WithdrawDialog2/AddressInput.tsx
src/views/dialogs/TriggersDialog.tsx
src/views/forms/TriggersForm/TriggerOrderInputs.tsx
src/views/forms/TriggersForm/TriggersForm.tsx

- Move testFlags from queryParams -> Custom Statsig Roll 0.5
- allow forcing flag off
- Replace all usages of testFlag.simpleUi with hook useSimpleUiEnabled
- Add appMode UserProperty

feat(simple-ui): enable 50%

---

src/pages/markets/simple-ui/markets-view/PositionRow.tsx

random things alex and I found

fix: simple row misc

---

src/App.tsx
src/components/ComplianceBanner.tsx
src/hooks/useComplianceState.tsx
src/pages/markets/simple-ui/MarketsMobile.tsx
src/pages/markets/simple-ui/portfolio-overview/UnconnectedPortfolioOverview.tsx

- bg color of container changes depending on whether user menu is open
- remove box-shadow/border on user menu (it is full screen anyways)
- add border to onboarding button when disabled.
- use flex instead of absolute positioning for compliance banner

fix: compliance-banner on simple ui

---

src/App.tsx
src/components/ComplianceBanner.tsx
src/constants/analytics.ts
src/constants/trade.ts
src/hooks/useComplianceState.tsx
src/pages/markets/simple-ui/MarketsMobile.tsx
src/pages/markets/simple-ui/portfolio-overview/UnconnectedPortfolioOverview.tsx
src/views/dialogs/SimpleUiTradeDialog/ResponsiveSizeInput.tsx
src/views/dialogs/SimpleUiTradeDialog/SimpleTradeForm.tsx

- Add Quick Limit options to Limit Order

feat: add quick limit buttons

---

src/App.tsx

- add Tos and Privacy pages to Simple UI BrowserRotuer
- Some users navigated from mobile app were redirected to markets page

fix: add terms/privacy pages to simple ui router

---

public/.well-known/apple-app-site-association

feat: Add universal link for turnkey onboarding

---

src/constants/statsig.ts
src/hooks/useSimpleUiEnabled.ts
src/views/dialogs/TransferDialogs/DepositDialog2/AmountInput.tsx
src/views/dialogs/TransferDialogs/WithdrawDialog2/AddressInput.tsx

feat(simple-ui): full release

---

src/hooks/useAccounts.tsx

this was making it impossible to connect a new wallet, not sure when this broke

fix: error status parsing

---

src/pages/markets/simple-ui/portfolio-overview/ConnectedPortfolioOverview.tsx

fix: add simple ui deposit cta on portfolio page

---

package.json
pnpm-lock.yaml
src/hooks/useWithdrawalInfo.ts
src/views/dialogs/TransferDialogs/WithdrawDialog2/WithdrawForm.tsx

fix: add withdrawal slippage warnings

---

src/hooks/useWithdrawalInfo.ts

For some reason testnet has withdraws paused today so I added this to test the dialog

fix: remove debug helper

---

src/pages/markets/MarketsBanners.tsx

##Summary
Added UTM tracking parameters to the rebate banner URL to enable proper tracking.

fix: Add UTM parameters to rebate banner URL for tracking

---

src/constants/dialogs.ts
src/providers/TurnkeyAuthProvider.tsx
src/providers/TurnkeyWalletProvider.tsx
src/views/dialogs/CheckEmailDialog.tsx
src/views/dialogs/EmailSignInStatusDialog.tsx
src/views/dialogs/OnboardingDialog.tsx
src/views/dialogs/TransferDialogs/DepositAddressDialog.tsx

- Conclude email loading state when going through magic link
- Add new user var to fix welcome message
- Make onClose optional on CheckEmailDialog

fix: Signin Loading State and Welcome message

---

src/views/dialogs/SimpleUiTradeDialog/SimpleTradeSteps.tsx

wait for fill for market orders so you can see your fill status/price

fix: more specific market order treatment on simple order confirm screen

---

src/bonsai/rest/compliance.ts
src/lib/affiliates.ts
src/lib/compliance.ts
src/lib/hdKeyManager.ts
src/state/_store.ts
src/state/wallet.ts
src/state/walletSelectors.ts

...and use nonce recordkeeping for hdKey so subscribers know when it changes.

fix: move ephemeral state out of persisted wallet store
