dydxprotocol/v4-web

src/hooks/useDydxClient.tsx
src/lib/abacus/dydxChainTransactions.ts
src/lib/abacus/index.ts
src/lib/telemetry.ts
src/views/dialogs/ExchangeOfflineDialog.tsx

Add try/catch when initializing the composite client in the ChainTransactionProtocol.
- handle error within try/catch
- trigger exchange offline dialog if composite client fails to initialize
---
* `<ExchangeOfflineDialog>`
* `closeDialog` if the `activeDialog` is `DialogTypes.ExchangeOffline`
* `lib/abacus/dydxChainTransactions`
* initialize client within `try/catch`
* open `ExchangeOffline` dialog if client fails to initialize
* `lib/abacus`
* setStore for `chainTransactionClient`
* `lib/telemetry`
* console.warn on non production builds 
---

handle composite client error

---

src/views/forms/AccountManagementForms/WithdrawForm/WithdrawButtonAndReceipt.tsx

* `WithdrawButtonAndReceipt`
* Do not check for the token balance since we can not diff via abacus yet. Also it is broken when trying to check a chain that the wallet is not currently on.

Do not get token balance on withdraw

---

src/hooks/useAccountBalance.ts
src/views/forms/AccountManagementForms/DepositForm.tsx

* `hooks/useAccountBalance`
* evmQuery/useBalance was being open unnecessarily by `AccountMenu`
* Change it so that evmQuery is only enabled if addressOrDenom is explicitly provided

Do not poll evm unless addressOrDenom is provided

---

package.json
pnpm-lock.yaml
src/hooks/useLocalNotifications.tsx
src/hooks/useSquid.tsx
src/lib/wagmi.ts
src/views/forms/AccountManagementForms/DepositForm.tsx

Add all squid supported EVM networks to wagmi config, so the user can start deposit from any of the chains in the deposit UI. Also have a grace period for onboarding status error handling. 
---
* `src/views/forms/AccountManagementForms/DepositForm.tsx`
* remove gasPrice validation, it is not used or always available.
* `src/lib/wagmi.ts`
* Add all the evm Chains found in the squid sdk_info
* take out alchemyProvider since we don't use it anymore
* `src/hooks/useLocalNotifications.tsx`
* Have an error grace period for onboarding status polling
* `viem`
* updated: ^1.1.6 -> 1.12.2

Add all squid evm networks to wagmi

---

src/views/forms/TradeForm/AdvancedTradeOptions.tsx

|  Before | After |
|---|---|
| <img width="308" alt="Before" src="https://github.com/dydxprotocol/v4-web/assets/13111994/ffcdbcba-937f-4623-83d2-4d6775869c91">  | <img width="308" alt="Screen Shot 2023-10-07 at 1 58 32 PM" src="https://github.com/dydxprotocol/v4-web/assets/13111994/59888ba7-50c8-4c77-8539-02ecdffc3bd0">  |
* `<AdvancedTradeOptions>`
* Fix breaking Abacus change of `goodUntil` -> `goodTil`

Fix GoodTil var changes

---

.github/workflows/deploy-testnet.yml
package.json
scripts/inject-app-deeplinks.sh

It needs to have the actual app ID during deployment for the deeplinks to work.

Add script to inject iOS app ID to public/.well-known/apple-app-site-association

---

src/hooks/useNotificationTypes.tsx
src/views/TransferStatus.tsx
src/views/TransferStatusSteps.tsx

Determine onboarding type based on passed in props instead of squid status API which is unreliable currently.
* `src/views/TransferStatusSteps.tsx`
* Determine type based on passed in prop instead of squid status API which is unreliable currently
* `src/views/TransferStatus.tsx`
* Determine type based on passed in prop instead of squid status API which is unreliable currently
* `src/hooks/useNotificationTypes.tsx`
* Determine onboarding type based on localCache and pass it to `TransferStatusSteps` TransferStatus`

Onboarding status do not rely on squidAPI to determine if deposit/withdraw

---

public/configs/env.json

New `dev2` ap-ne-1 validator IP address is `54.92.118.111`. It was previously `35.75.227.118`.
Update `dev2` validator IP address.

Update `dev2` validator IP address

---

package.json
pnpm-lock.yaml
src/constants/account.ts
src/hooks/useSubaccount.tsx

- bump abacus to fix USDC balance
- update auto-deposit for v4-client update
* `src/constants/account.ts`
* `AMOUNT_RESERVED_FOR_GAS_USDC` change from 100000 to 0.1 since abacus no returns with units already parsed
* `src/hooks/useSubaccount.tsx`
* use `compositClient.depositToSubaccount` so it would parse the unit for us. 
* `@dydxprotocol/v4-abacus`
* updated: v0.7.5 -> v0.7.6

Fix auto-deposit

---

src/hooks/useAccountBalance.ts
src/pages/rewards/DYDXBalancePanel.tsx
src/views/forms/AccountManagementForms/DepositForm.tsx

`assetSymbol` shouldn't be a factor in determining what balance to return

remove asset symbol for account balance logic

---

src/hooks/tradingView/useTradingView.ts
src/lib/orders.ts
src/views/tables/FillsTable.tsx

there can be a state where `marketId` is missing, abd `options`'s `symbol` is undefined which caused trading view to fail and crash the app.

fix trading view error

---

public/.well-known/apple-app-site-association

From v3->v4, the URL path schema has changed such that all url paths are now "#" prefixed. In order for the association file to perform properly, the URL path a user navigates to on their device must match a path specified in the association file. Because all of our v4 paths have the "/#/" prefix, there were no matches and thus the iOS device would not route to the app, instead, always the website.
As an example you can tap these links from your iOS device with a v4 build on it:
1. https://v4.testnet.dydx.exchange/trade
2. https://v4.testnet.dydx.exchange/#/trade/ETH-USD
#1 will route to the app (note it will crash due to a bug, separate work item tracked here: [TRCL-3100 : universal links are crashing the app](https://linear.app/dydx/issue/TRCL-3100/universal-links-are-crashing-the-app)) …

TRCL-3099 : update apple app site association file

---

package.json
pnpm-lock.yaml
src/views/dialogs/OnboardingDialog/GenerateKeys.tsx

- Update abacus to fix usdc balance
- abort key derivation if second signature fails/don't match
* `src/views/dialogs/OnboardingDialog/GenerateKeys.tsx`
* return if second signature fails, also set state back to NotDerived
* `@dydxprotocol/v4-abacus`
* updated: ^0.7.6 -> ^1.0.3

Abort key derivation if second signature fails

---

src/views/dialogs/TradeDialog.tsx
src/views/forms/TradeForm.tsx
src/views/forms/TradeForm/PlaceOrderButtonAndReceipt.tsx

issue: trade / place order button shows "Unavailable" when we're waiting for indexer to return subaccount response as validation that trade is enabled
fix: show a loading state instead of "unavailable" text during onboarding

show loading state instead of "Unavailable" for place order button

---

src/components/Collapsible.tsx
src/components/NavigationMenu.tsx
src/layout/Header/HeaderDesktop.tsx
src/views/TransferStatus.tsx

1. Reorder header so it's trade > portfolio > markets > chain token
2. center align header items
3. make caret icon smaller
4. transition should be on `rotate` instead of `transform` if it's rotating

reorder header, center align header, update collapse caret icons

---

src/pages/portfolio/AccountDetailsAndHistory.tsx
src/views/AccountInfo/AccountInfoConnectedState.tsx
src/views/forms/AccountManagementForms/DepositForm/DepositButtonAndReceipt.tsx
src/views/menus/AccountMenu.tsx

- When buying power is negative, show '-' instead of the value where makes sense, matching v3 behavior;
- Hide send/withdraw options in AccountMenu dropdown when balance is negative.

Handle negative free collateral + buying power

---

public/configs/env.json

We will use this section to load the params for mobile apps during build and run-time.  It contains iOS app scheme for now.

Configs: Add app configuration to env.json

---

src/hooks/useSubaccount.tsx
src/hooks/useTokenConfigs.ts

Fix bug `depositToSubaccount` and other v4-client functions that take in amount as string, where if the the amount decimals exceeds the token decimals, ethers.parseUnit will throw an error.
Fix this using `toFixed()` to ensure the decimals are correct

Fix decimal overflow bug

---

package.json
pnpm-lock.yaml
src/hooks/useAccounts.tsx
src/hooks/useWalletConnection.ts
src/views/TransferStatus.tsx
src/views/TransferStatusSteps.tsx
src/views/forms/AccountManagementForms/DepositForm.tsx

Depends on https://github.com/dydxprotocol/v4-localization/pull/149
- Memo `resolveWagmiConnector` so it does not repeatedly trigger `WalletConnectConnector` constructor which kicks of a wss auth request everytime
- Do not use `useWalletConnection` directly from Deposit form, it should be using the hook instance from the `useAccounts` context
- During deposit, the final step in does not have the correct transaction URL on complection. This is because the `toChain` object from squid status is not reliable and returns osmosis instead of dydx. It is better to derive the tranasction URL from the final step of `routeStatus` instead
- Update `TransferStatus` string when countdown reach 0, to show "available shortly" instead

Onboarding fixes

---

src/views/dialogs/DepositDialog.tsx

- rename test deposit -> faucet for clarity
- `showFaucet` defaults to true for non-mainnet, and false for mainnet

fix deposit dialog logic

---

public/configs/env.json
src/lib/abacus/dydxChainTransactions.ts
src/views/dialogs/RestrictedGeoDialog.tsx
src/views/dialogs/RestrictedWalletDialog.tsx
src/views/menus/NetworkSelectMenu.tsx

- for dev / staging env, show network select menu in restriction modals
- add missing `mintscanBase` in `env.json`
- use mintscan w/ `tx_hash` where applicable

add network select menu in restriction modals (dev)

---

package.json
pnpm-lock.yaml
src/lib/abacus/rest.ts
src/views/forms/AccountManagementForms/DepositForm.tsx
src/views/forms/AccountManagementForms/DepositForm/DepositButtonAndReceipt.tsx
src/views/forms/AccountManagementForms/SlippageEditor.tsx
src/views/forms/AccountManagementForms/WithdrawForm.tsx
src/views/forms/AccountManagementForms/WithdrawForm/WithdrawButtonAndReceipt.tsx

- Handle squid errors passed back via abacus
- `src/lib/abacus/rest.ts`
- Do not filter response of requests with unsuccessful status codes
- fix max deposit button
- disable slippage editor for now, as we can't edit slippage in abacus yet

Handle squid rout errors

---

src/hooks/useLocalNotifications.tsx
src/hooks/useSquid.tsx
src/views/forms/AccountManagementForms/WithdrawForm.tsx

There is an initial 2m grace period where the status error is ignored. but if it goes over 2m, status can sometime get set as an empty object and 
- increase the grace period.
- Update the status fetch skip logic to skip if error is found or if `squidTransactionStatus` exists and is not "ongoing".

Fix status empty bug

---

src/components/SearchSelectMenu.tsx
src/components/SelectMenu.tsx
src/components/ToggleButton.tsx
src/constants/dialogs.ts
src/layout/DialogManager.tsx
src/pages/Profile.tsx
src/styles/formMixins.ts
src/views/dialogs/DepositDialog.tsx
src/views/dialogs/DepositDialog/DepositDialogContent.tsx
src/views/dialogs/ManageFundsDialog.tsx
src/views/dialogs/TradeDialog.tsx
src/views/forms/AccountManagementForms/DepositForm.tsx
src/views/forms/AccountManagementForms/DepositForm/DepositButtonAndReceipt.tsx
src/views/forms/AccountManagementForms/TestnetDepositForm.tsx
src/views/forms/AccountManagementForms/WithdrawForm.tsx
src/views/forms/AccountManagementForms/WithdrawForm/WithdrawButtonAndReceipt.tsx
src/views/forms/TradeForm.tsx
src/views/forms/TradeForm/TradeSideToggle.tsx
src/views/forms/TransferForm.tsx
src/views/forms/TransferForm/TransferButtonAndReceipt.tsx

- add manage funds entry point in mobile profile
- all transfers dialog will allow user to switch between deposit/withdraw/transfer. this should actually replace mobile dialog for these types, but will do as a followup when i add back the transfer preview/confirm steps
- update deposit, withdraw, and transfer form to use similar styling (inputs spacing, gap, receipt padding and color, label color)

add manage funds dialog and transfers form styling

---

src/hooks/useCurrentMarketId.ts

Change dependency of `useCurrentMarketId` hook. Websocket messages well after initialization triggers this hook which ends up resetting TradeInputs.

Change dep in hook to fix input bug

---

src/layout/Footer/FooterDesktop.tsx
src/views/ExchangeBillboards.tsx
src/views/tables/MarketsTable.tsx

Update Markets table to sort OpenInterest by notional and display 24h volume as fiat value
---
* `<Footer>`
* Make default background of footer buttons transparent
* `<ExchangeBillboard>`
* When on tablet view change `Trades` -> `24h Trades`
* `<MarketsTable>`
* sort OpenInterest by notional
* display 24h volume as fiat value

MarketsTable: Sort OpenInterest by notional, Display 24h volume as fiat value

---

src/components/ComboboxMenu.tsx
src/components/Toast.tsx
src/layout/NotificationsToastArea.tsx

https://github.com/dydxprotocol/v4-web/assets/13111994/92164f67-8a95-4c8f-8253-00f664ac2b54
Update Toast/ToastArea component to be more mobile friendly.
---
* `<ComboboxMenu>`
* Attempted to fix an issue with autofocus in the mobile `<NotificationsMenu>`
* CMDK lib does not expose the props necessary to fix the issue. Added link to repo providing explanation.
* `<NotificationsToastArea>`
* Allow notifs to be stacked
* Make notif collapse toggle larger for mobile breakpoints 
* `<Toast>`
* Always display `CloseButton` when at Mobile breakpoint (No `:hover` effect)
---

Mobile friendly Toast: Collapse/Close

---

package.json
pnpm-lock.yaml

Do not count un-applicable short term orders towards EquityTier limit check
---
* `@dydxprotocol/v4-abacus`
* Equity Tier Limit updated logic
* updated: v1.0.28 -> [v1.0.30
](https://github.com/dydxprotocol/v4-abacus/pull/156)
---
The link to the Abacus PR has a video displaying the correct behavior for short term orders.

Bump Abacus@1.0.30: Equity Tier Limit logic change

---

public/configs/cctp.json

We will load this from Abacus and filter the Squid V1/V2 API based on the content.

Config: Add CCTP supported chains to cctp.json

---

src/abi/erc20_usdt.json
src/views/forms/AccountManagementForms/DepositForm.tsx

USDT contract on ETH is not implemented correctly, so the normal ERC20 Abi fails. 
To fix this, use an USDT ABI as fallback.

Fix USDT approval

---

src/views/forms/TradeForm/LeverageSlider.tsx
src/views/forms/TradeForm/MarketLeverageInput.tsx
src/views/forms/TradeForm/TradeSizeInputs.tsx

Before
https://github.com/dydxprotocol/v4-web/assets/13111994/66039ccc-4e90-4524-9e92-7b03f77c6ab0
After
https://github.com/dydxprotocol/v4-web/assets/13111994/58aa74aa-486a-4fb0-af76-afcf8876790a
Allow Size inputs to gracefully handle `0.0` when deleting chars.  
---
* `<MarketLeverageInput>`
* Add `getSignedLeverage` method to get the raw leverage value (signed)
* Have separate methods to handle when slider is used vs when input is used
* `<TradeSizeInputs>`
* Update redux state using `formattedValue` 
---

Size inputs

---

src/components/CollapsibleTabs.tsx
src/components/Input.tsx
src/components/Table.tsx
src/components/Tabs.tsx
src/pages/trade/HorizontalPanel.tsx
src/styles/layoutMixins.ts
src/views/AccountInfo.tsx
src/views/AccountInfo/AccountInfoConnectedState.tsx
src/views/MarketDetails.tsx
src/views/PositionInfo.tsx
src/views/charts/TvChart.tsx
src/views/tables/OrdersTable.tsx

Fix miscellaneous firefox issues.
---
* `<HorizontalPanel>`
* memoize config for `<CollapsibleTabs>`
* `<AccountInfo>`
* remove `overflow-x: clip`, caused issues with rendering the `<AccountInfo>` at smaller breakpoints on firefox
https://github.com/dydxprotocol/v4-web/assets/13111994/3845e327-f13f-4848-b502-1469fe4f9ad1
* `<AccountInfoConnectedState>`
* Remove `layoutMixins.perspectiveArea`
* Remove `outerBorders` when rendered on MobileTopPanel. Border was rendered out of place at smaller breakpoints on firefox
* `<MarketDetails>`/`<PositionInfo>`
* Remove `position: sticky` made buttons un-clickable in firefox:
*  external links
* close position
https://github.com/dydxprotocol/v4-web/assets/13111994/de517b63-ad14-4a86-a7b4-5aa9c673a06b …

Firefox issues

---

public/configs/cctp.json
src/lib/abacus/dydxChainTransactions.ts
src/views/forms/AccountManagementForms/TokenSelectMenu.tsx

- quietly catch and log NobleClient errors
- remove CCTP mainnet chains that are not supported yet 
- remove outdated swap tooltip

Do not block website if NobleClient cannot init, and other onboarding fixes

---

src/hooks/useCurrentMarketId.ts

Navigate to the Markets page if  the current marketId is not included in subscribed markets. This will be used to handle navigating to markets that have a status of `final_settlement`.
---
* `hooks/useCurrentMarketId`
* If v4_markets has not been subscribed to yet or marketId is not specified, default to validId
* If marketId is not valid (i.e. final settlement), navigate to markets page
* If marketId is valid, set currentMarketId
---

Navigate to the Markets page if  the current marketId is not included in subscribed markets

---

src/views/dialogs/HelpDialog.tsx
src/views/tables/PositionsTable.tsx

Fix stretched icon
---
* `<PositionsTable>`
* 
* `min-width: max-contents;` forces the AssetIcon to stretch in firefox
---

TRCL-3406: firefox mobile position table row has stretched icon

---

src/components/Table.tsx
src/constants/numbers.ts
src/views/tables/MarketsTable.tsx

Updated screenies:
Fix inaccuracies when sorting the Markets table by 1h funding.
---
* `<MarketsTable>`
* use `FUNDING_DECIMALS` as the `fractionDigits` for display of `1h funding`
* `<Table>`
* use `bignumber.js` for number formatting instead of `parseInt`
* `constants/numbers`
* add `FUNDING_DECIMALS`
* defaulted to 6 but can be changed
---

Update comparison function in Table

---

public/configs/documentation.json

[TRCL-3427 : Add Trading Rewards FAQ to Abacus](https://linear.app/dydx/issue/TRCL-3427/add-trading-rewards-faq-to-abacus)
- adds documentation.json
Trading Rewards FAQs are shared across clients, so we can use a deployed FAQs config json to update FAQs remotely.  Naming it `documentation.json` to support further static documentation.

Create documentation.json for trading rewards FAQ

---

src/views/forms/AccountManagementForms/DepositForm/DepositButtonAndReceipt.tsx

`toAmountUSD` is not currently being populated. Temporarily hide fee receipt-line so the users' wallets are the source of truth for gas price.
---
* `<DepositButtonAndReceipt>`
* `toAmountUSD` is not currently being populated. Temporarily hide fee receipt-line so the users' wallets are the source of truth for gas price.

Temp hide fees for CCTP route until Squid returns toAmountUSD

---

public/configs/env.json

Imperator will be scaling down their Testnet Indexing service. Replace all endpoints with the internal dYdX Testnet Indexer.
This PR does not affect any environment outside of testnet.

[Testnet only]: Imperator testnet indexer to be scaled down

---

src/views/MarketDetails.tsx

With deprecation of non linear margin requirement, only display `Initial Margin Fraction` instead of `Base Initial Margin Fraction`
---
* `Base Initial Margin Fraction` -> `Initial Margin Fraction`
---

Remove base from baseInitialMarginFraction

---

package.json
pnpm-lock.yaml
src/components/visx/XYChartWithPointerEvents.tsx
src/constants/charts.ts
src/constants/markets.ts
src/hooks/useOrderbookValues.ts
src/state/perpetualsCalculators.ts
src/views/charts/DepthChart.tsx
src/views/charts/DepthChart/Tooltip.tsx
src/views/charts/DepthChart/index.tsx
src/views/charts/FundingChart/Tooltip.tsx
src/views/charts/FundingChart/index.tsx

https://github.com/dydxprotocol/v4-web/assets/13111994/b564ea48-8f14-4e16-80e6-73a0448d0903
Update Funding Chart Tooltip to take up less vertical space.
---
* New: `<FundingRateTooltipContent>` / `<DepthChartTooltipContent>`
* pulled the `<TooltipContents>` out of FundingRate.tsx and DepthChart.tsx for easier viewing
* Fixed type errors
* `<XYChartWithPointerEvents>`
* Fixed typescript issues
* `invert` does not exist within visx's `XScale` and `YScale` but it does??
* `constants/charts`
* Move all types/enums/constants from `DepthChart` and `FundingChart` to designated const file
* Added `FundingDirection.None` for when fundingRate === 0 (only happens on testnet)
* Changes: `state/perpetualsCalculator`
* `hooks/useOrderbookValues`
* Move formatting hook from …

Update Funding Chart Tooltip

---

src/pages/portfolio/Portfolio.tsx
src/state/accountCalculators.ts
src/state/accountSelectors.ts

| No open positions/orders  | With open positions/orders |
| ------------- | ------------- |
| <img width="1493" alt="Screenshot 2024-01-12 at 10 56 02 AM" src="https://github.com/dydxprotocol/v4-web/assets/70078372/a0211be5-b478-42c0-9a64-bac0dcec7ecf"> | <img width="1263" alt="Screenshot 2024-01-12 at 10 41 25 AM" src="https://github.com/dydxprotocol/v4-web/assets/70078372/037211f1-e195-40b1-82b8-c8bbc5735324"> |
Display the number of open positions/orders in portfolio sidebar when they exist (non-zero). 
---
N/A
* `<Portfolio>`
* Update Positions and Orders labels to optionally render a tag showing num of open positions and orders when non zero
* Matched selector + display logic to what is used in `HorizontalPanel` 
None needed.
N/A
N/A
N/A
* `state/accountSelectors.ts`
*  Updated …

TRCL-1979 Show open positions / orders in portfolio sidebar

---

src/constants/analytics.ts
src/hooks/useAnalytics.ts
src/hooks/useApiState.ts

It's hard to diagnose how far behind the indexer was from a NetworkStatus event in Amplitude currently. Adding this param should allow us to see how far behind we are when that event is triggered.

Add trailing blocks to NetworkStatus analytics event

---

src/lib/abacus/dydxChainTransactions.ts
src/views/forms/AccountManagementForms/DepositForm.tsx
src/views/forms/AccountManagementForms/WithdrawForm.tsx

- Throw an error when attempting an CCTP deposit/withdraw, if the NobleClient has not been connected successfully.
- Also fix withdraw error being double wrapped.

CCTP deposit/withdraw to throw error if nobleClient is not initialized

---

src/hooks/useWalletConnection.ts
src/lib/abacus/index.ts
src/views/dialogs/OnboardingDialog/GenerateKeys.tsx
src/views/forms/AccountManagementForms/DepositForm.tsx
src/views/forms/AccountManagementForms/DepositForm/DepositButtonAndReceipt.tsx
src/views/forms/AccountManagementForms/WithdrawForm.tsx
src/views/forms/TransferForm.tsx

Issue: wallet connection pops up when it doesn't need to
More context:
- we currently automatically connect wagmi when connecting the wallet. 
- when remember me is enabled however, and we refresh or relaunch the browser, the wallet is connected via the stored keys, but wagmi still tries to resolve and resulting in wallet extension popup, resulting in a bad ux.
- wagmi is needed however during deposit (wagmi signer)
Fix:
- when remember me is enabled, don't connect with wagmi automatically
- only connect with wagmi during deposit

Delay wagmi connection if remember me is enabled

---

public/configs/env.json

ios build script pulls from this env file to determine app scheme. we need to update with more unique scheme. See corresponding [iOS PR](https://github.com/dydxprotocol/v4-native-ios/pull/66)

Update ios app scheme in env.json

---

src/components/Table.tsx

markets table is showing view more button because data was empty and later updated, which the state did not account for
updating so we are stricter on when can view more button show up

update view more table logic

---

public/configs/env.json

For native apps, we need a special deployment for testers of deployer's app. They would have access to deployer's mainnet, and regular testnet

Added a TestFlight deployment so help native app testers

---

src/components/Checkbox.tsx

- changing checkbox's label back to a `label` html element to add back the clickable text behavior
steps to test:
pnpm ladle, check checkbox story's disabled + not disabled behavior

add back clickable label to checkbox

---

src/hooks/useSubaccount.tsx

Use BigInt because mainnet value of 10_000_000_000_000_000_000_000 returns scientific notation 1e22.

Use BigInt toString() for initialDepositAmount param

---

public/chart-bars-background.svg
public/chart-bars.svg
src/components/Panel.stories.tsx
src/components/Panel.tsx
src/constants/dialogs.ts
src/layout/DialogManager.tsx
src/views/dialogs/DisplaySettingsDialog.tsx
src/views/menus/AccountMenu.tsx

The first PR in the series of 3 to add themeing + green/red preference functionality in the app.
1. Creates entry point in settings dropdown for "display settings"
2. Creates `Display Settings` dialog with theme options
Second [PR](https://github.com/dydxprotocol/v4-web/pull/256): adds functionality for swapping green/red preference.
Third [PR](https://github.com/dydxprotocol/v4-web/pull/261): exposes entry point for swapping green/red preference. 
| Classic | Dark | Light |
| ---- | ---- | ---- | 
| ![Screenshot 2024-01-30 at 4 42 18 PM](https://github.com/dydxprotocol/v4-web/assets/70078372/a036e97a-f406-4097-be5a-eb59a8b27146)  | ![Screenshot 2024-01-30 at 4 42 22 PM](https://github.com/dydxprotocol/v4-web/assets/70078372/71664509-8208-449c-8e55-ec40dbbcd2eb) | ![Screenshot 2024-01-30 …

TRCL-3520 Add entry point + modal for themeing 

---

src/hooks/useWalletConnection.ts

there was a bug where clicking wallet type does nothing
repro steps:
1. use metamask, connect to wallet A, remember me enabled
2. refresh or quit chrome and reopen, your dydx wallet should still be connected (but wagmi will be disconnected)
3. disconnect wallet
4. choose metamask again but nothing happens
seems like the issue is the `isAccountConnected` check is using an outdated version of evmDerivedAddresses, where during disconnect wallet the `encryptedSignature` should be deleted

use updated isaccountconnected check

---

package.json
pnpm-lock.yaml
src/components/Output.tsx
src/components/Table.tsx
src/constants/abacus.ts
src/constants/localization.ts
src/constants/tooltips/trade.ts
src/lib/abacus/index.ts
src/lib/abacus/stateNotification.ts
src/lib/testFlags.ts
src/pages/Profile.tsx
src/pages/rewards/DYDXBalancePanel.tsx
src/pages/rewards/RewardHistoryPanel.tsx
src/pages/rewards/RewardsHelpPanel.tsx
src/pages/rewards/RewardsPage.tsx
src/pages/rewards/TradingRewardsSummaryPanel.tsx
src/state/account.ts
src/state/accountSelectors.ts
src/views/tables/TradingRewardHistoryTable.tsx

no trading rewards:
with trading rewards:
steps to test:
- change network to staging
- trade something (orders must be filled) so you get trading rewards -- you should see a block reward notification
- head to Rewards page, and add `?tradingrewards=1` to end of url
- observe trading rewards summary + historical trading rewards table
- toggle between monthly/weekly/daily - this is more relevant when you have at least 2 days of trading rewards, hence feature flag gated and want to keep testing in staging for 1week+
Shared components changes
- `Output`: component now supports UTC option -- this is because we're showing the time periods in UTC in the historical trading rewards table
- `Table`: enable view more row custom styling
Library changes
- abacus / state manager: adds support for new …

Add historical trading rewards gated by feature flag

---

package.json
pnpm-lock.yaml

Should be merged after https://github.com/dydxprotocol/v4-abacus/pull/214 to enable testing ROC on frontend

Bump abacus to enable ROC

---

src/components/Table.tsx
src/views/tables/TradingRewardHistoryTable.tsx

for trading rewards table, clicking view more should expand 10 rows each time, instead of showing all data.
this pr adds that behavior option to Table, and update to use prop `viewMoreConfig`

Add more controlled pagination to table

---

src/constants/analytics.ts
src/hooks/useDydxClient.tsx
src/lib/abacus/dydxChainTransactions.ts

This is helpful for research to identify which transactions are sent by the front-end website.

Add memo to transactions for onchain tracking

---

src/views/charts/DepthChart/Tooltip.tsx

Original price impact calculation was just wrong as far as I can tell, chatted with research and confirmed that formula should be `abs(price - midMarketPrice) / midMarketPrice`. Also confirmed with product that we should be using the nearestDatum price (the circle on the chart), rather than the pointer, for price.
*This also more closely reflects the [formula](https://github.com/dydxprotocol/titan/blob/d1020661ff487ebb588a0592e018e4442f0728c3/src/pages/trade/charts/DepthChart.tsx#L185) we used in v3 (though that one used bestAsk/bestBid instead of midMarket)
https://github.com/dydxprotocol/v4-web/assets/70078372/5829b2e9-f615-4f6f-92e8-d6cf6c120112
---

CT-363 Fix Price Impact Calculation

---

src/views/forms/ClosePositionForm.tsx
src/views/forms/TradeForm.tsx
src/views/forms/TradeForm/PlaceOrderButtonAndReceipt.tsx

1. Add a warning icon to the trade order button whenever it is disabled due to an input error (includes missing inputs)
2. Wrap the trade order button in a tooltip with error message when applicable (showed product the screenshots)
---
* Modified: `src/views/forms/TradeForm/PlaceOrderButtonAndReceipt.tsx`
* replaced `isClosePosition` prop with `confirmButton` prop because it was a little hard to follow all the ternaries in code
* Also seemed like caller should just be passing down this info
* Removed `showConnectWallet?: boolean;` which was unused
* Updated: `src/views/forms/TradeForm.tsx` (caller of `PlaceOrderButtonAndReceipt`)
*  Updated: `src/views/forms/ClosePositionForm.tsx` (caller of `PlaceOrderButtonAndReceipt`)

CT-145 Add warning icon + tooltip to trade order button CTA

---

src/components/Tag.stories.tsx
src/components/Tag.tsx

Nit issue I noticed while poking around the positions table; quick fix. 
Issue was that highlighted tag text color was wrong for `isHighlighted` (purple), which was apparent in light mode.
| | Classic | Light | Dark |
| ----- | ----- | ----- | ----- |
| Before | <img width="310" alt="Screenshot 2024-02-14 at 10 25 50 AM" src="https://github.com/dydxprotocol/v4-web/assets/70078372/92d61814-de0e-450e-895f-61990350bbe5"> | <img width="307" alt="Screenshot 2024-02-14 at 10 25 41 AM" src="https://github.com/dydxprotocol/v4-web/assets/70078372/a3b84640-7efb-41f8-b863-47a655729317"> | <img width="304" alt="Screenshot 2024-02-14 at 10 25 45 AM" src="https://github.com/dydxprotocol/v4-web/assets/70078372/65058904-5b97-4cd4-a568-8578f65e32a5"> |
| After | <img width="309" alt="Screenshot 2024-02-14 …

Fix highlighted tag text color

---

src/hooks/tradingView/useChartMarketAndResolution.ts

https://github.com/dydxprotocol/v4-web/assets/70078372/78a40026-259f-4dda-b45f-0b834083e661
---
Bug due to `tvWidget?.setSymbol` being called every time the resolution was being changed - where the resolution that was being saved was first the `savedResolution`. Updated effect to no longer depend on `resolution` dependencies, with comment explaining why.

CT-486 Fix sticky chart resolution setting

---

src/lib/abacus/dydxChainTransactions.ts
src/lib/network.ts

there was a json.stringify parsing error that covered up the broadcast error, making abacus failed to parse it properly

fix parsing error and surface tx broadcast error

---

src/hooks/tradingView/useChartLines.ts

Apparently `tvWidget.chart()` can still crash on the `innerApi()` call after `onChartReady` is true 🙃 . The check for whether the inner api/window is ready is `headerReady`.
- Tested switching networks didn't crash the page.
https://github.com/dydxprotocol/v4-web/assets/70078372/d51972ae-b95e-4ac5-abed-332f20f58c38

CT-499 Fix TradingView crash on network switch

---

public/configs/env.json
public/configs/v1/env.json

Updates the 7 testnet envs, RO is still disabled on mainnet. Updated both versions of `env.json`.
Verified reduce only now shows on testnet environments.
https://github.com/dydxprotocol/v4-web/assets/70078372/708d8610-288f-47c9-a21f-7010c69967ed

Update env config to enable reduce only in testnet

---

package.json
pnpm-lock.yaml
public/configs/v1/env.json

- bump abacus, which includes `usePessimisticCollateralCheck` feature flag + logic to use pessimistic collat check price (i.e. worse(limitPrice, oraclePrice) when calculating subaccount state from trade 
- add `usePessimisticCollateralCheck` to env.json

use pessimistic collat check in non-dev/staging envs

---

src/constants/tvchart.ts
src/hooks/tradingView/useChartLines.ts
src/lib/tradingView/utils.ts

Following conversation with Se:
1. Add yellow liquidation line to charts (when applicable)
2. Removed size from entry + liquidation line (but kept on order lines)
https://github.com/dydxprotocol/v4-web/assets/70078372/d529c317-3ffa-4502-bd22-4fea032ded45
---
* `constants/tvchart.ts`
* Add a new position line type (`liquidation`)
* `lib/tradingView/utils.ts`
* Add a color for liquidation line
* `hooks/tradingView/useChartLines.ts`
* Update to draw a liquidation line when necessary
* Remove quantity from entry line
---

CT-525 Add liquidation position line to charts

---

src/views/AccountInfo/AccountInfoConnectedState.tsx

Add transfer button to the Account Connected Header next to withdraw and deposit

Add transfer button to AccountInfoConnected Header (OTE-186)

---

src/pages/portfolio/Overview.tsx

this was killing me to see
was looking at code to scope out linear tix anyways
| Before | After |
| ----- | ----- |

Remove unnecessary border on Portfolio Overview "Open Positions" table

---

src/constants/potentialMarkets.ts

---
* `potentialMarkets`
* Lower valid amount of oracles from `6` -> `5` 
---

Lower safe num oracles

---

package.json
pnpm-lock.yaml
src/components/Table/TableCell.tsx
src/constants/abacus.ts
src/constants/styles/colors.ts
src/hooks/Orderbook/useOrderbookValues.ts
src/lib/orders.ts
src/pages/portfolio/Positions.tsx
src/pages/trade/HorizontalPanel.tsx
src/state/accountCalculators.ts
src/state/accountSelectors.ts
src/styles/globalStyle.ts
src/styles/themes.ts
src/views/tables/Orderbook.tsx
src/views/tables/PositionsTable.tsx
src/views/tables/PositionsTable/PositionsTriggersCell.tsx

1. Create the skeleton for the `Triggers` column in SL/TP (flagged behind `sltp`)
1. Doesn't implement a lot of the functionality yet, partial states also not implemented
2. Does implement logic for finding any SL/TP orders (if they exist) for a position 
| Classic | Dark | Light |
| ----- | ----- | ----- |
| <img width="1295" alt="Screenshot 2024-03-04 at 2 11 49 PM" src="https://github.com/dydxprotocol/v4-web/assets/70078372/7dea0641-6f46-4029-9fe6-8eda66baed45"> | <img width="1306" alt="Screenshot 2024-03-04 at 2 12 18 PM" src="https://github.com/dydxprotocol/v4-web/assets/70078372/7b68ae50-d02b-410f-8ea6-2b34868d883e"> | <img width="1305" alt="Screenshot 2024-03-04 at 2 12 29 PM" src="https://github.com/dydxprotocol/v4-web/assets/70078372/bab484b0-9d43-44f9-963e-a8e863ba3929"> |
---
* …

CT-653 Render Triggers Column skeleton

---

src/lib/abacus/websocket.ts

Add additional checks in `websocket.ts` to ensure only one live ws connection per instance

websocket stability: ensure one live websocket connection per instance

---

.vscode/settings.json
package.json
pnpm-lock.yaml
src/lib/testFlags.ts
src/pages/portfolio/Positions.tsx
src/pages/trade/HorizontalPanel.tsx
src/views/tables/PositionsTable.tsx
src/views/tables/PositionsTable/PositionsMarginCell.tsx

https://linear.app/dydx/issue/TRA-90/add-margin-column-to-positionstable
Add column in the `<PositionsTable>` to display USDC margin. This will only be displayed with the `?isolatedmargin=1` query param.
---
* `<PositionsTable>`
* Add `margin` column to column definitions
* `<HorizontalPanel>`
* Add `margin` column based on query flag
* New: `<PositionsMarginCell>`
* Add table cell that displays position's margin
* `lib/testFlags`
* add `isolatedmargin` query flag
---

feat(positiontable): add column for margin

---

package.json
pnpm-lock.yaml
src/components/Toast.tsx
src/constants/notifications.ts
src/hooks/useApiState.ts
src/hooks/useNotificationTypes.tsx
src/hooks/useNotifications.tsx
src/layout/Footer/FooterDesktop.tsx
src/layout/NotificationsToastArea/NotifcationStack.tsx
src/lib/abacus/dydxChainTransactions.ts
src/state/app.ts
src/state/appMiddleware.ts
src/state/appSelectors.ts
src/views/dialogs/ExchangeOfflineDialog.tsx
src/views/forms/AccountManagementForms/DepositForm/DepositButtonAndReceipt.tsx
src/views/forms/AccountManagementForms/WithdrawForm/WithdrawButtonAndReceipt.tsx
src/views/forms/TradeForm/PlaceOrderButtonAndReceipt.tsx

---
depends on https://github.com/dydxprotocol/v4-localization/pull/327
* `src/layout/NotificationsToastArea/NotifcationStack.tsx`
* Allow for custom action, needed for the status page link
* `src/components/Toast.tsx`
* Removed Radix's Toast.Action, because it wasn't rendering the child for some reason. I also don't really understand what it is for. Let me know if this is a bad idea!
* `src/constants/notifications.ts`
* Add notification type for APIerror
* Add `SingleSessionNotificationTypes` to define notification types that do not need to be saved to local storage
* `src/lib/abacus/dydxChainTransactions.ts`
* Instead of triggering the offline Dialog when connection initialization fails, save the error to redux store, so that it can be used to trigger the notification
* …

feat(notifications): use notification for connection errors

---

.nvmrc

N/A
Adds a `.nvmrc` so you can do `nvm use` in the repo instead of checking the currently used version.
You can also enforce usage of this in your CI, depending on what tools you're using (like GitHub actions).
If you decide to use this, I'd suggest updating the README as well.
---
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
Do `nvm install` the first time in the repo, and `nvm use` to activate the correct node version.

chore: add .nvmrc

---

package.json
scripts/install-local-abacus.js

Adds a new script that can be run via `pnpm run install-local-abacus`. It assumes that abacus is checked out to `../v4-abacus` relative to this repository. It handles building abacus and installing the local package.

build: Add install-local-abacus script

---

src/pages/Profile.tsx

I'm not super familiar with this codebase, but I noticed a typecast that seemed odd to me. if you look at the `actions` variable in the `Profile` page, it appears to be casted instead of typed. unsure if this is necessary due to side effects not immediately noticeable from my PR, but i've submitted a potential fix
Before:
the 'key' property was deleted from an action but no type error pops up
After:
IDE properly recognizes there's a type error since `actions` variable is typed instead of casted
Increase type safety of the codebase by opting for variable typing over function output typecasting. Casting the output of the filter function removes the type safety of the `action` variable's base array as it overrides any values that occur before the filter function.
---
* …

fix: action type in profile page

---

scripts/install-local-abacus.js

Don't fail the script if we didn't find any previously built packages.

build: Fix clean build case in install-local-abacus

---

.gitignore
package.json
pnpm-lock.yaml
scripts/install-local-abacus.js
vite.config.ts

Ideally we'd do this through Vite's `server.watch` config. But it currently doesn't work with subdirectories of `node_modules`. Tried a couple different workarounds in this thread: https://github.com/vitejs/vite/issues/8619, ultimately this is the solution that worked.
This does introduce a new dev dependency (https://www.npmjs.com/package/vite-plugin-restart), but it seems pretty widely used (ton of sponsors, including Vite) and somewhat recently maintained (Nov 2023).

build: Trigger Vite restart when install-local-abacus is run

---

package.json
pnpm-lock.yaml
src/hooks/tradingView/useTradingView.ts
src/hooks/useAccounts.tsx
src/hooks/useAnalytics.ts
src/hooks/useDydxClient.tsx
src/hooks/useEndpointsConfig.ts
src/hooks/useNextClobPairId.ts
src/lib/tradingView/dydxfeed/index.ts
src/lib/tradingView/utils.ts

Trading view chart loads pretty slowly, especially on first load
1. Separate indexer client out
- api calls from indexer client were previously blocked by abacus connection to validator(s) to initialize the compositeClient. Since we only offer one option for indexer endpoint, there's no advantage to getting indexer client from composite client, and indexer api calls can be kicked off faster without that dependency.
2. Removing markets dependency for rendering trading view
- previously we only initialize trading view after markets are fetched
- by not caring about the markets, network calls to get candles are now queued at 2s instead of 4s on average
- this sacrifices setting price scale by ignoring tickSizeDecimals (this might be fixed with auto price scale in newer versions of …

feat(performance): trading view kick off getBars / request candles sooner

---

.gitignore
package.json
vite.config.ts

pnpm dev will currently fail
- update script so it creates an index.html locally, which is added to .gitignore
- update `build` in vite.config so it won't throw an error when there's no entry_points directory

fix: update entry-points config logic to allow for pnpm dev

---

package.json
pnpm-lock.yaml
src/views/forms/AccountManagementForms/DepositForm/DepositButtonAndReceipt.tsx

instead of prompting evm wallet reconnect on deposit button mount, only do that when cta is clicked (button: reconnect wallet)
to test, enable remember me, quit browser and reopen, check deposit dialog

fix: connect wagmi on cta and not automatic for deposit

---

src/hooks/tradingView/useTradingView.ts
src/lib/tradingView/dydxfeed/index.ts

when navigating from portfolio -> trade, chart doesn't load because `hasMarkets` was set to true and no `initialPriceScale` needs to be set
test:
1. navigate from portfolio -> trade
2. change markets
3. observe trading view chart loads

fix(tradingview): handle case when initial price scale doesnt need to be set

---

.vscode/settings.json

Turn on file watching for v4-abacus node module so types get re-indexed automatically.

build: Add v4-abacus to VSCode file watcher

---

src/components/CollapsibleTabs.tsx
src/components/PotentialPositionCard.tsx
src/pages/trade/HorizontalPanel.tsx
src/pages/trade/UnopenedIsolatedPositions.tsx
src/styles/layoutMixins.ts

https://github.com/dydxprotocol/v4-web/assets/13111994/11155585-a954-4714-a322-dae455f17123
Scaffold `Unopened Isolated Positions` section in the `<HorizontalPanel>`. This will help to navigate users to their orders on Isolated Markets before the position has been made available.
In order to test add `?isolatedMargin=1` query param
---
* New: `<UnopenedIsolatedPositions>`
* Smart container that will eventually take Abacus state to populate a carousel of `PotentialPositionCards`.
* `<HorizontalPanel>`
* Add `slotBottom` to display component outside of the `HorizontalPanel`
* Updated `Styled` Record
* Note: `styled` method from `styled-components` does not persist generic types. Had to cast `as CollapsibleTabs<InfoSection>` to get typing to work.
* New: `<PotentialPositionCard>`
* component …

feat(isolated-positions): Scaffold Unoponed Isolated Position cards

---

src/constants/orderbook.ts
src/hooks/Orderbook/useDrawOrderbook.ts
src/hooks/Orderbook/useOrderbookValues.ts
src/state/accountSelectors.ts
src/views/tables/Orderbook.tsx

fix same orderbook row showing twice or not at all during the prev data canvas draw
bug:
https://github.com/dydxprotocol/v4-web/assets/9400120/7b7717b2-67e3-4eeb-8629-680b9079c4e6
make it look "sharper" by increase contrast of
- rows getting removed state (darker text)
- bars are less rounded and more gap
- shorter transition state

fix(orderbook): rows missing/duplicated in transition state

---

src/layout/Footer/FooterDesktop.tsx

match status dot to status error
previously when status is undefined, status dot will just be shown as operational which is inaccurate (since we do show chain disruption error)
fix is add a connecting state, so it will accurately switch to either operational / degraded after
https://github.com/dydxprotocol/v4-web/assets/9400120/3330aa5a-b98a-4dcb-b664-59055130559d
https://github.com/dydxprotocol/v4-web/assets/9400120/1a50f0a4-cb4d-476e-8ca0-e60b48e6ccc5

fix: update status dot for connecting state and actually degraded

---

src/components/Table.tsx
src/lib/numbers.ts
src/pages/portfolio/Overview.tsx
src/pages/portfolio/Positions.tsx
src/pages/trade/HorizontalPanel.tsx
src/styles/tradeViewMixins.ts
src/views/forms/TradeForm/AdvancedTradeOptions.tsx
src/views/tables/PositionsTable.tsx

net funding could only be found via single position view, with it gone, we need to show it in the positions table
1. add net funding column
2. handle neutral case for signed output (color should not be green when it's just 0)
3. reduce horizontal padding in table since we're running out of space

chore: add net funding to positions table

---

package.json
pnpm-lock.yaml

Pulls in this fix: https://github.com/dydxprotocol/v4-abacus/commit/3b13ccb7df9c43e431226197b0a7ebd952587177
Verified by checking percentage on Bitcoin position locally:
| Testnet (before) | Local (after) |
| <img width="541" alt="Screenshot 2024-04-11 at 2 50 26 PM" src="https://github.com/dydxprotocol/v4-web/assets/70078372/8aadf02f-f392-4a01-b17a-3d65a1ca8d62"> | <img width="535" alt="Screenshot 2024-04-11 at 2 50 23 PM" src="https://github.com/dydxprotocol/v4-web/assets/70078372/396c0e52-be6a-4886-93c8-c914d0a0c2e9"> |
Also confirmed error handling on SLTP still works (which is the majority of the changes between v.37->.40)
Note sl/tp is still gated; to test, use `?sltp=true`.

fix(sltp): bump abacus for updated perc calculation

---

src/hooks/useCurrentMarketId.ts
src/views/forms/ClosePositionForm.tsx

Follow up to: https://github.com/dydxprotocol/v4-web/pull/407#discussion_r1552125968
Updated `ClosePositionForm`'s `useEffect` update so that it resets market regardless of `currentInput`.
Verified:
- Close positions dialog stays open between market changes when there is a market change to a market w/ an open position
- Close positions dialog closes (we reset to trade form) when there is a market change to a market w/o an open position
https://github.com/dydxprotocol/v4-web/assets/70078372/8f08fcb5-6f47-4f2b-b00f-0dc6262c23da

chore(closepositions): clean up trade form stage between market changes

---

src/views/tables/PositionsTable/PositionsTriggersCell.tsx

Should be comparing with triggerPrice instead of price (this is calculated by abacus with some widened bounds for market orders)
| Before | After |
| ----- | ----- |
| <img width="1538" alt="Screenshot 2024-04-23 at 3 43 14 PM" src="https://github.com/dydxprotocol/v4-web/assets/70078372/d849697d-b28c-49ad-ae60-67bafb22723c"> | <img width="1482" alt="Screenshot 2024-04-23 at 3 46 03 PM" src="https://github.com/dydxprotocol/v4-web/assets/70078372/41ade6c1-7e39-43c4-9f9a-5ccdffca07df"> |
Confirmed that we do also show it properly:

fix(sltp): fix liquidation bug comparison

---

src/constants/styles/colors.ts
src/lib/orders.ts
src/lib/tradeData.ts
src/styles/globalStyle.ts
src/styles/themes.ts
src/views/TradeBoxOrderView.tsx
src/views/forms/TradeForm.tsx

Improve market order volatility experience by re-directing a user to create a limit order when they receive a blocking error due to liquidity conditions.
- Confirmed this should only happen on "error" (when user is blocked from placing an order) and not "warning"
*This only triggers when slippage > 10%; I just modified abacus locally for testing purposes
---
https://github.com/dydxprotocol/v4-web/assets/70078372/86db03a1-8d3b-4977-bec3-766646b51688
* `TradeForm.tsx`
* Updated error code here to check if the errorCode to be displayed is a liquidation error; if so, render an arrow CTA which navigates the user to a limit order
* `styles/colors.ts`, `styles/themes.ts`
* Added a `whiteFaded` color token for the background of the button
* `styles/globalStyle.ts`
* Added a `--color-white-faded ` …

chore(trade): add CTA to place limit order on liquidity error

---

src/hooks/tradingView/useChartLines.ts

Add (quantity) size to position lines (liquidation + entry).
Noticed an existing bug: the decimal precision on the quantity of the position lines (entry, liquidation) isn't quite right when switching between markets - it uses the decimal precision of the last market (see below). 
https://github.com/dydxprotocol/v4-web/assets/70078372/f2484123-4bd3-4795-828f-1da87f103d4d
Spent a lil too long trying to fix it by rounding the number passed in, only to realize this is (supposedly) controlled by the [priceScale](https://github.com/dydxprotocol/v4-web/blob/main/src/lib/tradingView/dydxfeed/index.ts#L73) of the chart widget api. It seems like it's not quite set properly between markets because we only [set](https://github.com/dydxprotocol/v4-web/blob/a28eae9e8dfd8aa2cb5915099135b9f159e9e2cd/src/h …

chore: add position size to liquidation + entry lines

---

pnpm-lock.yaml
public/configs/cctp.json
src/components/SearchSelectMenu.tsx
src/constants/cctp.ts
src/constants/tooltips/withdraw.ts
src/views/forms/AccountManagementForms/TokenSelectMenu.tsx
src/views/forms/AccountManagementForms/WithdrawForm.tsx
src/views/forms/AccountManagementForms/WithdrawForm/WithdrawButtonAndReceipt.tsx

Following pictures are new UI according to [this design spec](https://www.notion.so/dydx/Revamp-withdrawal-and-deposits-UI-71d417f9c08d4c8eab2de4b27f88cbc5?pvs=4#1cb26156b9a645ba9562fece48d52203)
NOTE: there are 2 minor differences:
1. we don't insert an "and" between the 2nd to last and last cctp token names when listing them in the withdraw form subheader tooltip. This is solely because it's slightly annoying add an 'and' there. I can update this if people feel strongly. Personally, I don't think it matters.
2. We use the term bridge fee instead of 3rd party fees because there's a precedent for a string key const existing in our state. I couldn't find an equivalent for 3rd party fee so I'm opting to keep it as is. I don't think this is an easily fixable change (but I could be wrong). …

feat: refresh withdrawals ui to add clarity around fees (OTE-276)

---

src/views/forms/AccountManagementForms/TokenSelectMenu.tsx

moves cctp tokens to the top (in this case, usdc for the token search select item)

fix: move usdc to top of TokenSelectMenu dropdown

---

src/views/forms/AccountManagementForms/SourceSelectMenu.tsx

Add lowest fees decorator text to SourceSelectMenu.
This fulfills the last of the spec described in [Revamp Withdrawals and Deposits UI](https://www.notion.so/dydx/Revamp-withdrawal-and-deposits-UI-71d417f9c08d4c8eab2de4b27f88cbc5#d24417175fb64789b2b029129736d16b)
---
* `src/views/forms/AccountManagementForms/SourceSelectMenu.tsx`
* adds lowest fees decorator text as either descriptor or slotAfter depending on whether or not type is withdrawal or deposit (due to differing size of the select in those situations).
This is not ideal since this makes the assumption that withdraw = small width and deposit = large width. But to do this 'properly' could be very difficult and likely not worth the time it would take for this operation

feat: add lowest fees decorator text to SourceSelectMenu

---

src/hooks/useTriggerOrdersFormInputs.ts
src/lib/abacus/index.ts
src/views/forms/AccountManagementForms/TestnetDepositForm.tsx

because of the only one input at a time constraint in abacus, we should pretty much always reset to focused input to trade when transfers/triggers dialogs are closed, so that the trade button has the right validation state (i.e. usually "enter amount")
places that use that clear the input state -> refocus to trade input:

fix: unavailable place order button

---

package.json
pnpm-lock.yaml
src/hooks/useNotificationTypes.tsx

abacus changes to pull: [1](https://github.com/dydxprotocol/v4-abacus/pull/325), [2](https://github.com/dydxprotocol/v4-abacus/pull/330)
also added duration for TP/SL notifications (because they were never disappearing and it was driving me bonkers)
Confirmed update to 90 days:
Double checked logs by building a v of abacus locally with Logger.e {}

chore(sltp): bump abacus v to pull in new analytics + change sl/tp duration to 90 days

---

src/lib/orders.ts
src/views/OrderStatusIcon.tsx
src/views/dialogs/DetailsDialog/OrderDetailsDialog.tsx
src/views/notifications/TradeNotification/index.tsx
src/views/tables/OrdersTable.tsx

some duplication and discrepancy between existing `getStatusIconInfo` and `OrderStatusIcon` -> combining and cleaning up logic
- remove open -> partially filled logic because it's now supported
to test, check fill notification and orders tab

chore: clean up order status icon

---

package.json
pnpm-lock.yaml
src/components/Notification.tsx
src/constants/notifications.ts
src/hooks/useNotificationTypes.tsx
src/views/dialogs/PreferencesDialog.tsx

---
* `PreferencesDialog`
* Update to localize `Release Updates`
* `Notification.tsx`
* Add `white-space: break-spaces` to body to prevent period from falling onto new line after `here`. Checked other notifications and everything looks fine, so I'm inclined to keep it like this 🤔 but lmk if there's something i haven't thought through!
* `constants/notifications.ts`
* added `RevampedConditionalOrders` to `ReleaseUpdateNotificationIds`
* `hooks/useNotificationTypes`
* synced with product that we want this notification to last for ~1 month
* added trigger to render conditional orders revamp notification
* `localization`
* updated: v1.1.76 -> v1.1.78
---

chore(sltp): create notification for sltp

---

src/constants/trade.ts
src/hooks/useNotificationTypes.tsx
src/hooks/useSubaccount.tsx
src/lib/abacus/dydxChainTransactions.ts
src/state/account.ts
src/state/accountSelectors.ts
src/views/dialogs/DetailsDialog/OrderDetailsDialog.tsx
src/views/notifications/OrderCancelNotification.tsx
src/views/notifications/OrderStatusNotification.tsx

add notifications for canceling order as well for more visual feedback
- notification is very similar to order status notif, but with different data
to test
- cancel orders via orders table + order details dialog
- cancel short term orders -- this is a weird flow but you should see just one toast reflecting most updated status

feat: order status [5/n] cancel order toasts

---

src/components/Output.tsx
src/hooks/useMarketsData.ts
src/hooks/usePerpetualMarketSparklines.ts
src/hooks/usePerpetualMarketsStats.ts
src/pages/markets/Markets.tsx
src/views/ExchangeBillboards.tsx
src/views/MarketsStats.tsx
src/views/tables/MarketsCompactTable.tsx
src/views/tables/MarketsTable.tsx

Additional cleanup.
---
* `<MarketsCompactTable>`
* update styled object
* fix props
* add headers
* fix data accessor
* remove default sort
* `<Markets>`, `<ExchangeBillboard>`
* update styled object
* `<MarketStats>`
* update styled object
* remove `View` button (it didn't do anything...) 
* `<MarketsTable>`
* Utilize abacus perpetualMarket `line` data 
* 
* 
* `<Output>`
* add `slotLeft` prop
* `hooks/useMarketsData`
* remove 24h sparkline query call. Utilize abacus stored line info
---

refactor(market-revamp): sum staking rewards, update compact tables, reduce sparkline api call

---

scripts/install-local-abacus.js

the readme states that 
"Our tooling assumes that the [v4-abacus repo](https://github.com/dydxprotocol/v4-abacus) is checked out alongside v4-web
```
--- parent folder
|___ v4-web
|___ v4-abacus
```
"
however, the script currently seeks for `~/v4-abacus` which requires that v4-abacus be put in a specific directory, rather than just being in the same repo as v4-web. this fixes some UX issues by:
1. making the readme accurate - now abacus just need to be in the same dir as v4-web
2. giving the dev more flexibility on where they put their code (mine is in ~/dydx)

fix: change script to use relative pathing

---

.github/workflows/run-e2e.yml

Re-enable e2e tests CI, now that the browserstack plan is activated. 
Also test on staging instead of testnet for now, since testnet deployment does not always have the password gating. To improve the e2e test, we could detect vercel password gating and conditionally proceed.

chore: re-enable e2e

---

public/configs/v1/env.json
src/components/Details.tsx
src/components/Output.tsx
src/components/ToggleGroup.tsx
src/constants/tooltips/trade.ts
src/lib/numbers.ts
src/lib/wagmi.ts
src/views/MarketDetails.tsx
src/views/MarketStatsDetails.tsx
src/views/forms/TradeForm/MarketLeverageInput.tsx

UI updates for effective IMF changes. going according to [figma spec](https://www.figma.com/file/fMQodZKzn9B5aZTN5G0fLJ/dYdX-%E2%80%BA-Desktop?type=design&node-id=27458-41684&mode=design&t=pkj8dD829Aa7Idt7-0).
---
* `src/views/MarketDetails.tsx` + `src/views/MarketStatsDetails.tsx`
* update to use `DynamicOutput` component
* New: `DynamicOutput`
* extension of existing `Output` component.
* allows for static and dynamic value props so we can conditionally render old leverage/imf vs new one side by side
* continuing to update `Styled` objs as we go, migrating styles to live inside the `Styled` obj declaration and removing the existing `Any` typing for styles
IMF = EIMF:
UI looks the same as before
IMF != EIMF:
Slider, marketdetails, and marketStatsDetails all updated with new IMF and …

feat: ui updates for eimf [OTE-299]

---

src/components/Table.tsx
src/pages/trade/HorizontalPanel.tsx
src/views/tables/FillsTable.tsx
src/views/tables/OrdersTable.tsx
src/views/tables/PositionsTable.tsx

Add default pagination to tables; reduce pagination vals for horizontal panel since it's shorter. Helps improve perf for heavy traders. I want to also follow up to maybe not load alllll the data from abacus (i.e. like a couple thousand orders), but that'll be a separate PR.
*Chose 25 as a default to-load number that works for my large desktop screen (without scrolling). Can adjust in the future.
see perf on heavy trader simulation:
https://github.com/dydxprotocol/v4-web/assets/70078372/2e741747-0aef-4eab-97ba-a4e30d4c6a1b
---
* `HorizontalPanel.tsx`
* Have all tables in this view pass in `VIewMoreConfig` of just 10 to initial load since it's a "shorter" view
* `Table.tsx`
* Add default to `ViewMoreConfig`
* `FillsTable.tsx`, `PositionsTable.tsx`, `OrdersTable.tsx`
* Pass through …

fix(perf): add default pagination to all tables

---

src/views/forms/AccountManagementForms/WithdrawForm.tsx

update `WithdrawForm` errorMessage handling to prefer human-actionable error message before displaying routing messages.
fixes issue [where we see "Unable to resolve quote"](https://linear.app/dydx/issue/OTE-291/fix-squid-error-showing-unable-to-resolve-quote) instead of "amount must be >10"
as a general rule of thumb, we should be prefer user addressable error messages vs backend error messages since they may not be actionable by the end-user

fix: prefer cctp validation to squid route validation [OTE-291]

---

package.json
pnpm-lock.yaml
src/views/tables/FillsTable.tsx

small change, noticed we were missing it when auditing some tables.
Also pulled in most recent abacus such that assets + chains are now alphebetized (lowest fees are still pulled to the top because we do that sorting in web in `TokenSelectMenu`).

fix(perf): memoize fills table

---

src/views/MarketsDropdown.tsx

Fix market dropdown pagination button being hidden due to incorrect height calculation. It still looks sorta janky, but will fix in my overall PR to update pagination to be page based ([ticket](https://linear.app/dydx/issue/TRCL-3578/update-pagination-on-tables-to-be-page-based)) (new designs).

fix: fix market dropdown table pagination

---

src/views/ExchangeBillboards.tsx
src/views/MarketsStats.tsx

adding `contentSectionDetachedScrollable` layout mixin created strange interactions with safari mobile view. after removing the style i can't see any regressions.
context: 
- https://dydx-team.slack.com/archives/C03GKH23YAZ/p1715339847403409
- https://dydx-team.slack.com/archives/C04CQCRGELV/p1715355311206209

fix: remove scrollArea style to fix safari mobile

---

src/views/notifications/OrderCancelNotification.tsx

there's a lag between order confirmed cancel (node response) vs indexer's response, therefore currently the order cancel toast can be canceling -> open -> canceled
fix: optimistically believe in node response that it's canceled and show that (or if indexer says it's confirmed first), so that toast should go from canceling -> canceled, or canceling -> error when fail
test: cancel an open order

fix: order cancel toast should go from canceling -> canceled / error

---

src/components/DropdownMenu.tsx
src/components/NavigationMenu.tsx
src/components/SearchSelectMenu.tsx
src/components/ToggleGroup.tsx
src/lib/genericFunctionalComponentUtils.ts
src/pages/trade/HorizontalPanel.tsx
src/views/MarketsStats.tsx
src/views/dialogs/NewMarketMessageDetailsDialog.tsx
src/views/forms/TradeForm.tsx
src/views/forms/TradeForm/TradeSideToggle.tsx
src/views/tables/LiveTrades.tsx
src/views/tables/Orderbook.tsx
src/views/tables/OrderbookTradesTable.tsx

I created two utilities for turning react higher order functions into normal higher order functions so the typescript compiler can do higher order type inference correctly.

chore: cleaner handling of higher order function type inference (styled and forwardRef)

---

src/views/forms/TriggersForm/OrderSizeInput.tsx
src/views/forms/TriggersForm/OrderSizeSlider.stories.tsx
src/views/forms/TriggersForm/OrderSizeSlider.tsx

Previously, bug was that sliding the slider could display a seemingly usable order size - but error out on the button (due to incorrect step size, or below min size). This was because the value we were displaying as the order size (right size input) was being rounded while our abacus input we were sending back wasn't. Updated order slider to always send back rounded value (to make it easier to use) and to not round order size right size input - since that is seemingly what the user wants to input.
https://github.com/dydxprotocol/v4-web/assets/70078372/ded278fc-4d5d-4410-8689-1ed90b685997

fix(sltp): match order size slider value to input value

---

pnpm-lock.yaml
src/components/visx/TimeSeriesChart.tsx
src/pages/portfolio/AccountDetailsAndHistory.tsx
src/views/charts/PnlChart.tsx

a couple of pnl chart improvements:
- fix flickering of x-axis after period toggle value changes
- remove logic for detecting period / toggle value based on zoom domain to avoid bugginess -- not amazing but i'd rather sacrifice this than figuring out the two fighting to pick the right toggle value during zoom / animation
- only show toggle options based on how much data they have; i.e. if user's first transfer history is less than 30 days ago, don't show the 90 day option
- along with abacus bump, it should restrict number of api calls to pnl to max 90 days + also don't continuously send api calls which eats up cpu in prod
testing:
recommend testing on mainnet (i.e. pulling this down locally and update env.json) since testnet indexer pnl seems buggy currently
test with accounts with 7d+ …

fix: pnl table flickering + limit toggles to available data

---

src/constants/analytics.ts
src/hooks/useAnalytics.ts
src/hooks/useDydxClient.tsx
src/lib/abacus/dydxChainTransactions.ts
src/lib/abacus/index.ts
src/lib/abacus/rest.ts
src/lib/abacus/websocket.ts

Current implementation of selecting gas denom is only applicable when using a method from `useDydxClient`. Add capability to set gas denom for transactions in Abacus' chain transaction protocol.
---
* `lib/abacus`, lib/abacus/dydxChainTransactions`
* expose setter method for gas denom
* `hooks/useDydxClient`
* Preserve selected gas denom by setting within useEffect
---

fix(selected-gas-denom): preserve gasDenom and set in chainTransactionProtocol

---

src/constants/analytics.ts
src/hooks/useLocalNotifications.tsx
src/views/forms/AccountManagementForms/DepositForm.tsx

adds success/fail/new transfer notification tracking.
creates new event `AnalyticsEvent.TransferNotification` with metadata:
- txHash (uses this as the id)
- toAmount (amount to withdraw/deposit)
- timeSpent (time since tx start)
- triggeredAt (time the tx began)
- status (success, error, new)
- type (withdraw/deposit)

chore: add logging for status tracking [1/n]

---

src/lib/abacus/rest.ts
src/lib/isExternalLink.tsx

It is filling the console in dev mode on localhost since all the urls are like "/history" which is an invalid url.

fix: remove noisy log

---

src/hooks/useNotificationTypes.tsx

The addition of the notification type here:
https://github.com/dydxprotocol/v4-web/blob/fix-deposit-notif/src/views/forms/AccountManagementForms/DepositForm.tsx#L289
Uncovered a bug where the notification transferType is not calculated correctly.

fix: the transfer type ternary is not correct

---

src/lib/abacus/rest.ts

Remove abacus rest log since it's kinda expected

fix: remove log when bad url to prevent spam

---

src/views/tables/MarketsTable.tsx

tested by building locally and looking at markets page

chore: show all markets w/o pagination on market page

---

src/views/forms/ClosePositionForm.tsx

one of the most frequent place order errors are related to this "Reduce-only orders cannot increase the position size"
trader can submit multiple close position orders if they click it kinda fast
this PR should prevent this behavior
to test, attempt to close an open position by clicking the close position CTA on the form multiple times

fix: clear inputs on close position click to avoid subsequent place orders

---

src/styles/formMixins.ts
src/views/dialogs/DepositDialog/DepositDialogContent.tsx
src/views/forms/AccountManagementForms/DepositForm.tsx
src/views/forms/ClosePositionForm.tsx
src/views/forms/TradeForm.tsx
src/views/tables/FillsTable.tsx
src/views/tables/OrdersTable.tsx
src/views/tables/PositionsTable.tsx

context: some traders use a much smaller screenheight and trade form's footer cover most of the inputs
fix: make footer not sticky when screen is too short
also opt to use ' | ' for the table column header

chore: make trade form footer not sticky depending on screen height + table column header nits

---

pnpm-lock.yaml
src/views/dialogs/DetailsDialog/OrderDetailsDialog.tsx
src/views/tables/OrdersTable.tsx
src/views/tables/OrdersTable/OrderActionsCell.tsx

context: some traders are running into unexpected equity tier limit issues and seeing an order count mismatch. their accounts have "stuck" stateful orders that are "best_effort_canceled" but are hidden by indexer/FE
indexer will include best effort canceled orders in the initial v4_subaccounts subscribe ws message, and FE will display those in the orders tab, and enable the Cancel button so traders can attempt submitting another cancel to get rid of them.
cancel ux flow on FE is not impacted, because we keep a local `isCanceling` state which disables subsequent cancel clicks already. 
To test, sub out the v4_subaccounts subscription message and add two example stuck orders, for example the following (you'll have to sub out your subaccount id etc. as well). Observe that the cancel button …

chore: enable traders to cancel "BEST_EFFORT_CANCELED" stateful orders

---

src/pages/portfolio/Orders.tsx
src/pages/trade/HorizontalPanel.tsx
src/views/tables/OrdersTable.tsx

I kinda feel like we should only show margin type of you have a non-cross order but it's kind of annoying to look at that so I've added it everywhere.

feat: add margin type to orders table

---

src/styles/constants.css
src/views/AccountInfo/AccountInfoConnectedState.tsx
src/views/tables/OrdersTable.tsx

I didn't change calculation at all, just modified the number of boxes and titles. 
Tooltips need update:

feat: update wording and remove old trade page account boxes

---

src/hooks/useAccounts.tsx
src/state/accountSelectors.ts

Abacus was rejecting v4-web state change requests as a result of...
- abacus stateManager.sourceAddress not being set... as a result of
- v4-web not being able to set the sourceAddress... as a result of
- abacus AccountSupervisor not having an account... as a result of
- v4-web attempting to set the sourceAddress before the account was set
we could have done this the *more correct way* which is to functionally ensure that these dependent codepieces cohabit the same function or exist in functions nested in a linearly executed piece of code.
but that would involve figuring out what all the account setting dependencies and requirements are so for now we've took the hacky route of:
- checking for the existence of a subAccount (aka `Account` in abacus) and adding that to the dependencyArray of …

fix: get transfers state working

---

package.json
pnpm-lock.yaml
src/constants/tooltips/trade.ts
src/state/inputsSelectors.ts
src/views/dialogs/TradeDialog.tsx
src/views/forms/TradeForm.tsx

…rginModeSelection if existing position
---
* `<TradeForm>`, `<TradeDialog>`
* Update marginMode selector
* Add tooltips
* `constants/tooltips`
* Add targetLeverage tooltip
* updated: v1.1.92 -> v1.1.97
---

style(trade-form): update trade form with tooltips and marginMode selection (2/N)

---

src/pages/trade/HorizontalPanel.tsx
src/state/account.ts
src/state/accountSelectors.ts
src/views/tables/FillsTable.tsx

context: for traders who've traded a bit, fills tab number will just consistently be 99+ which is not that useful. instead, we want to just show number of unseen fills, either for current market, or total.
logic:
- we treat all existing fills (i.e. first fills from abacus) as "seen"
- when trader selects fills tab on Trade or sees the Fills table in portfolio, all fills (for the current market if filter, or all) will be marked as seen. no fun logic to determine what's rendered :p
- that also applies to fills that come in when fills table is being rendered; those fills will be marked as seen once they switch market / navigate away from table
to test:
- create some market orders in different markets
- navigate to and away from Fills tab on Trade page and observe number different
- navigate …

feat: update fills tab number logic to count unseen fills only

---

src/constants/analytics.ts
src/lib/analytics.ts

result of discussion: https://dydx-team.slack.com/archives/C042V24U87Q/p1715894605604209 
this PR https://github.com/dydxprotocol/v4-web/pull/504/files broke our analytics events since we were no longer sending `eventData` as a param in our `details` object.
added typing around the `CustomEvent` function that prevents this from happening again.
TODO: add a test for this as well

chore: type custom events

---

src/constants/abacus.ts
src/views/MarketDetails.tsx

Display perpetual market type in Details
---
* `<MarketDetails>`
* Add new detail item for perpetualMarketType
* `constants/abacus`
* PerpetualMarketType
---

chore(market-type): display perpetual market type in Details

---

package.json
pnpm-lock.yaml
src/views/menus/AccountMenu.tsx

- Added a new item in AccountMenu "Multi-Factor Authentication"
- Privy's MFA modal is shown when item is clicked
- There's a PR in v4-localization to add the new localized string https://github.com/dydxprotocol/v4-localization/pull/486
[mfa.webm](https://github.com/dydxprotocol/v4-web/assets/13419428/d2725f17-d584-455f-9cc6-73d99bf7e7d5)

feat: Self-served MFA modal

---

package.json
pnpm-lock.yaml
src/hooks/useAccounts.tsx
src/hooks/useWalletConnection.ts

- Privy's MFA modal is shown after a new user signs up
- This modal won't show for already existing users
- Modal is dismissible 
- Due to the signature being setup headlessly, we need to give Privy a second to finish the execution of the modal's logic before `signTypedDataAsync` is called so I added a `sleep` call. Privy's login was failing with `exited_auth_flow` due to this, now it shouldn't fail anymore!
[mfa.webm](https://github.com/dydxprotocol/v4-web/assets/13419428/06ec9cb0-7994-4dea-bd61-c8af09006da5)

feat: Prompt MFA after sign up

---

src/views/tables/PositionsTable/PositionsTriggersCell.tsx

had to manually override a bunch of button styles because we don't technically have a button size this small. I don't think we should be using buttons this tiny (generally) so keeping as an override as opposed to making a new size in the core component
- verified the diff states + that it is clickable

chore: make sl/tp rectangles clickable

---

src/components/BaseButton.tsx
src/components/Details.tsx
src/components/Tabs.tsx
src/components/WithDetailsReceipt.tsx
src/views/charts/DepthChart/Tooltip.tsx
src/views/charts/FundingChart/Tooltip.tsx
src/views/forms/AccountManagementForms/DepositForm/DepositButtonAndReceipt.tsx
src/views/forms/AccountManagementForms/WithdrawForm/WithdrawButtonAndReceipt.tsx
src/views/notifications/BlockRewardNotification/index.tsx
src/views/notifications/IncentiveSeasonDistributionNotification.tsx

- decrease padding in receipts, especially in tooltip content (longstanding feedback) and with receipt button (more likely someone on a short screen will see the CTA .v.)
- changing horizontal padding of button back to rem -- this matches the design system more actually
test:
- Details are used across the app, mainly details dialog, market details, receipt areas, notifications, tooltip contents
- compare before/after side by side

chore: padding / real estate

---

src/App.tsx
src/layout/Header/HeaderDesktop.tsx
src/lib/testFlags.ts
src/pages/token/Token.tsx
src/pages/token/rewards/GovernancePanel.tsx
src/pages/token/rewards/NewMarketsPanel.tsx
src/pages/token/rewards/RewardsHelpPanel.tsx
src/pages/token/rewards/RewardsNavPanel.tsx
src/pages/token/rewards/RewardsPage.tsx

and address follow up from https://github.com/dydxprotocol/v4-web/pull/632#discussion_r1628496812.
merged both into `enableStaking` since they both serve the same purpose.
Tested by rendering token page with `enableStaking` on and off.

chore(staking): merge tradingrewardsrehaul + enablestaking flags

---

package.json
pnpm-lock.yaml
src/constants/notifications.ts
src/hooks/useNotificationTypes.tsx
src/views/notifications/IncentiveSeasonDistributionNotification.tsx

distribute s4 notifs
will hold merge until rewards are actually distributed but ready for review

chore: season 4 reward distributed notification

---

src/hooks/usePerpetualMarketsStats.ts
src/views/ExchangeBillboards.tsx

update fee estimation to be 2bps of total volume instead of relying on numia since integration is curr broken. Also removed the chart since it's going to be inaccurate and we're shifting off (and our approximation is not enough data to allow us to render the chart). [context](https://dydx-team.slack.com/archives/C03GKH23YAZ/p1718002439106939)
* `src/views/ExchangeBillboards.tsx`
* Updated fee output rendering to `compactFiat` since it's an approximation (and weird to see decimals on an approximation)

fix: update markets fee estimation

---

src/lib/tradeData.ts
src/views/forms/TradeForm/PlaceOrderButtonAndReceipt.tsx

postOrder can be null but if we still want to show that diff state that it's becoming null

fix(isolated-margin): show diff state in place order cta

---

src/hooks/useStakingValidator.ts

Originally, initial load never showed validator name + validator icon on unstaking panels. 
Bug was due to `unbondingDelegations` initially being null and the query not re-running when `unbondingDelegations` updated (even though it was a dep in the `callback` it wasn't a dep on the `useQuery` call). Fixed by adding `unbondingDelegations` and `currentDelegations` to `queryKey`. 
- Also removed `useCallback` wrapper since it's effectively not doing anything here.
- `?staking=true`: verify names show on unstaking panels when initially linking wallet
https://github.com/dydxprotocol/v4-web/assets/70078372/4a2ab6ac-b544-403b-b08e-05016b4b8463

fix(staking): fix unstaking validator names not showing on initial render

---

src/views/forms/TradeForm/PlaceOrderButtonAndReceipt.tsx

Display full `liquidationPrice` in trade receipt.
---
* `<PlaceOrderButtonAndReceipt>`
* Update `liquidation-price` output to use tickSizeDecimals

chore(liquidation-price): use tickSizeDecimals

---

src/constants/account.ts

Reserve 50 cents to be used for gas after depositing.
---
* `constants/accounts`
* Change reserved usdc from `0.1` -> `0.5` 
---

chore(gas): reserve 0.50 usdc

---

src/constants/account.ts
src/hooks/useSubaccount.tsx
src/views/menus/AccountMenu.tsx

Reblance wallet if usdc balance drops below `$0.05`.
---
* `<AccountMenu>`
* Add `Wallet Balance` in AccountMenu when `isDev`
* <img width="371" alt="Screen Shot 2024-06-13 at 10 29 18 AM" src="https://github.com/dydxprotocol/v4-web/assets/13111994/ee34eb09-151a-4f15-99f7-12762e7e4fac">
* `constants/account`
* add `AMOUNT_USDC_BEFORE_REBALANCE`
* `hooks/useSubaccount`
* Add `rebalanceWalletFunds` to handle deposits and withdraws
---
Tested by spending gas and logging the refill

feat(rebalance-wallet): rebalance wallet if usdcBalance is low

---

src/state/accountCalculators.ts
src/state/accountSelectors.ts
src/views/CanvasOrderbook/index.tsx
src/views/forms/ClosePositionForm.tsx
src/views/forms/TradeForm/PlaceOrderButtonAndReceipt.tsx
src/views/tables/Orderbook.tsx

when full closing an isolated position, post order position margin should be displayed as zero in the place order receipt
to test:
- open an isolated position
- check close position -> full closing should show position margin going to null
- open an order in the same market
- check close position -> full closing should show similar position margin instead of going to null

chore: override post order position margin for full close position on isolated market

---

src/views/tables/OrdersTable.tsx
src/views/tables/PositionsTable.tsx

chatted with brendan and agreed that behavior in fills table was correct - which uses [`stepSizeDecimals`](https://github.com/dydxprotocol/v4-web/blob/main/src/views/tables/FillsTable.tsx#L101)
| Positions Table | Orders Table |
| <img width="1387" alt="Screenshot 2024-06-14 at 4 33 08 PM" src="https://github.com/dydxprotocol/v4-web/assets/70078372/4133e732-c3ca-430c-a759-2fbebe694b94"> | <img width="1381" alt="Screenshot 2024-06-14 at 4 33 15 PM" src="https://github.com/dydxprotocol/v4-web/assets/70078372/98d98d29-37ec-4aac-b279-70545394df61"> |
---

fix: fix decimal places on order size/amount in positions + orders table

---

package.json
pnpm-lock.yaml
src/lib/abacus/index.ts

bump abacus to 1.7.79 for https://github.com/dydxprotocol/v4-abacus/pull/452

feat: cancel trigger orders automatically / abacus bump

---

src/constants/markets.ts
src/hooks/useMarketsData.ts
src/state/perpetualsSelectors.ts
src/views/MarketsStats.tsx
src/views/tables/MarketsCompactTable.tsx

Instead of showing now new markets, show the newest markets. Approximate this by using the markets with the highest `clobPairId`.

fix: Recently Listed Markets View Sorted by `clobPairId`

---

src/views/ExchangeBillboards.tsx

by request [here](https://dydx-team.slack.com/archives/C06EMJW8M63/p1718725737016719)

fix: add back precision to earned by stakers

---

package.json
pnpm-lock.yaml
src/components/Output.tsx

Fix AbacusV2 regression where sparkline retrieval was set to false.
---
* `<Output>`
* Re-add multiplier for percent values
* return `val` instead of `valueBn` to fix `smallPercent` and `percent`
* `v4-abacus`
* updated: v1.7.85 -> v1.7.87
---

fix(sparklines): bump abacus and fix output component

---

src/components/ValidatorDropdown.tsx
src/hooks/useStakingValidator.ts
src/pages/token/rewards/StakingPanel.tsx
src/views/forms/StakeForm/index.tsx

Requirements:
- fetch all validators and filter out any jailed or unbonded validators
- default selection of validator should still be from the preconfigured list in env.json (based on lowest stake weight)
- validators should otherwise be displayed in order of ascending commission and descending stake weight
Added some polishes
- fixed caret rendering before link out icon 
| Dropdown Open | Dropdown Closed |
|<img width="552" alt="Screenshot 2024-06-19 at 7 10 38 PM" src="https://github.com/dydxprotocol/v4-web/assets/70078372/c02b0cf2-5be6-41b8-815a-dbe3aa840bfb"> | <img width="533" alt="Screenshot 2024-06-19 at 7 10 49 PM" src="https://github.com/dydxprotocol/v4-web/assets/70078372/f8fe30cb-8e0a-47a2-8968-5f9540dc09a4"> |
---
* `StakingPanel`  
* Updated to not block …

feat(staking): hydrate validator dropdown with all options

---

src/hooks/useDydxClient.tsx
src/views/dialogs/PreferencesDialog.tsx

Default to USDC as gas denom.
---
* `<PreferencesDialog>`
* Hide gas toggle
* `hooks/useDydxClient`
* Make `setSelectedGasDenom` a noop if not `dev`
---

chore(hide-gasToggle): temp hide gas toggle

---

src/constants/trade.ts
src/hooks/useNotificationTypes.tsx
src/lib/orders.ts
src/state/account.ts
src/state/accountSelectors.ts
src/views/dialogs/DetailsDialog/OrderDetailsDialog.tsx
src/views/notifications/OrderCancelNotification.tsx
src/views/notifications/OrderStatusNotification.tsx

- update PartiallyCanceled order status to use partial fill icon -- the way to differentiate between PartiallyFilled vs PartiallyCanceled is its clear-ability (i.e. the latter is clearable)
- fix clearable orders logic, which fixes open orders count in trade info numbers
- for order status toasts, add a new status `PlaceOrderStatuses.Canceled` -- we want to re-trigger the notif when an order is moved to canceled as well (similar to an error state), with the cancel reason
- also retrigger notif when there's an error string; this should make the notification stay a bit longer when there's an error

chore: improve order statuses

---

src/constants/numbers.ts
src/views/forms/AccountManagementForms/DepositForm.tsx
src/views/forms/AccountManagementForms/WithdrawForm.tsx

QA'd locally - just need to set `Skip` on the onboarding routerVendor configs and it routes to the new vendor seamlessly 😄 
Notes on removed gating params:
- gasFee: We set our gas fee really high - 160,000 gwei is about $1000 USD. happy to decrease this if anyone cares.
- routeType: we still use this value to pick between using the passed in value or undefined.

chore: remove deprecated params [OTE-353]

---

.github/workflows/validate-other-market-data.yml
scripts/validate-other-market-data.ts

Have market validation only run on added/modified markets (instead of the entire JSON) as the JSON has a large number of markets and running validation on all of them every time is time-consuming

feat(new market): have other market validation run on diff only

---

src/hooks/useStakingAPR.ts
src/pages/token/rewards/RewardsHelpPanel.tsx
src/pages/token/rewards/StakingPanel.tsx
src/views/dialogs/StakeDialog.tsx
src/views/forms/StakeForm/index.tsx

1. Add % to the APR
2. Remove +0.1 from gas receipt when staking
3. Remove “how is the pre-configured set of validators determined?” FAQ

fix: polishes for staking

---

src/components/AssetIcon.tsx
src/views/ExchangeBillboards.tsx
src/views/MarketsStats.tsx

Fix spacing issues on Markets page
---
* `<MarketStats>`
* update vertical padding from `0.5rem` -> `1rem`
* make `toggleContainer` `position: absolute` so the two cards with SectionHeader texts are aligned.
* `<ExchangeBillboards>`
* update vertical padding from `0.5rem` -> `1rem`
* `<AssetIcon>`
* Re-introduce placeholder
---

style(nits): update exchange billboards and stats, assetIcons

---

src/lib/abacus/dydxChainTransactions.ts
src/lib/abacus/index.ts

Safeguard to keep dydxChainTranscations and Abacus in sync.
---
* `lib/dydxChainTransactions`
* add `clearAccount` fn
* `lib/abacus/index`
* Update `disconnectAccount` function to include breakdown of chainTransactionsProtocol. 
---

fix(disconnect-cleanup): set localWallet and hdKey to undefined when disconnecting

---

package.json
pnpm-lock.yaml
src/pages/token/rewards/LaunchIncentivesPanel.tsx
src/pages/token/rewards/StakingPanel.tsx
src/views/forms/StakeForm/index.tsx

by request of dan, [designs](https://www.figma.com/design/dhSd8kkcUrY3UBRsdS89kH/dYdX-%E2%80%BA-Legal?node-id=768-911&t=AheVJQAPXWFNpw1i-0)
| LaunchIncentivesPanel | StakingPanel | StakingForm |
| ----- | ----- | ----- | 
| <img width="859" alt="Screenshot 2024-06-26 at 11 25 00 AM" src="https://github.com/dydxprotocol/v4-web/assets/70078372/13b541a9-a959-47c1-97f2-a6c4ecbe5f3c"> | <img width="431" alt="Screenshot 2024-06-26 at 11 24 53 AM" src="https://github.com/dydxprotocol/v4-web/assets/70078372/5c68af2c-e8f9-4359-8629-6b281a83cd05"> | <img width="521" alt="Screenshot 2024-06-26 at 11 33 25 AM" src="https://github.com/dydxprotocol/v4-web/assets/70078372/9ea6850e-8397-4c99-918a-58c0e4da3030"> |
---
* `StakeForm`
* Update error if wallet balance < gas fees and hide max button
* …

fix(staking): update button styling on tokens page + add error if wallet balance < gas fees on stake form page

---

src/views/ExchangeBillboards.tsx
src/views/MarketsStats.tsx
src/views/tables/MarketsCompactTable.tsx

hehe another pass coz the table heading x section header alignment is bugging me
im hiding the table header since that's in the original figma so i think its fine
before:
after:

chore: another pass for the markets panels padding

---

src/views/charts/TradingRewardsChart.tsx

edge case bug where disconnecting/reconnecting on token page didn't show chart properly on initial load
- figured out it was due to `.reverse` being destructive (not v good practice, my bad, also. makes assumptions about data format being returned), replaced with sort 
- i think this bug only started after we updated our abacus data loading? or maybe something else changed 🤷 
https://github.com/dydxprotocol/v4-web/assets/70078372/05d1cc40-077c-487d-8ae8-76030cf361a4 
https://github.com/dydxprotocol/v4-web/assets/70078372/4df06c76-3e2f-4764-aad7-e3c4b8efdbe5

fix(staking): fix chart not loading properly

---

src/components/Icon.tsx
src/constants/abacus.ts
src/constants/analytics.ts
src/icons/chaos-labs.tsx
src/icons/index.ts
src/icons/logo-short.tsx
src/layout/Header/HeaderDesktop.tsx
src/lib/telemetry.ts
src/pages/token/rewards/LaunchIncentivesPanel.tsx
src/views/forms/AccountManagementForms/DepositForm.tsx
src/views/forms/AccountManagementForms/WithdrawForm.tsx

Adds:
- Error analytics event to every `log` event
- tracks an amplitude error event for every error. we should be able to filter based on location
- `DepositForm/onSubmit`
- `WithdrawForm/onSubmit`
- tracks amplitude `routeError` event
- due to the nature of `errorMessage` being in one giant `useMemo` hook which recalculates more than we want it to, we'lll get duplicate events. **this is expected**. we only want to use this to see if skip or squid has an outsized # of routeError analytics events per user session.
Changes:
- icons.index: we unpack the component svgs `logo-short` and `chaos-labs`.
-  WHY? well because... telemetry now imports `analytics`, which imports `./dialogs`, which imports `./wallets` which imports `icons`.
- these icons both use the theme hook, which uses the …

chore: observability for skip migration [OTE-432]

---

public/configs/v1/env.json
src/hooks/useEnvFeatures.ts
src/views/forms/TransferForm.tsx

to avoid future misconfigs should try to clean up flags sooner rather than later, and toggle mainnet as soon as safe (can we safely toggle it before then)?

chore(memo): clean up memo flag + flip staking to be true in mainnet

---

src/components/Output.tsx
src/hooks/Orderbook/useDrawOrderbook.ts
src/lib/consistentAssetSize.ts
src/views/tables/LiveTrades.tsx

Use asset stepSize to determine a valid divisor+suffix and render a compact representation of the asset size. 
BEFORE + AFTER:
AFTERS:

feat: compact, consistent asset amount rendering in orderbook + trades

---

src/pages/portfolio/Overview.tsx
src/pages/portfolio/Portfolio.tsx
src/pages/portfolio/Positions.tsx

This fixes an issue where unopened isolated position cards never wrap and instead force page horizontal scrolling.
Cards sections should be detached since they should never horizontally scroll
Mobile page needs to have a contentContainerPage somewhere since all the components use mixins that assume its within one.

fix: portfolio page content sizing

---

src/hooks/useInitializePage.ts
src/hooks/useStatsig.tsx
src/lib/statsig.ts

we run into a race condition using hooks where the statsig config isn't loaded yet for a new user, causing weird behavior with abacus' state management where state wasnt being populated (Such as transfer input).
solution for now is to just use the initializeSync method.
this prevents abacus race conditions **but** unfortunately it means that the first time a device loads the page they will always fail a gate. this will make gathering data the first time a little bit slow but it will be fine in the long run as our users won't be clearing their local storage all the time

fix: use await for initial statsig config

---

src/hooks/useInitializePage.ts
src/hooks/useStatsig.tsx
src/lib/statsig.ts
src/state/_store.ts
src/types/statsig.ts

Fixes the issue that was called out in https://github.com/dydxprotocol/v4-web/pull/756
The race condition was not inherent to abacus. 
The condition was that the client is constructed separately from initialization, so we were early returning an uninitalized client. This caused abacus to have split behavior where it would call the squid assets endpoint but use the skip processors.
We fix this problem by instead returning the initialization promise instead
TLDR; I am out of practice with promises. This should not have been that hard to debug 😵 
PS: TODO - think about adding tests for this to make sure we don't break the async functionality in the future

feat: statsig async initialization [OTE-496]

---

src/pages/token/rewards/StakingPanel.tsx

1. Remove the APR badge next to 'Unstaked' and add green APR badge next to 'Staked' (no need to exactly copy Keplr)
2. If the balance is more than 0, the text should be 'Primary' instead of 'Tertiary' to avoid confusion (staking panel)

fix: update staking panel text colors + apr tag

---

src/icons/logo.tsx
src/styles/text.css
src/views/dialogs/SharePNLAnalyticsDialog.tsx

Basically fix the share pnl card to look good in light/ dark/classic // also tested the twitter clickthrough
| | Light | Dark | Classic |
| ---- | ---- | ---- | ---- | 
| App | <img width="560" alt="Screenshot 2024-07-03 at 3 21 11 PM" src="https://github.com/dydxprotocol/v4-web/assets/70078372/32de46ce-3b95-44a7-8027-e1e1e4f1bfbb"> | <img width="538" alt="Screenshot 2024-07-03 at 3 21 20 PM" src="https://github.com/dydxprotocol/v4-web/assets/70078372/65c9a7ae-e578-4144-80f5-b5d72d11fb83"> | <img width="535" alt="Screenshot 2024-07-03 at 3 21 25 PM" src="https://github.com/dydxprotocol/v4-web/assets/70078372/400c85a0-507c-44bb-86bc-5a7a06042e17"> | <img width="688" alt="Screenshot 2024-07-03 at 3 23 42 PM" src="https://github.com/dydxprotocol/v4-web/assets/70078372/9941c469-28b4-4c31-a581- …

fix: share pnl card visuals

---

src/constants/analytics.ts
src/views/dialogs/SharePNLAnalyticsDialog.tsx

notion reqs [here](https://www.notion.so/dydx/Grants-Share-P-L-Cards-4af7036029ec4a588cd68720ab0774e5#be73475c1b1749b98a1871dc84d728a3). chatted with chris // confirmed that only metadata we want is asset (asset isn't recorded for modal opening since tracking the opening/closing dialogs is done in another way, but I think that's fine. Can double check with Yang once he's back).

chore: add analytics for share pnl dialog

---

src/views/dialogs/UnstakeDialog.tsx

| before | after |
| <img width="534" alt="Screenshot 2024-07-05 at 1 22 03 PM" src="https://github.com/dydxprotocol/v4-web/assets/70078372/b3cf3c23-34df-4ac2-8387-209d09a69e78"> | <img width="556" alt="Screenshot 2024-07-05 at 1 19 49 PM" src="https://github.com/dydxprotocol/v4-web/assets/70078372/3ede5201-9a22-4d1b-a30e-799249d74e7e"> | 
confirm multiple case looks fine still

fix: fix unstake dialog alignment when single validator staked

---

src/constants/notifications.ts
src/hooks/useNotificationTypes.tsx
src/hooks/useNotifications.tsx

motivation: when api status goes from error to back to normal, the status notification/toast still persists until user closes it. if the api status (e.g. indexer trailing error) is inaccurate / temporary (e.g. network slowness), it will have the illusion that exchange is still down even tho it's back to normal. therefore we want to introduce a way to remove an existing notification (without toast duration) based on condition other than user dismissing it.
this pr introduces two new things:
1. `hideNotification` function: when api status is normal, we want to hide toast if it exists. this will mark the notification as `hidden`
2. `hidden` notification status, one "step" before `cleared` i.e. if notif is cleared it cannot be marked back to hidden, but otherwise a notif can be marked as …

feat: add ability to hide + unhide notification based on condition other than user action

---

src/views/ExportHistoryDropdown.tsx

fix types for export csv code. it was in flight too long and became stale, and as a result missed some new types

fix: types for export csv code

---

src/views/menus/useGlobalCommands.tsx

Navigation to markets using `cmd+k` was broken before. Allow for much easier transition to any market via the `cmd+k` menu. Works for ticker or name, for example "TRX" or "TRON" both work for Tron.

fix: navigation to markets in cmd+k menu

---

src/constants/analytics.ts
src/constants/localization.ts
src/state/localization.ts
src/state/localizationMiddleware.ts

when detected browser language is one of DE, PT, ES or FR, do not default to that language but override it to just use english.
add amplitude tracking when trader switched their language to one of those languages, with metadata including which language they switched from, and their current browser language.

chore: regulatory override EU locale detection and default to English

---

src/hooks/useInitializePage.ts
src/lib/abacus/index.ts

motivation:
- there are reports of seeing api status error messaging more often (even when indexer/validator are fine) when user has switched tabs and come back after after a while
- we've upped the threshold for showing indexer trailing error and also add logic to remove the error toast when api status is calculated back to normal
- as one more thing to try, we want to add logic to restart abacus when web app comes from background -> foreground, similar to what mobile does
this pr:
- add logic to restart abacus when web app comes back to "foreground" after hidden for 10+ seconds
- restarting abacus = reconnect to indexer/validator endpoints + websocket

feat: reconnect abacus when app comes back from background -> foreground after 10s

---

src/views/MarketsStats.tsx
src/views/tables/MarketsTable.tsx

better loading state since markets page is now the default landing
before:
after:
also updated padding a little since the sparklines feel too tall / too little padding:
before:
after:

fix: markets page nits

---

src/hooks/useNextClobPairId.ts
src/views/forms/NewMarketForm/NewMarketPreviewStep.tsx
src/views/forms/NewMarketForm/NewMarketSelectionStep.tsx
src/views/forms/NewMarketForm/index.tsx

Create general function that will calculate next available clobPairId. Add a manual fetch along with the polling fetch to be used onSubmit.
---
* `<NewMarketForm>`
* Remove code that disables form  if `nextAvailableClobPairId` is not populated since it will be fetched right before market proposal.
* `<NewMarketSelectionStep>`
* Remove `clobPairId` prop and use the contents of hook directly.
* Remove code that disables continuing to next step if `clobPairId` is not populated since it will be fetched right before market proposal.
* `<NewMarketPreviewStep>`
* Utilize `fetchNextClobPairId` in `onSubmit`
* Remove `clobPairId` prop and use the contents of hook directly.
* `hooks/useNextClobPairId`
* add `getNextClobPairIdAndTickers` to be used in new `fetchNextClobPairId` and existing memo.
---

feat(next-clob-pair-id): update new market proposal fetch

---

src/components/Tabs.tsx
src/styles/constants.css
src/styles/formMixins.ts
src/views/TradeBoxOrderView.tsx
src/views/forms/AdjustTargetLeverageForm.tsx
src/views/forms/TradeForm/MarketLeverageInput.tsx

- add back missing borders in tabs
- reduce padding (esp vertical) for trade form inputs to get more real estate
- better vertical alignment in transfers inputs
before:
after:
before:
after:
before:
after:

fix: fix missing tab borders, update inputs padding

---

public/configs/rpc.json
public/configs/v1/env.json
scripts/generate-rpc-configs.js

as part of the squid -> skip migration, the skip chains API does not provide an rpc endpoint. This is because the skip team believes public rpc endpoints are not great. The Squid sdk API does provide an RPC endpoint though. I have taken the RPC endpoint provided by [Viem](https://github.com/wevm/viem/tree/main/src/chains/definitions) and added it to a new rpc.json file
Next steps will be to add this to abacus's environment endpoints and then for mobile apps to integrate it.

feat: add rpc.json and script to generate it

---

src/components/Tabs.tsx
src/views/tables/LiveTrades.tsx

the reason that the orderbook leaked into a short trade tab stack is because we use [forceMount](https://github.com/dydxprotocol/v4-web/blame/main/src/pages/trade/VerticalPanel.tsx#L40) on the orderbook tab for [perf reasons](https://github.com/dydxprotocol/v4-web/pull/227) (along with asChild), but not on the trade tab.
- I tried removing these two attributes but it looked off when switching between the tabs
- instead fixed by giving trade tab a z-index of 1 when active (and updating the sticky header z-index to 2 so that scrolling on the trade tab doesn't go over the tab headers), and setting background on entire table rather than rows
- manually slicing to few trades in local branch
https://github.com/user-attachments/assets/8437c287-6e74-47f3-ae12-ef2ee602f580 …

fix: fix orderbook and trade tab stack

---

src/lib/__test__/analytics.spec.ts

add simple analytics test guarding against expected object property names (inspired by prev fixes https://github.com/dydxprotocol/v4-web/pull/730 and https://github.com/dydxprotocol/v4-web/pull/555). Tested with `pnpm run test`

chore: add simple analytics tests

---

public/configs/rpc.json
scripts/generate-rpc-configs.js

some of the rpc URLs in the viem [definition files](https://github.com/wevm/viem/tree/main/src/chains/definitions) are non-functioning so we will prefer to use private alchemy rpc nodes. This PR updates the script to generate the rpc.json with alchemy URLs
see corresponding [abacus PR](https://github.com/dydxprotocol/v4-abacus/pull/519)

chore: generate rpc.json with both alchemy and viem RPC urls

---

package.json
pnpm-lock.yaml
src/lib/errors.ts
src/views/forms/AccountManagementForms/WithdrawForm.tsx

This PR does 2 things:
1. Upgrades abacus. This gives us the `no multi tx` flag in the withdrawals route which will prevent the FE from allowing users to attempt a multi tx route (base + polygon CCTP would fall under this category). We want to prevent this because abacus only handles a single tx. this would cause our users' funds to just go into noble and be swept back, or in the worst case scenario be stuck completely and require help from skip to retrieve.
2. Replaces base message of `"no single-tx routes found, to enable multi-tx routes set allow_multi_tx to true"` which would be very confusing to the end user for a more user friendly `'This route is not yet supported, please check back soon as we are adding new routes.'`
Ideally we do the error message overrides in abacus but:
1. it's …

feat: bump abacus + error message overrides

---

src/constants/abacus.ts
src/state/inputsSelectors.ts
src/views/CanvasOrderbook/CanvasOrderbook.tsx
src/views/forms/TradeForm.tsx
src/views/forms/TradeForm/PlaceOrderButtonAndReceipt.tsx

During close position, the `selectedTradeType` is not correctly set to `MARKET` by abacus, instead the `MARKET` type is hardcoded when a close position order is placed.
During close only we are checking for `selectedTradeType` which is inaccurate, so we want to check for the current input type to see if it is also `closePosition`

fix(compliance): during close only, check for close position form for place orders

---

src/hooks/Orderbook/useDrawOrderbook.ts

per thread [here](https://dydx-team.slack.com/archives/C06EMK1746T/p1720469178664289?thread_ts=1720204777.641659&cid=C06EMK1746T), following changes have been made:
- Only show highlight when level is removed; do not show highlight when price level changes in size (previously used highlight animation when price level changed in size, not when level was removed)
- Remove dimming animation on the text
See .mov below comparing before (left) and after (right)
https://github.com/user-attachments/assets/fa628fa6-dd7e-4ac2-9f80-9cf7e9900ba1

fix(orderbook): update orderbook animations to be less distracting

---

src/views/charts/DepthChart/index.tsx

Updated so that x axis always renders with `tickSizeDecimals` precision
- Had to tweak `numTicks` from `5` -> `4` to make the lowest price markets work (to not have the numbers overlap)
- I think this is the easiest solution rn 🤔 tho open to other ideas
https://github.com/user-attachments/assets/877303ce-b3b8-4f9b-be65-0aaaadda517e
---
* `DepthChart`
* Updated number formatting function
* I'm unsure when zoomDomain is ever > 500 (couldn't make it happen through manual scrolling), solution seems to work for everything from lowest (MOG) to highest price markets (BTC)

fix(depthchart): fix x axis of depth chart for prices < 1

---

src/views/dialogs/MnemonicExportDialog.tsx
src/views/dialogs/MobileSignInDialog.tsx

Suppress the following data from hotjar
- wordlist for recovery phrase
- qrcode + encryption key for mobile login
For `privy email + phone number`:
- privy only has an email input (unless i'm missing something?)
- we don't have any control over the privy modal, deployers will just have to [update their hotjar settings to not record on email inputs](https://help.hotjar.com/hc/en-us/articles/115012439167-How-to-Suppress-Text-Images-Videos-and-User-Input-from-Collected-Data#site-wide)

chore: suppress data from hotjar [OTE-524]

---

src/components/PortfolioCard.tsx
src/constants/errors.ts
src/constants/orderbook.ts
src/hooks/useNotificationTypes.tsx
src/pages/trade/Trade.tsx
src/pages/trade/UnopenedIsolatedPositions.tsx
src/styles/constants.css
src/styles/tradeViewMixins.ts
src/views/CanvasOrderbook/CanvasOrderbook.tsx
src/views/CanvasOrderbook/OrderbookControls.tsx
src/views/CanvasOrderbook/OrderbookRow.tsx
src/views/forms/TradeForm/TradeSizeInputs.tsx

1. reduce horizontal panel (i.e. position table etc.) height on all screen sizes
2. reduce vertical padding on `Tabs` and horizontal tables i.e. positions/orders/fills table
3. a little more height on isolated positions so it doesn't scroll weirdly
4. reduce orderbook row height
5. update orderbook/trade layout to take up more height if laptop size is wide; remove some borders from orderbook since they no longer match up

chore: update layout + padding on trade

---

src/constants/dialogs.ts
src/lib/abacus/logger.ts
src/views/dialogs/SharePNLAnalyticsDialog.tsx
src/views/tables/PositionsTable.tsx
src/views/tables/PositionsTable/PositionsActionsCell.tsx

Old Card (Percent):
New Card (Dollar amount):

chore: change pnl card to use fiat instead of percent [OTE-511]

---

src/constants/analytics.ts
src/hooks/useAnalytics.ts
src/lib/analytics.ts

context: https://dydx-team.slack.com/archives/C03JV4VJQ6N/p1716565422932799
manually setting a domain referrer since the one automatically it often returns none.
This will help us know if a domain referrer is simply not being provided or if a race condition/setting is causing amplitude to fail to capture this.
also removes the `referrer` event property for 2 reasons:
1. it tracks utm_source, which amplitude already tracks
2. it has no business being an event property. even if we want to add this back at some point it should be as a user property

chore: manually assign custom domain referrer [OTE-516]

---

package.json
pnpm-lock.yaml

https://github.com/dydxprotocol/v4-abacus/pull/529/
- this should fix accounts with multiple active parent subaccounts seeing empty equity when switching to isolated margin mode + stop autosweeping funds from those accounts

fix: include abacus bump for multiple parent subaccounts fix

---

src/constants/numbers.ts

bump min amount to 11 
context: https://dydx-team.slack.com/archives/C06ETDBE370/p1721406945614009?thread_ts=1721400846.467719&cid=C06ETDBE370
users are seeing their transfers fail because the relayer minimum CCTP amount is slightly higher than the amount they're sending

chore: update min cctp amount

---

package.json
pnpm-lock.yaml
src/constants/localization.ts
src/constants/trade.ts
src/hooks/useNotificationTypes.tsx
src/hooks/useSubaccount.tsx
src/lib/abacus/dydxChainTransactions.ts
src/lib/errors.ts
src/state/account.ts
src/state/localizationSelectors.ts
src/views/forms/AdjustIsolatedMarginForm.tsx
src/views/forms/CancelAllOrdersInMarketForm.tsx
src/views/forms/ClosePositionForm.tsx
src/views/forms/TradeForm.tsx
src/views/forms/TradeForm/PlaceOrderButtonAndReceipt.tsx
src/views/notifications/OrderCancelNotification.tsx
src/views/notifications/OrderStatusNotification.tsx

context: it's possible that the stringkey we pass from Abacus might not exist in localization, since we aren't translating protocol errors 1:1. [example](https://github.com/dydxprotocol/v4-abacus/blob/de7b8170aec72008d02dac0656085e7c2c82466e/src/commonMain/kotlin/exchange.dydx.abacus/state/app/adaptors/V4TransactionErrors.kt#L17). other than just translating all error codes and catching all possible query results (which is not sustainable), we should fallback to show some error message that is relevant
- correctly serialize transaction errors via `stringifyTransactionError`, because when a normal Error is thrown (e.g. query update failure), JSON.stringify will not work
- update functions that takes in `errorStringKey?: string` to `errorParams?: ErrorParams`, the latter includes a …

feat: unsupported transaction error fallback

---

src/pages/portfolio/Fees.tsx

fix: fee tier market share percentage should show 1 decimal

---

src/hooks/Orderbook/useDrawOrderbook.ts

Chatted with product [here](https://dydx-team.slack.com/archives/C06EMK1746T/p1721407912354539?thread_ts=1720204777.641659&cid=C06EMK1746T); we want to remove the size bar in our orderbook gradients and only keep the depth bar.
Could've further simplified the drawBars function but thought it might be nice to keep the `gradientMultiplier` configuration in case we want to tweak it in the future 🤷‍♀️ 
- I don't feel strongly so happy to just convert the `1.3` to a constant at the top of the file if others think that's better 
| before | after |
| <img width="314" alt="Screenshot 2024-07-23 at 2 12 32 PM" src="https://github.com/user-attachments/assets/fe03b3bc-7aad-463d-80ad-97e86942f3b5"> | <img width="323" alt="Screenshot 2024-07-23 at 2 12 25 PM" …

chore(orderbook): remove size gradient from orderbook

---

src/hooks/useNotificationTypes.tsx

pulls out change from https://github.com/dydxprotocol/v4-web/pull/809 which is going out later than I expected. Context is when I originally wrote this code, I couldn't count // notification should only last a month, and I accidentally set it to 2 months
will rebase that PR once this gets in

chore: update staking notification expiration date

---

package.json
pnpm-lock.yaml
src/constants/__test__/cctp.spec.ts
src/constants/abacus.ts
src/constants/cctp.ts
src/views/forms/AccountManagementForms/DepositForm/DepositButtonAndReceipt.tsx
src/views/forms/AccountManagementForms/HighestFeesText.tsx
src/views/forms/AccountManagementForms/RouteWarningMessage.tsx
src/views/forms/AccountManagementForms/SourceSelectMenu.tsx
src/views/forms/AccountManagementForms/WithdrawForm/WithdrawButtonAndReceipt.tsx

blocked by: https://github.com/dydxprotocol/v4-abacus/pull/540
If we receive a warning from skip from the `msgs_direct` api, we pass that warning onto the user and gate withdrawals until they click a checkbox saying they acknowledge the warning.
The warning we expect to see is typically about transfer fees being very high.
This is designed to prevent users who aren't pay attention to the receipt from losing funds unnecessarily
We also update the copy in the source select dropdown to warn users for high fees on ethereum
https://www.loom.com/share/5e388ab7b5f24e3b8ef1896717e39590?sid=41cf5310-6a2e-4ffa-b902-5f65c5c6633f
NOTE: had to mock a route warning since i  couldn't trigger a real one, so excuse the jankiness
https://www.loom.com/share/0eefc97cba4744faa3d2f08a024f7d13?sid=1df2cd7e-43e1- …

feat: warning for high fees [OTE-621]

---

.ladle/components.tsx
src/components/Tag.stories.tsx
src/components/Tag.tsx
src/components/ToggleGroup.tsx
src/constants/markets.ts
src/hooks/useMarketsData.ts
src/layout/Header/HeaderDesktop.tsx
src/pages/token/LaunchIncentivesPanel.tsx
src/views/MarketFilter.tsx
src/views/MarketsDropdown.tsx
src/views/MarketsStats.tsx
src/views/tables/MarketsCompactTable.tsx

Market Page
Market Dropdown
Add `Prediction Market` filter to `<MarketFilter>` component.
---
* `<MarketFilter>`
* Add gradient fade to scrollable area so users know it is scrollable.
* Utilize ToggleGroup.item `slotAfter` to render `<NewTag>` based on `MARKET_FILTER_OPTIONS`
* `<MarketDropdown>`
* Add disclaimer when on Prediction Market Filter 
* `<Component>`
* Remove unnecessary providers from base `ladle` component to fix component story environment.
* New: `<NewTag>`
* Add NewTag component and story component
* Update usage in `HeaderDesktop`, `LaunchIncentivesPanel`, `MarketStats`, and `MarketCompactTable`
* `<ToggleGroup>`
* Add usage of `slotAfter` prop for ToggleGroup.Item
* Update `MARKET_FILTER_LABELS` -> `MARKET_FILTER_OPTIONS` to support `isNew` prop
* …

feat(add-filter): Prediction Market filter

---

src/components/ComboboxMenu.tsx
src/components/Input.tsx

https://dydx-team.slack.com/archives/C06ETDBE370/p1722267871599219
hotjar blocks text input tracking by default. we are enabling it on all available inputs by adding the `data-hj-allow` property on `input` tags
NOTE: we will need to do the same when/if we add textarea tags

chore: add data hj allow to inputs [OTE-639]

---

public/configs/cctp.json
src/constants/__test__/cctp.spec.ts

re adds base and polygon USDC as cctp assets. these are the biggest offenders of no route found errors. 
we can release. this as soon as skip is stable on mobile

feat: readd base and polygon as cctp [OTE-655]

---

.github/workflows/deploy-testnet.yml
README.md
package.json
scripts/README.md
scripts/inject-google-tag-manager.js

adds google tag manager script. relies on env var GOOGLE_TAG_MANAGER_CONTAINER_ID.'
followed steps outlined here: https://support.google.com/tagmanager/answer/14847097?hl=en&ref_topic=15191151&sjid=3001289320793576310-NA
Tough to QA this - for build time scripts, env vars need to be injected via github secrets

chore: inject google tag manager script [OTE-632]

---

src/components/DropdownSelectMenu.tsx
src/hooks/useSelectedNetwork.ts
src/views/menus/NetworkSelectMenu.tsx

Disable the NetworkSelectMenu and hide the dropdown icon when there is only one supported network.
---
* `<NetworkSelectMenu>`
* disable the dropdown if 1 available environment
* `<DropdownSelectMenu>`
* Introduce prop to hide the caret icon
* `hooks/useSelectedNetwork`
* add side-effect to set your network to the default if the `selectedNetwork` from localStorage is invalid. (Necessary to add the side effect because the dropdown will be disabled)
---

chore(network-selector): disable network-selector if only 1 network

---

src/constants/candles.ts
src/lib/abacus/websocket.ts
src/lib/testFlags.ts
src/lib/tradingView/utils.ts

This change takes in the new `orderbookMidPrice[Open/Close]` data returned from indexer and optionally uses it to render the candles if:
- there are no trades in that candle 
- (to be removed after done testing in a subsequent PR) ohlc is enabled (as a url testing param)
- Used a new ohlc url param flag instead of the existing OHLC flag from env.json because checking that requires a hook which is not available in `mapCandle`
- It is intentional that this change does not check if the OHLC toggle is on/off from the chart
- We'd like to release this change before the OHLC toggle part (because it's sig easier)
- Known bug that we sometimes have trailing decimal points (rip floating point precision) in `orderbookMidPrice[Open/Close]`; BE is working on fixing that 
- This one was sort of …

feat(ohlc): enable ohlc for all markets

---

public/configs/v1/env.json
src/constants/notifications.ts
src/hooks/useEnvFeatures.ts
src/hooks/useIncentivesSeason.ts

Removes `seasonFiveIncentivesDistributed` flag (I'd like to remove these flags as soon as they're not needed so merging the `env.json` is less confusing for others).
Testing:
- built locally, small modification to show even if rewards = 0 just for testing
---
* `constants/notifications.ts`
* Remove `IncentivesDistributedNotificationIds.IncentivesDistributedS4`  (no longer used) 
* `hooks/useEnvFeatures`
* remove `seasonFiveIncentivesDistributed` from `EnvironmentFeatures`
* `hooks/useIncentivesSeason`
* remove check of `seasonFiveIncentivesDistributed` (assume is true)
* add comment referencing how to easily update again for subsequent seasons
* `env.json`
* Remove `seasonFiveIncentivesDistributed`
---

chore(incentives): remove season 5 notification distribution flag

---

src/components/Tabs.tsx
src/constants/orderbook.ts
src/hooks/Orderbook/useDrawOrderbook.ts
src/hooks/Orderbook/useOrderbookValues.ts
src/pages/trade/VerticalPanel.tsx
src/views/CanvasOrderbook/CanvasOrderbook.tsx
src/views/forms/TradeForm.tsx

try #2 which is 100x simpler than my last thing I was trying cuz I think my brain was non functional the first round
Goal: To make the orderbook not scrollable (fixed height-ish) while still maintaining the reponsiveness of the screen sizing:
We still want the orderbook to grow when the height of the screen grows
We still want the whole page to fit on any (reasonably sized) screen without scrolling
We want the orderbook to be just large enough to show x rows, centered such that the price row is in the middle
Solution: 
1. Calculate the approximate size of the div of the canvas orderbook
2. Calculate the number of rows we can render in this div
3. Recalculate when browser or div resizes (latter happens without browser resizing if we just zoom in/out) using resizeObserver
EDIT: used …

chore(orderbook): update orderbook to not be scrollable

---

src/hooks/useAccountBalance.ts

There was bug where the user can not see their token balance unless they switched network first. Fix this by passing in the chainId to `useReadContracts`
https://github.com/user-attachments/assets/d268661d-ce6c-4bbb-b71a-d530f38f26a7

fix: fetch balance without switch network

---

src/views/AccountInfo/AccountInfoConnectedState.tsx

before
after
- when order flips position when reduce only is checked, post order account margin usage isn't calculated so it'll also fail "INVALID_NEW_ACCOUNT_MARGIN_USAGE", which is why there's an error icon next to cross margin usage
- however this is confusing because we don't surface anything on the FE that suggests there's any margin usage being calculated / or why it's invalid. so updating to only surface that error when it's the first validation error (i.e. what we're surfacing in the alert / cta)
- the two errors returned in this condition are 1. "ORDER_WOULD_FLIP_POSITION", 2. margin usage error
- opted to not update abacus logic to skip margin usage error when there's a invalid reduce only state since we should just take advantage of the defined error ordering (i.e. error code)

fix: CT-1060 only show margin usage error icon when most relevant error is relate to margin usage

---

src/views/tables/PositionsTable.tsx

This PR updates the USD value of position sizing in trade/portfolio position tables to be 2 decimals.

feat: round USD values in position size to 2 decimals [CT-992]

---

package.json
pnpm-lock.yaml

bump abacus version to get:
- https://github.com/dydxprotocol/v4-abacus/pull/550
- filter out non EVM chains
- sorts native asset as first item after usdc asset if applicable
- https://github.com/dydxprotocol/v4-abacus/pull/560
- filters our USDT assets
- https://github.com/dydxprotocol/v4-abacus/pull/553
- don't trigger compliance on geo change

feat: bump abacus version

---

src/views/CanvasOrderbook/CanvasOrderbook.tsx

chore: improve orderbook spacing to not look cutoff

---

src/App.tsx
src/constants/dialogs.ts
src/hooks/useCommandMenu.ts
src/layout/DialogManager.tsx
src/views/dialogs/GlobalCommandDialog.tsx

To add logging for our cmd k dialog, update `GlobalCommandDialog` to be opened in the same way as our other dialogs (with `dispatch(openDialog)`).
- Would ideally like to be able to also record if help / display preferences / etc dialogs are being opened from cmd + k (instead of preferences), will follow up in separate PR for this
---
* `GlobalCommandDialog`
* Remove local state of being open/closed and use `setIsOpen` from `DialogManager`
* `DialogManager`
* Add `GlobalCommand` dialog navigation
* `App`
* Instead of always rendering `GlobalCommandDialog` component, simply call `useCommandMenu` hook which attaches event listener for cmd+k
* `constants/dialogs.ts`
* Add `GlobalCommand` dialog type
* `hooks/useCommandMenu`
* Update to determine if dialog is open by reading from …

chore(analytics): update cmd k menu to use dialog logging

---

src/lib/language.ts
src/state/localizationMiddleware.ts

during locale initialization, we should just always set locale regardless of whether `globalThis.navigator?.language` exists. this will just default to English and won't affect existing behaior.
also update browser language detection logic to match amplitude (since somehow they always have a language property while we seem to miss since `selectedLocale` was empty for many users)

chore: always set selectedLocale and match amplitude language detection

---

src/constants/analytics.ts
src/hooks/useAnalytics.ts

`fromDialogType` is undefined when the dialog is not opened from an existing open dialog
https://github.com/user-attachments/assets/8a3741f4-a07c-4ab0-94da-5c34780b94c5

chore(analytics): add fromDialogType to NavigateDialog events

---

src/constants/analytics.ts
src/lib/analytics.ts
src/views/dialogs/AcknowledgeTermsDialog.tsx
src/views/dialogs/OnboardingDialog/GenerateKeys.tsx
src/views/dialogs/OnboardingTriggerButton.tsx
src/views/forms/AccountManagementForms/DepositForm.tsx

According to the doc: https://www.notion.so/dydx/v4-conversion-funnel-events-32465e38f3704b4f973d586f3da7c2da#b3f64fb5942f41a8b9a73e0958a2e5ff
Clicked "Connect Wallet": `OnboardingTriggerClick`
Clicked "Send Request": `OnboardingSendRequestClick`
- also flags first attempt, because failures will result in the `Try Again` button instead. We can track if users are getting there
Clicked “Sign” (first time): `OnboardingDeriveKeysSignatureReceived`
- has a `signatureNumber` property to track whether it's the first or second signature. Opted to not use a `firstAttempt` flag since users are not attempting but may potentially (in the future) have N number of signatures they need to sign
Clicked “Sign” (second time): Same as above
Clicked “I agree”: `OnboardingAcknowledgeTermsButtonClick`
- has …

chore: add support for missing dydx onboarding analytics [OTE-645]

---

package.json
pnpm-lock.yaml
src/App.tsx

See https://styled-components.com/docs/faqs#shouldforwardprop-is-no-longer-provided-by-default
I misread this part of the release notes and thought it was about features we don't use.

fix: styled pass through props changed in v6

---

src/constants/analytics.ts
src/hooks/useAnalytics.ts

adds geo as a user property. enables analytics to track various things such as whether or not users are part of restricted geos
https://dydx-team.slack.com/archives/C06ETDBE370/p1722353625082109

chore: add user geo as user property [OTE-667]

---

package.json
pnpm-lock.yaml
src/hooks/tradingView/useChartLines.ts
src/lib/tradingView/utils.ts

and pull in localization changes (unrelated).
---
| Before | After | 
| <img width="898" alt="Screenshot 2024-08-09 at 1 33 25 PM" src="https://github.com/user-attachments/assets/c683470e-2787-4633-b105-9f5091f779a9"> | <img width="897" alt="Screenshot 2024-08-09 at 1 34 08 PM" src="https://github.com/user-attachments/assets/3bc4db55-db6f-4f8d-9756-f3d1aec05f83"> |
* `lib/tradingView/utils.ts`
* added `custom_font_family`, copied from `--fontFamily-base` in `text.css`
* add `scalesProperties.fontSize`
* `hooks/useChartLines`
* set font to Satoshi for lines drawn
* updated: v1.1.170 -> v1.1.171
---

chore(tradingview): update tradingview chart font to satoshi

---

src/components/Input.tsx

adds hotjar text to the NumericFormat input option for the `Input` component.

fix: missing hotjar text [OTE-675]

---

src/views/AccountInfo/AccountInfoConnectedState.tsx

hide diff state when available balance is going to be negative
before:
after:

chore: hide diff state for account available balance when its negative

---

src/views/forms/TradeForm/PlaceOrderButtonAndReceipt.tsx

when fields are filled (e.g. missing amount), don't show warning icon since they are not important error validations
alternative is to introduce another warning level or check error code (starts with REQUIRED) -- but using existing best guess with `areInputsFilled` also work

chore: hide warning icon in place order CTA when missing fields

---

src/constants/notifications.ts
src/hooks/useNotifications.tsx
src/lib/notifications.ts

issue:
- abacus fill notifications (when a fill is deleveraged/ final settlement, liquidated, offsetting) are being triggered every time user lands on web app
- store them like a non single session notif type so they can be properly seen/hidden/cleared
- not doing this for orders since we don't really fetch order history and they happen much more often (i.e. every fill)
repro'd with https://v4.stage.dydx.exchange/trade/ETH-USD?address=dydx1lagu6a2lkpwqe3ekv0078h5zvxulhsj6rfas42
dydx1lagu6a2lkpwqe3ekv0078h5zvxulhsj6rfas42 has tho notifs

fix: store abacus fill notifs so they are properly stored and not retriggered

---

package.json
pnpm-lock.yaml
src/hooks/useStatsig.tsx
src/lib/__test__/index.spec.ts
src/lib/abacus/index.ts
src/types/statsig.ts

enable evm swap deposits by piping in the new `ff_enable_evm_swaps` feature gate
also automatically adds new statsig flags to the statsig config object

feat: evm swap deposits [OTE-700]

---

public/configs/v1/env.json
src/hooks/tradingView/useTradingView.ts
src/hooks/useEnvFeatures.ts

Remove `isOhlcEnabled` flag, clean up an unnecessary check against toggle refs being null in `useTradingView`

chore(ohlc): enable orderbook mid price candles across all envs

---

public/configs/v1/env.json

Use the new API proxy with client-dedicated CORS setup.

chore: Use new URL for Apybara API proxy in testnet

---

scripts/inject-smartbanner.js
src/index.css
src/styles/constants.css

https://linear.app/dydx/issue/OTE-711/[v4-web]-cant-close-custom-app-store-banner
cant close the custom app store banner. this is a test PR to see if override styles works
this PR targets the smartbanner default ios class and pushes its z-index to 999, placing it above all dydx app banners and modals

fix: ensure smartbanner is clickable [OTE-711]

---

src/constants/errors.ts
src/constants/wallets.ts
src/hooks/useWalletConnection.ts
src/lib/wallet/index.ts
src/views/dialogs/OnboardingDialog/ChooseWallet.tsx

https://linear.app/dydx/issue/OTE-662/when-receiving-this-see-description-error-from-metamask-display-this
Override base error message from metamask error by:
- creating MetamaskErrorCodes enum (to track further metamask errors)
- creating DydxError class to enable more flexible error properties
- piping in error.code when receiving an unexpected error from the walletconnect
- add MetamaskErrorCodes.RESOURCE_UNAVAILABLE as a return type for the `getWalletErrorType` function
- create `getErrorMessageForCode` which **defaults to the given error message** and use that for the error message catchall
Followup thoughts:
we should maybe in the future create a MetamaskErrorHandling function. Right now there's like 4-5 layers of indirection to 
get the error which is kind of a lot for something …

chore: better metamask error message [OTE-662]

---

src/App.tsx
src/components/NavigationMenu.tsx
src/constants/routes.ts
src/hooks/useLaunchableMarkets.ts
src/layout/Header/HeaderDesktop.tsx
src/lib/testFlags.ts
src/pages/LaunchMarket.tsx
src/views/forms/NewMarketForm/index.tsx
src/views/forms/NewMarketForm/v7/NewMarketPreviewStep.tsx
src/views/forms/NewMarketForm/v7/NewMarketSelectionStep.tsx

Launch Market page
- Set-up app routes for `/launch-market` url
- Scaffold NewMarketPreview and NewMarketSelection forms
---
* New `<LaunchMarket>`
* add new page
* rough scaffold of components on page
* New `<NewMarketPreviewStep>` and `<NewMarketSelectionStep>`
* Rough scaffold of brand new forms in the `v7` directory (protocol support version)
* `<HeaderDesktop>`
* add `Launch Market` item behind testFlag
* `<App>`
* Add new route behind testflag and redirect `/markets/new` -> `/launch-market`
* `<NewMarketForm>`
* add new components under `pml` flag
* add hook to get receipt items since receipts are shared on two forms
* `<NavigationMenu>`
* `white-space: nowrap` for nav items
* `constants/routes`
* add new route
* `lib/testFlags`
* add `pml` testflag
* `hooks/useLaunchableMarkets`
* …

feat(pml-launcher): Add route and scaffold new forms under testflag

---

package.json
pnpm-lock.yaml
src/views/forms/ClosePositionForm.tsx

post abacus bump set full close as default (i.e. percent = 1), therefore we can remove that call
also add a 10% option since that was a request a while back and it's ez to add now
testing: 
- close a position / switch to another market during close position and observe that full close is selected, and size / diff state should reflect that
- select 10% option

chore: close position 10% option + bump abacus

---

src/hooks/useComplianceState.tsx

The `complianceMessage` was not being memo-ized leading to a non-stop rendering of the compliance notification, which was eating up a lot CPU when website is in user restricted area.
Memoize the `complianceMessage` to fix this.

fix: memoize compliance string

---

src/components/Dialog.tsx

check dialog with dropdown menus in Trade page
rest of dialog should have the right cursor / behavior when having the menu open

fix: set pointer events to auto in dialog to fix behavior when theres another layer

---

src/lib/abacus/dydxChainTransactions.ts

this should skip 2 round trip calls for getting market info and block height. 
abacus already has that info from fetched markets info and polled/estimated block height
- latter could potentially increase risk of some errors related to GTB, but will monitor next week
```
* @param marketInfo optional market information for calculating quantums and subticks.
*        This can be constructed from Indexer API. If set to null, additional round
*        trip to Indexer API will be made.
* @param currentHeight Current block height. This can be obtained from ValidatorClient.
*        If set to null, additional round trip to ValidatorClient will be made.
```
https://github.com/dydxprotocol/v4-clients/blob/56d8c2deacffd97eb70343b2904ac94f4c91d242/v4-client-js/src/clients/composite-client.ts#L342-L346 …

fix: place order tx should use marketInfo and currentHeight from abacus payload

---

src/components/Button.tsx

the stuff that bothers me // unsure if this is a personal preference but I'm pretty sure this looks better centered??
| before | after |
| <img width="1512" alt="Screenshot 2024-08-23 at 1 41 27 PM" src="https://github.com/user-attachments/assets/6789521d-17de-4d17-a2d1-23213a607510"> | <img width="1512" alt="Screenshot 2024-08-23 at 1 40 31 PM" src="https://github.com/user-attachments/assets/bd6b72a1-eab6-4c6f-8f5f-267b0ce1f06d"> |

fix: fix uncentered loading button

---

package.json
pnpm-lock.yaml
src/layout/Header/HeaderDesktop.tsx
src/pages/LaunchMarket.tsx
src/views/charts/LaunchableMarketChart.tsx
src/views/forms/NewMarketForm/index.tsx
src/views/forms/NewMarketForm/v7/NewMarketPreviewStep.tsx
src/views/forms/NewMarketForm/v7/NewMarketSelectionStep.tsx

- Clean up and localization of PML widget
---
* New: `<LaunchableMarketChart>`
* Small visualization of important details of a Launchable Markets. Also includes a price chart.
* `<LaunchMarket>`
* Localize page and move some elements to a new component: `LaunchableMarketChart`
* Remove hardcoded copy and  localize all other views
* Add PML strings
* updated: v1.1.177 -> v1.1.182
---

chore(i18n): localize PML Widget

---

src/lib/tradingView/utils.ts

This hides the right toolbar which shows the "Object tree" menu by default. Unfortunately it doesn't look like there's a way to only hide it by default but still make it expandable, but I think hiding it is better than showing it for now 🙏

fix: hide right toolbar in TradingView

---

package.json
pnpm-lock.yaml
src/lib/tradeData.ts
src/views/forms/ClosePositionForm.tsx
src/views/forms/TradeForm.tsx

for https://github.com/dydxprotocol/v4-abacus/pull/601
also add in logic to read in `link` and `linkText` returned by abacus errors.

chore: bump abacus for min isolated margin validation

---

src/hooks/useNotificationTypes.tsx

(time is correct given my current time zone)

fix(notif): update matic wind down date

---

src/lib/addressUtils.ts
src/views/forms/AccountManagementForms/WithdrawForm.tsx

This PR updates the logic to combine the `isValidAddress` check for both evm and noble to be in the same place. And removes the logic to only validate cosmos addresses if the user is connected to Keplr.

fix: validate withdraw form address by destination type instead of wallet type

---

src/views/forms/AccountManagementForms/SourceSelectMenu.tsx

Only phantom wallet supports solana as a deposit option

feat: filter out solana chain for other wallets

---

src/views/MarketsDropdown.tsx

| Before | After |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/23a3eb42-8f0c-4cf0-ba06-4c381fcf55ed) | <img width="422" alt="Screen Shot 2024-08-30 at 1 11 12 PM" src="https://github.com/user-attachments/assets/65690349-96e2-4374-a69f-bcd74dac2151"> |
Add additional space to the MarketsDropdown so tickers do not wrap.
---
* `<MarketsDropdown>`
* Remove `All Markets` label
---

style(marketDropdown): remove label

---

src/lib/wagmi.ts

This PR disables using smart wallets through Coinbase's wallet connector.
|Before|After|
|------|------|
|<img width="461" alt="image" src="https://github.com/user-attachments/assets/0cef5fd1-edcf-42ac-8095-fc9368df185e">|<img width="479" alt="image" src="https://github.com/user-attachments/assets/59e77455-b0e5-44ab-b923-8cb24dd5fa39">|
^^ Note these only show up if the user doesn't have the extension wallet installed.

feat: disable coinbase smart wallet

---

package.json
pnpm-lock.yaml
src/components/Table.tsx
src/hooks/useSubaccount.tsx
src/lib/abacus/index.ts
src/lib/testFlags.ts
src/state/account.ts
src/state/accountCalculators.ts
src/views/tables/OrdersTable.tsx
src/views/tables/OrdersTable/CancelAllOrdersButton.tsx
src/views/tables/OrdersTable/CancelOrClearAllOrdersButton.tsx

cancel all orders - 'cancel all' button to replace 'action' in orders table
full feature should have the following ux flow:
- user clicks 'cancel all' -> opens dialog for confirmation -> select cancel all orders under current market, or cancel all orders in all markets -> confirm to cancel -> show notification for canceling orders: 1/N canceled...
breaking this feature into a couple PRs for easier review; this one adds the MVP for testing functionality
- add cancel all button
- clicking should cancel all orders, or only orders under current market if toggle is set to current market
- no notifications
feature gated by `cancelall` flag for product testing / broken PRs
testing: 
- add ?cancelall=1 to the end of url
- open some limit orders in different markets
- close all under one market
- …

feat: [1/n] cancel all orders mvp

---

src/constants/notifications.ts
src/constants/statsig.ts
src/hooks/useIncentivesSeason.ts
src/hooks/useQueryChaosLabsIncentives.ts
src/pages/token/LaunchIncentivesPanel.tsx

statsig ff: ff_incentives_s6_rewards_distributed; rollout on 9/13 530pm or just launch that time
https://cloud.chaoslabs.co/query/api/dydx/points/dydx15m3lvgfwe4xad7wqyskvn6qz5w5ahue60hhemn?n=1
(20437417.331058+86389756.838196+85323598.369674+70796421.080448+78327052.52252999)
(this will show up when rewards > 0; im just changing this locally)

chore: update s6 notification w/ statsig + show total rewards

---

.husky/pre-push

sometimes, rarely, commits sneak into PR's unsigned. this is annoying https://dydx-team.slack.com/archives/C06S9ND5T40/p1725897065808209
quick script to prevent this from happening

chore: prepush commit signing

---

src/hooks/useWalletConnection.ts

This bug was introduced because I removed a flow that extraneously wrote from `selectedWallet` ->`connectedWallet` state, and the address override reads from `connectedWallet`, which is why setting the test wallet through `selectedWallet` worked before. But we can just write directly to `connectedWallet` in this case.

fix: address impersonation

---

src/components/Table/AssetTableCell.tsx
src/constants/markets.ts
src/hooks/useMarketsData.ts
src/views/tables/MarketsCompactTable.tsx
src/views/tables/MarketsTable.tsx

Refactor `type market`. This is necessary in order to add unlaunched markets to our `useMarkets` hook from `x/marketmap` since it is outside of Abacus.
---
* `<MarketsTable>`, `<MarketsCompactTable>`
* Update props passed to `<AssetTableCell>`
* `<AssetTableCell>`
* Update props to include `symbol` and `name` instead of taking Abacus' `Asset` type
* update `type Market`
* `hooks/useMarketsData`
* Update to be compatible with new `type Market`
---

refactor(market-type): update market interface for useMarkets hook

---

src/constants/notifications.ts
src/hooks/tradingView/useChartLines.ts
src/hooks/useCustomNotification.ts
src/hooks/useNotificationTypes.tsx
src/lib/orderModification.ts
src/state/notifications.ts
src/state/notificationsSelectors.ts

This PR introduces a new way to fire one-off notifications and its first example usage is for the error notification when you're modifying an order from the TV chart with an invalid price.

feat: Custom notifications and order modification price validation

---

src/lib/tradingView/dydxfeed/cache.ts
src/lib/tradingView/dydxfeed/index.ts
src/lib/tradingView/dydxfeed/streaming.ts
src/lib/tradingView/utils.ts
src/views/LaunchMarketSidePanel.tsx
src/views/dialogs/NewMarketAgreementDialog.tsx
src/views/forms/NewMarketForm/NewMarketAgreement.tsx
src/views/forms/NewMarketForm/v7/NewMarketPreviewStep.tsx

Pull NewMarketAgreement into a separate `view` to be used in Dialog and directly in `v7/NewMarketPreviewStep`.
---
* New: `<NewMarketAgreement>`
* Add Agreement form to it's own view
* `<NewMarketPreviewStep>` , `<NewMarketAgreementDialog>`
* Use `<NewMarketAgreement>` view
| Old flow | New flow |
|---|---|
| <video src="https://github.com/user-attachments/assets/319a413a-fa47-42c4-8346-74549c74d9df" /> | <video src="https://github.com/user-attachments/assets/66efc7fe-86c1-4d04-96b3-e3917f10f22b" /> |
* `<LaunchMarketSidePanel>`
* Update copy to use `USDC` icon
* `lib/tradingView/dydxfeed`
* Use `symbol` to index the `lastBarsCache`
* `lib/tradingView/utils`
* update `full_name` to use displayable ticker in the TradingView chart
* <img width="221" alt="Screen Shot 2024-09-12 at 11 17 39 …

refactor(new-market-agreement): add agreement to v7 preview step

---

package.json
pnpm-lock.yaml
src/constants/abacus.ts
src/lib/tradeData.ts

had to pull in updated abacus version for new errorFormat type
| before | after | 
| <img width="346" alt="Screenshot 2024-09-16 at 4 56 56 PM" src="https://github.com/user-attachments/assets/cccfc828-78ee-4e7f-b04e-07ac378f9c16"> | <img width="336" alt="Screenshot 2024-09-16 at 4 56 29 PM" src="https://github.com/user-attachments/assets/77e366a6-ff9a-490d-a24a-a498afbafa87">
|

fix: have 2 sig digs on min isolated margin collateral error

---

src/layout/Header/HeaderDesktop.tsx

fix: fix more nav menu getting blocked by compliance banner

---

src/state/accountSelectors.ts

just some good ol javascript precision rounding errors // should fix [this](https://dydx-team.slack.com/archives/C03GKH23YAZ/p1724834105334999) and [this](https://dydx-team.slack.com/archives/C03GKH23YAZ/p1726594059040329)
ok maybe I could pull out into a public helper for testing purposes but felt like it wasn't super worth testing (issue is mainly that we didn't use our BigNumber library) but if anyone feels strongly I'll do it 🫠 
tested locally by using the vals:
- order.price = 0.0744
- side = "BUY" 
- tickSize = 0.0001
and verifying that the output is 0.0744 instead of 0.0743 (which is what it was before the update)

fix: fix orderbook price bucket rounding issue

---

src/lib/leverage.ts
src/views/forms/AdjustTargetLeverageForm.tsx
src/views/forms/TradeForm/MarketLeverageInput.tsx

| cross 20x | isolated 20x | cross 10x |
| ---- | ---- | ---- | 
| <img width="1268" alt="Screenshot 2024-09-17 at 5 12 49 PM" src="https://github.com/user-attachments/assets/971d5e94-4d12-434e-b68e-e4d812eba880"> | <img width="1041" alt="Screenshot 2024-09-17 at 5 13 03 PM" src="https://github.com/user-attachments/assets/6474479f-d67d-430e-af06-9262678f2398"> | <img width="1269" alt="Screenshot 2024-09-17 at 5 13 20 PM" src="https://github.com/user-attachments/assets/278e2040-8267-40f3-ba62-4bc7e3763f89"> |

chore: update leverage buttons to go up to max market leverage

---

README.md
public/configs/sitemap.json
scripts/__test__/active-market-pairs.test.ts
scripts/generate-sitemap.js
scripts/markets/active-market-pairs.ts

This PR introduces an optional feature - sitemap generation - that can be added as a build step.
The sitemap consists of 2 groups of URLs:
- Static URLs provided in a config file
- URLs for active market pairs, evaluated using an external API.
The market pairs are obtained according to the following rule:
1. Get all the id and pair from [markets/param](https://dydx-ops-rest.kingnodes.com/dydxprotocol/prices/params/market)
2. minus the id that are NOT in STATUS_ACTIVE from [clob/clob_pair](https://dydx-ops-rest.kingnodes.com/dydxprotocol/clob/clob_pair)
The current implementation uses Kingnodes REST API.

feat: Allow dynamic sitemap.xml generation on build

---

src/components/Table.tsx
src/pages/portfolio/Portfolio.tsx

idk why it was 2.75 at any point. tested in:
- TradePage: Positions/Fills/OrdersTable
- TradePage: LiveTradesTable
(only applies to `withFocusStickyRows`). FundingPaymentsTable does not appear to be rendered anywhere so didn't test
Also removed `Payments` route from the `Portfolio` history tab because it's disabled everywhere else
https://github.com/user-attachments/assets/aaf27d82-dce4-40c1-98eb-b840fb4724a3

fix: fix positions table last row being stickied incorrectly

---

src/views/forms/TradeForm/TradeFormInputs.tsx

- good to have feature
- prereq for leverage slider on limit orders
test:
- switch markets / order types; it should set limit price for all limit orders to mid market price on mount when it's available
- (won't automatically sync, but clicking "mid" updates it to the latest mid market price)

feat: prefill limit price input to mid market price when available

---

src/hooks/useAccounts.tsx

without checking for `hasSubAccount`, the hook to set the sol address wouldn't fire after a user reconnected. this caused the withdrawal modal to never trigger a state change (b/c abacus wont fire `transfer` function requests unless a `source` wallet is connected).

fix: solana set for source address

---

src/lib/abacus/index.ts
src/lib/testFlags.ts

since important trade updates are missing with static typing turned on, that makes developing other features difficult :< making this into a test flag instead

chore: use test flag instead for static typing

---

public/configs/markets.json
src/components/SearchInput.tsx
src/constants/markets.ts
src/hooks/useMarketsData.ts
src/views/MarketFilter.tsx

fix: fix markets filter ordering and typo and overflow

---

package.json
pnpm-lock.yaml
src/constants/notifications.ts
src/hooks/useDisplayedWallets.ts
src/hooks/useNotificationTypes.tsx

adds phantom notification
moves phantom to 2nd position
the way we move phantom to the 2nd position is by splicing it into index 1 of the injected wallets list if we detect it.
this will ensure it is either:
- 2nd position (if there is at least 1 other detected injected wallet)
- 1st position (if there are no other detected injected wallets)

feat: phantom noti + positioning

---

package.json
scripts/__test__/active-market-pairs.test.js
scripts/generate-sitemap.js
scripts/markets/active-market-pairs.js

Sitemap generation is run in `node` and using Typescript there causes issues. For this reason this PR rewrites all sitemap generation-related code to Javascript. Additionally it plugs the sitemap generation script into `package.json` and removes some unnecessary console.log statements.

fix: Make sitemap generation JS, not TS, since it runs at build time

---

src/hooks/useTradeFormInputs.ts
src/lib/abacus/index.ts
src/views/forms/TradeForm/TradeFormInputs.tsx
src/views/forms/TradeForm/TradeSizeInputs.tsx

https://linear.app/dydx/issue/CT-1232/fe-doesnt-detect-that-defaulted-limit-price-to-mid-price-is-a-filled
bug: when remember me is not enabled and user is in logged out state (i.e. sees "recover keys" cta), after setting limit price or amount on the trade form and clicking recover keys, none of those values are actually set in abacus.
cause: this is a limitation introduced after isolated markets abacus refactor -- somehow we can't edit input states until there's a proper subaccount. the trade input states we have on FE are not synced to abacus, and there's not really a way to detect when abacus is ready to have their input state be editable.
fix: 
- reset input sizes when account is connected -- so even if user fills an amount, that will just get cleared after recovering keys
- syncs the …

fix: add logic to clear or sync limit order input states to abacus

---

src/hooks/tradingView/useChartLines.tsx
src/hooks/useNotificationTypes.tsx
src/hooks/useOnLastOrderIndexed.ts
src/hooks/useSubaccount.tsx
src/lib/abacus/dydxChainTransactions.ts
src/lib/abacus/stateNotification.ts
src/pages/trade/HorizontalPanel.tsx
src/state/_store.ts
src/state/account.ts
src/state/accountCalculators.ts
src/state/accountSelectors.ts
src/state/localOrders.ts
src/state/localOrdersSelectors.ts
src/views/dialogs/DetailsDialog/OrderDetailsDialog.tsx

motivation: local orders placement/canceling tracking are getting more complicated, before i add close all positions (which has another notification / tracking), refactoring this away from account state so it's clearer what it's doing
changes/ improvements:
- moved local orders state tracking (i.e. placing/canceling order submitted -> confirmed -> filled/canceled/failed) to a new slice `localOrders`
- removed `uncommittedOrderClientIds` tracking because `localPlaceOrders` does kinda the same thing
fixed some bugs:
- `cancelOrderConfirmed`: confirmed a canceling transaction isn't doing what it thinks it's doing -- it's just confirming the transaction went through, but not that the order is confirmed canceled (esp apparent with short term orders). removing this and using indexer as source …

chore: refactor local orders state

---

src/constants/notifications.ts

https://dydx-team.slack.com/archives/C03GKH23YAZ/p1727249969119469
while cleaning up squid code, we updated the [notification type enum value](https://github.com/dydxprotocol/v4-web/pull/1040/files#diff-8241d76f654c8fbfc7a5d8e8e66be6b952adfcd5539b3d1543048cf483c50bf2L8).
this changed the expected caching key which caused the frontend to register all transfers as new notifications.
This caused panic for some users as they saw several unexpected "your withdrawal has been completed" notifications, making them think someone may have drained their account.

fix: revert enum value for skiptransfer

---

public/configs/v1/env.json
src/constants/wallets.ts
src/constants/window.d.ts
src/hooks/useDisplayedWallets.ts
src/hooks/useWalletConnection.ts

sorts wallets according to spec https://linear.app/dydx/issue/OTE-825/sort-for-wallets-show-default-wallets-and
- metamask
- phantom
- keplr
^ these three will go first and default to a download link if the extension isn't already installed
- walletconnect
- coinbase
- email or social (privy)
- coinbase
- okx wallet
- if the okx wallet is not installed, we'll still show the logo and just route it through the walletconnect option. if it is installed, we'll display as part of injected wallets. this isn't exactly how it was outlined in the spec so will want to get confirmation that this is acceptable behavior
https://www.loom.com/share/01711f85a43045fc9e252f91ccf3b352

feat: sort wallets [OTE-825]

---

package.json
pnpm-lock.yaml
src/lib/abacus/dydxChainTransactions.ts

- call the prepopulate account number cache function on setting local wallet
- so we can skip the account number fetch roundtrip when placing order
testing:
setting breakpoints and verifying that this is set (both when remember me is enabled + after connecting wallet)
placing a short term order right away:

feat: add call to prepopulate account cache when local wallet is set

---

.github/workflows/ci.yml
.github/workflows/run-e2e.yml
package.json
src/lib/statsig.ts

Three changes here:
1. We should use `--ignore-scripts` when running `pnpm install`. This helps prevent attacks from contributors directly adding pre/post install scripts to our package.json as well as supply-chain attacks from dependencies.
2. We should never use `pnpm run`. Always inline via `pnpm exec.`
3. An NPM token shouldn't be necessary for simply installing packages.

fix: lockdown e2e workflow

---

package.json
pnpm-lock.yaml
src/views/forms/AccountManagementForms/DepositForm.tsx
src/views/forms/AccountManagementForms/DepositForm/DepositButtonAndReceipt.tsx
src/views/forms/AccountManagementForms/WithdrawForm.tsx
src/views/forms/AccountManagementForms/WithdrawForm/WithdrawButtonAndReceipt.tsx

uses the new state property `estimatedRouteDurationSeconds`

feat: eta in receipt [OTE-831]

---

src/App.tsx
src/hooks/useNotifications.tsx
src/layout/Footer/FooterMobile.tsx
src/layout/NotificationsToastArea/index.tsx
src/views/menus/NotificationsMenu.tsx

hide notifications on mobile web view and add an unread indicator to the mobile footer when applicable
| no new notifs | w/ new notifs |
| <img width="724" alt="Screenshot 2024-09-26 at 3 58 10 PM" src="https://github.com/user-attachments/assets/b692051a-5936-446a-ac1e-4e1f4d9d7576"> | <img width="735" alt="Screenshot 2024-09-26 at 3 57 47 PM" src="https://github.com/user-attachments/assets/cc3df13f-1ddc-4b9b-a3b2-0bbabf04098b"> |

chore: hide notifs on mobile web view

---

src/constants/abacus.ts
src/constants/dialogs.ts
src/constants/trade.ts
src/hooks/useNotificationTypes.tsx
src/hooks/useSubaccount.tsx
src/layout/DialogManager.tsx
src/lib/abacus/index.ts
src/state/localOrders.ts
src/state/localOrdersSelectors.ts
src/views/dialogs/CloseAllPositionsConfirmationDialog.tsx
src/views/notifications/CloseAllPositionsNotification.tsx
src/views/tables/OrdersTable/CancelOrClearAllOrdersButton.tsx
src/views/tables/PositionsTable.tsx
src/views/tables/PositionsTable/CloseAllPositionsButton.tsx

enable "close all" button on positions table that close all positions with market orders
- the functionality is added to abacus, so FE only needs to call that function. market price = oracle price +/- slippage
- it adds tracking similar to cancel all, so we can have a separate toast to keep count of number of positions closed. we'll still emit the fill notifications since they are relevant.
- when a position isn't closed (i.e. order is canceled / not filled), we have a try again option

feat: market close all

---

package.json
pnpm-lock.yaml
src/components/Button.tsx
src/components/GreenCheckCircle.tsx
src/components/Icon.tsx
src/components/SelectMenu.tsx
src/components/Tag.tsx
src/components/ToggleGroup.tsx
src/components/WithLabel.tsx
src/pages/token/StakingPanel.tsx
src/pages/trade/TradeDialogTrigger.tsx
src/pages/vaults/VaultTransactions.tsx
src/styles/layoutMixins.ts
src/views/dialogs/DisplaySettingsDialog.tsx
src/views/dialogs/PredictionMarketIntroDialog.tsx
src/views/dialogs/StakeDialog.tsx
src/views/forms/AccountManagementForms/SourceSelectMenu.tsx
src/views/forms/NewMarketForm/v7/NewMarketPreviewStep.tsx
src/views/forms/StakingForms/shared/StakePreviewContents.tsx
src/views/forms/TradeForm/MarginModeSelector.tsx
src/views/forms/TradeForm/TargetLeverageButton.tsx
src/views/forms/TradeForm/TradeSideToggle.tsx

fixes issues where text is aligned into the middle instead of start (by adding `text-align: start` to `WithLabel` and then some other polishes cuz I went down a rabbit hole:
- Updated icons to have `min-w` and `min-h` in addition to `w` and `h` so that they don't shrink on truncation
- Added text truncation to `Tag`s
- Fixed truncation in `StakingPanel` and `StakeDialog` on long languages
- Localized `Source` and `Destination` on `SourceSelectMenu`
long languages still don't look perfect, but it's getting better

fix: truncation on withdraw dialog

---

src/components/Tag.tsx
src/components/WithLabel.tsx

remove truncation from tags until I have more time to better review all the cases T.T and add back missing spacing between tags and labels

fix: forward fix misaligned tag + label

---

src/hooks/vaultsHooks.ts
src/pages/vaults/VaultDepositWithdrawForm.tsx
src/state/vaults.ts

The debounce change is the one that matters, the new action is just nice to have (and more correct!).

fix: vaults error flickering on submit

---

package.json
pnpm-lock.yaml
src/views/menus/AccountMenu.tsx

| Ethereum | Solana |
|-----------|-------|
|<img width="361" alt="Screenshot 2024-10-01 at 11 58 46 PM" src="https://github.com/user-attachments/assets/702fc7d5-f137-4b91-8634-14bbcfd38224">|<img width="376" alt="Screenshot 2024-10-01 at 11 59 08 PM" src="https://github.com/user-attachments/assets/09d5a259-ec06-4237-903a-a1aca84397cf">|

fix: dydx address tooltip text should match the chain name OTE-845

---

src/components/Accordion.tsx
src/components/DiffArrow.tsx
src/components/IconButton.tsx
src/components/TriangleIndicator.tsx
src/components/WithConfirmationPopover.tsx
src/layout/Footer/FooterMobile.tsx
src/pages/trade/MobileTopPanel.tsx
src/views/AccountInfo/AccountInfoConnectedState.tsx
src/views/dialogs/DisplaySettingsDialog.tsx
src/views/dialogs/MnemonicExportDialog.tsx
src/views/forms/TradeForm.tsx
src/views/tables/OrdersTable/OrderActionsCell.tsx
src/views/tables/PositionsTable/PositionsTriggersCell.tsx

man I added min-height and min-size as part of my truncation PR to prevent icons from shrinking. Thought I caught all the cases of icon sizing, but realized I missed when we were applying custom icon sizing via `svg {}` in css so some of our small icons were being rendered too large due to `min-height: 1em;`. Updated with a quick search of `svg {}`

fix: fix icon sizing

---

src/components/AssetIcon.tsx
src/constants/assetMetadata.ts
src/hooks/useLaunchableMarkets.ts
src/pages/trade/InnerPanel.tsx
src/pages/trade/MobileBottomPanel.tsx
src/views/MarketDetails/CurrentMarketDetails.tsx
src/views/MarketDetails/LaunchableMarketDetails.tsx
src/views/MarketDetails/MarketDetails.tsx
src/views/MarketLinks.tsx

Add `details` pane, on Trade page when viewing a Launchable Market.
---
- `<InnerPanel>`
- Update `InnerPanel` to have a memoized list of items to pass to `<Tabs>`
- `<MarketDetails>`
- create basic market details that will be used in `<CurrentMarketDetails>` and `<LaunchableMarketDetails>` 
- New `<CurrentMarketDetails>` and `<LaunchableMarketDetails>`
- Different data sources that end up being passed to `<MarketDetails>` 
- `<AssetIcon>`
- Add `logoUrl` as a possible prop to accept `s3` link for icon
- `constants/assetMetadata`
- handle API update that returns `self_reported_market_cap`
---

feat(details): Add Launchable market details

---

src/components/CopyButton.tsx
src/components/DisplayUnitTag.tsx
src/constants/analytics.ts
src/constants/candles.ts
src/constants/debounce.ts
src/constants/localStorage.ts
src/constants/trade.ts
src/hooks/Orderbook/useDrawOrderbook.ts
src/hooks/tradingView/useTradingView.ts
src/hooks/useDebounce.ts
src/lib/testFlags.ts
src/lib/tradingView/dydxfeed/index.ts
src/lib/tradingView/utils.ts
src/state/configs.ts
src/state/configsSelectors.ts
src/views/CanvasOrderbook/CanvasOrderbook.tsx
src/views/CanvasOrderbook/OrderbookControls.tsx
src/views/MarketStatsDetails.tsx
src/views/charts/PnlChart.tsx
src/views/charts/TradingRewardsChart.tsx
src/views/forms/AccountManagementForms/DepositForm.tsx
src/views/forms/AccountManagementForms/WithdrawForm.tsx
src/views/forms/StakingForms/StakeForm/StakeFormInputContents.tsx
src/views/forms/StakingForms/UnstakeForm/UnstakeFormInputContents.tsx
src/views/forms/TradeForm/LeverageSlider.tsx
src/views/forms/TradeForm/TradeFormInputs.tsx
src/views/forms/TradeForm/TradeSizeInputs.tsx
src/views/forms/TriggersForm/OrderSizeSlider.tsx

- add global state / local storage for display unit; i.e. synced display unit for all cases
- existing cases: orderbook controls + amount input toggle
- new cases: open interest, trading view volume, asset tags on orderbook and amount input
- debounced the dispatch on amount input toggle and asset tag to prevent spamming (didn't do that on orderbook controls because you have to move your mouse)
- added debounced constants
https://github.com/user-attachments/assets/05c1b30a-e4d1-404b-ae9b-2e2220a14745

feat: toggle display unit usd <> base token/asset

---

src/constants/account.ts

Vault withdrawal is estimated to be 75 cents, bumping up to $1 and rebalance to $0.8

feat: bump up gas reservation for vault withdrawal

---

src/lib/__test__/tradeData.spec.ts
src/lib/tradeData.ts
src/views/forms/TradeForm/PlaceOrderButtonAndReceipt.tsx

Hyperliquid does this, and it seems to make more sense to keep the idea of MMF hidden from users most of the time.

fix: use imf for positions margin calculation

---

src/lib/analytics/datadog.ts

enables deployers to use a proxy url in case they want to send logs somewhere else other than directly to a DD instance.
for example, if a deployer would like to send them to a proxy url that sends the logs to multiple destinations.

feat: add datadog proxy url [OTE-827]

---

src/lib/testFlags.ts

remove unused `isolatedMargin` and `complianceApi` flags. 
enable `pml`, and `uiRefresh` on staging

chore: enable uiRefresh on staging link

---

src/views/forms/TradeForm.tsx
src/views/forms/TradeForm/MarketLeverageInput.tsx
src/views/forms/TradeForm/TradeSizeInputs.tsx
src/views/tables/PositionsTable.tsx

positions don't need to be default sorted by market; others fills/orders table don't have to default arrow on
i fucked up label / tag spacing
mobile size trade type orders toggle should only show icon when selected

fix: smol trade polishes

---

src/pages/token/RewardsPage.tsx

Move launch incentives above Trading Rewards graph
---
- `<RewardsPage>`
- Update tile order
---

style: re-order launch incentives

---

src/layout/Header/HeaderDesktop.tsx

https://github.com/user-attachments/assets/838dd724-b7f9-4fca-b1fe-118174f33e93
Add External Navigation dialog.
---
- `<HeaderDesktop>`
- Add ExternalLink Dialog when users try to navigate to API Documentation
---

fix: external nav dialog on api documentation

---

src/components/visx/TimeSeriesChart.tsx
src/pages/vaults/VaultPnlChart.tsx

Give the chart parent the option to add some percent padding to the domain calculations so updates don't cause points to get pushed off screen.

fix: zoom domain excluding first point on data update

---

src/hooks/useAccounts.tsx

Check that geo is not blocked before trying to connect via stored signature

fix: do not connect wallet from remember me in restricted geo

---

src/constants/localStorage.ts
src/hooks/useCurrentMarketId.ts
src/state/_store.ts
src/state/dismissable.ts
src/state/dismissableSelectors.ts
src/state/migrations.ts
src/state/migrations/1.ts
src/state/migrations/2.ts
src/state/migrations/__test__/2.test.ts
src/views/MarketDetails/CurrentMarketDetails.tsx
src/views/dialogs/PredictionMarketIntroDialog.tsx

Miscellaneous fixes for Polymarket feature and long form tickers.
---
- `<PredictionMarketIntroDialog>`
- Use `dismissable` slice to set `hasSeenPredictionMarketIntroDialog`
- `<CurrentMarketDetail>`
- Remove long form ticker
- `hooks/useCurrentMarketId`
- use `hasSeenPredictionMarketIntroDialog` via `useAppSelector`
- new `state/dismissable`, `state/_store`
- Add `dismissable` reducer/slice and add to redux-persist
- Add `dismissableSelectors`
- Use for `hasSeenPredictionMarketIntroDialog` to replace `useLocalStorage`
- new `state/migration2`
- migrate localStorage to redux persist 
---

fix(polymarket): add dismissable reducer and fix ticker

---

src/hooks/useMarketsData.ts

put the prediction market behind feature flag so it can be toggled on/off via `ffShowPredictionMarketsUi`

fix: put prediction market behind feature flag

---

package.json
pnpm-lock.yaml
src/components/Tabs.tsx
src/views/CanvasOrderbook/OrderbookRow.tsx

- pull in new translations
- fix stacking of characters in tabs
- note, I verified that "Depth" is a translation key (DEPTH_CHART_SHORT) it's just that japanese happened to translate it as "Depth" :( (will find channel to circuit feedback into)
| before | after | 
| <img width="330" alt="Screenshot 2024-10-14 at 5 25 15 PM" src="https://github.com/user-attachments/assets/e1187e73-3bc1-49b7-902d-4408ccd20e2c"> |  <img width="318" alt="Screenshot 2024-10-14 at 5 28 13 PM" src="https://github.com/user-attachments/assets/b9e2b897-e15c-49af-9221-59f74cea1ff6"> | 
| <img width="753" alt="Screenshot 2024-10-14 at 5 40 30 PM" src="https://github.com/user-attachments/assets/a91292b9-62d8-49df-8262-5be3437f0915"> | <img width="738" alt="Screenshot 2024-10-14 at 5 40 21 PM" …

fix: fix stacking of characters

---

package.json
pnpm-lock.yaml
src/hooks/useSubaccount.tsx
src/views/forms/NewMarketForm/v7/NewMarketPreviewStep.tsx

Update frontend to use new `createPermissionlessMarket` client functions.
---
- `v7.0 <NewMarketPreviewForm>`
- use `createPermissionlessMarket` method
- `hooks/useSubaccount`
- add `createPermissionlessMarket` method
- `@dydxprotocol/v4-client-js`
- Bump version to one that includes client call 
- updated: v1.10.0 -> v1.11.0
---

feat(create-market): Add create market client call

---

src/lib/domUtils.ts
src/views/MarketsDropdown.tsx

was gonna do a cool kbd element but it doesn't make sense to exist anywhere so this is a hidden power feature :3
testing:
- go to trade page
- enter '/'
- observe market dropdown open
- notice if you '/' again nothing happens (it is not a toggle!). 'esc' to leave

feat: market dropdown shortcut '/' key

---

src/constants/abacus.ts
src/hooks/useDydxClient.tsx
src/hooks/vaultsHooks.ts

Going to hold off merging until staging pnl points are fixed so I can see how this actually looks.

fix: just merge vault pnl points for smooth recent pnl plus long term views

---

src/components/Table/TablePaginationRow.tsx
src/components/ToggleGroup.tsx

temp fix was breaking if pagination was in the hundreds, so just disabled truncation on buttons in pagination row

fix: fix truncation on pagination rows

---

src/lib/analytics/datadog.ts

https://dydx-team.slack.com/archives/C05UN0D4GCQ/p1729103258309479?thread_ts=1727976245.694519&cid=C05UN0D4GCQ
One of our deployers is requesting we append the DD log endpoint path to simplify proxy forwarding.

feat: log endpoint path

---

src/constants/statsig.ts
src/hooks/tradingView/useTradingView.ts
src/hooks/tradingView/useTradingViewToggles.tsx
src/lib/abacus/websocket.ts

Gates ohlc behind statsig ff (ff_enable_ohlc) because we foresee needing to turn it on/off a few times in the next few weeks.
Expected behavior: 
- when ff_enable_ohlc = false: do not show ohlc toggle, data shown should be that of when ohlc toggle is off
- when ff_enable_ohlc = true; show ohlc toggle, default to true
Tested by toggling ff_enable_ohlc and verifying the above cases (i suggest using NOT market to see obvious differences)

chore: gate ohlc behind statsig ff

---

src/pages/portfolio/Overview.tsx
src/state/dismissable.ts
src/state/dismissableSelectors.ts
src/state/migrations/2.ts
src/views/AffiliatesBanner.tsx

On desktop, move the affiliate banner to top of overview page and allow it to be dismissable.

feat: dismissable affiliate banner

---

src/constants/analytics.ts
src/hooks/useAnalytics.ts

Uses a ref to track the previous location pathname outside of the react lifecycle. if people are spooked by this i'm happy to use another approach but it feels pretty stable to me

feat: add previous page to navigatePage [OTE-768]

---

src/views/menus/AccountMenu.tsx

Wraps actions in account menu in `<Item>` tag which allows it to automatically dismiss the parent dropdown on click.
Prior to this, if a user selected an asset action (either the withdraw or deposit arrow in the account dropdown, which is the wallet address dropdown in the header) they would have both the onboarding modal and the account menu open at once.

fix: dismiss account menu on select [OTE-809]

---

package.json
pnpm-lock.yaml
src/components/Button.stories.tsx
src/components/Button.tsx
src/constants/buttons.ts
src/constants/tooltips/trade.ts
src/pages/trade/MobileTopPanel.tsx
src/pages/trade/Trade.tsx
src/styles/constants.css
src/views/AccountInfo.tsx
src/views/AccountInfo/AccountInfoConnectedState.tsx
src/views/AccountInfo/AccountInfoDiffOutput.tsx
src/views/AccountInfo/AccountInfoSection.tsx
src/views/forms/TradeForm/PlaceOrderButtonAndReceipt.tsx
src/views/tables/OrdersTable/OrderActionsCell.tsx
src/views/tables/PositionsTable/PositionsActionsCell.tsx

1. [Flagged] Moves the account info section to the bottom of the trade box
2. Adds some missing tooltips (unrelated)
3. Added a new "withoutBackground" style to Button because I was tired of adding `background: transparent; border: none` everywhere and I wanted it to work with the different button states
Does not:
- Does not update the cross | isolated margin selector (that will come in a follow up because it hasn't yet been mocked)
- Mobile web could look better, but i'll follow up; this approximately matches the current state of world
| | DesktopWeb | Mobile | DesktopWeb- unflagged | Mobile - unflagged |
| ---- | ---- | ---- | ---- | ---- |
| Connected | <img width="1248" alt="Screenshot 2024-10-18 at 4 02 16 PM" src="https://github.com/user-attachments/assets/b0e35429-719f-4f51-a8ff-e2b …

feat(uirefresh): component refresh - trade box [1/2]

---

src/components/ComboboxMenu.tsx
src/components/SearchInput.tsx
src/components/SearchSelectMenu.tsx
src/constants/__test__/cctp.spec.ts
src/constants/cctp.ts
src/constants/transfers.ts
src/hooks/transfers/useTransfers.tsx
src/lib/assetUtils.ts
src/views/forms/AccountManagementFormsNew/WithdrawForm/NetworkSelectMenu.tsx

Followed by https://github.com/dydxprotocol/v4-web/pull/1156
Adds networkselectmenu.
Adds useSearchInputComponent prop that renders the SearchInput component instead, [as specified by figma mocks](https://www.figma.com/design/fMQodZKzn9B5aZTN5G0fLJ/dYdX-%E2%80%BA-Web?node-id=41402-168816&node-type=frame&t=HtXCnIXhOiY4jfOY-0)
**This will make our search inputs bigger in general since i'm increasing the size from 2 to 2.5rem**
NOTE: I opted to not use a general component override prop since we don't don't have a usecase for it yet and it feels like a great "rule of three" moment to avoid overengineering something we dont need
It's not quite identical to the figma specs due to:
- the existing search input component just looks slightly different (magnifying glass opposite direction)
- we …

feat: cctp withdrawals: network select dropdown [3/n]

---

src/views/forms/AccountManagementFormsNew/WithdrawForm/WithdrawButtonAndReceipt.tsx
src/views/forms/AccountManagementFormsNew/WithdrawForm/useValidation.tsx

Followed by: https://github.com/dydxprotocol/v4-web/pull/1155
Adds:
- WithdrawButtonAndReceipt
- useValidation hook
I opted to create a local custom `useValidation` hook instead of a component because the [output of the hook is used to compute derived state in the parent component (WithdrawForm)](https://github.com/dydxprotocol/v4-web/pull/1155/files#diff-ca6afead7da0e940677b7fd3c8abe6960ea101300d3e1e16e4ecf8bf28ae18b7R439). Alternatively we could have the `errorMessage` be a piece of state in the `WithdrawForm` component, but i didn't like having `errorMessage` as a state item since it's not controlled by the component
The WithdrawButtonAndReceipt component is **not** finalized to the [figma spec](https://www.figma.com/design/fMQodZKzn9B5aZTN5G0fLJ/dYdX-%E2%80%BA-Web?node-id=42743-193255& …

feat: cctp withdrawals: receipt + validation [4/n]

---

src/components/CollapsibleTabs.tsx
src/components/IconButton.tsx
src/components/SearchInput.tsx
src/components/WithTooltip.tsx
src/views/MarketsDropdown.tsx
src/views/forms/ClosePositionForm.tsx
src/views/menus/NotificationsMenu.tsx
src/views/tables/OrdersTable/OrderActionsCell.tsx
src/views/tables/PositionsTable/PositionsActionsCell.tsx
src/views/tables/PositionsTable/PositionsTriggersCell.tsx

follow ups from https://github.com/dydxprotocol/v4-web/pull/1178#discussion_r1809130025 and consolidated styling of `IconButton` and `Button`
---
- `<ClosePositionForm>`
- Wrap text in span so that tag is properly positioned after it
- `<OrderActionsCell>`
- Replaced `$uiRefreshEnabled` styling with `buttonStyle` prop
- Fixed width so that the focus looks correct
- `<PositionActionsCell>`
- Replaced `$uiRefreshEnabled` styling with `buttonStyle` prop
- Fixed width so that the focus looks correct
- Reduced icon size a bit, checked with both flag on and off
- `<PositionTriggersCell>`
- Fixed width so that the focus looks correct
- `<CollapsibleTabs>`
- Update to `Square` when `uiRefresh` enabled so that focus outlines match
- Replaced `$uiRefreshEnabled` styling with `IconButton` prop
- …

fix: fix button styling nits

---

src/hooks/transfers/useTransfers.tsx
src/views/forms/AccountManagementFormsNew/WithdrawForm/WithdrawForm.tsx

move cosmosChainAddresses to useMemo and export it from useTransfers hook
use cosmosChainAddresses to calculate cosmos address.
if we dont receive an address from cosmosChainAddresses, then we're not connected to keplr

feat: calculate withdrawal address for keplr [OTE-875]

---

src/components/NavigationMenu.tsx
src/layout/Header/HeaderDesktop.tsx
src/styles/popoverMixins.ts

known existing bug that I did not fix:
- when truncated, the "more" dropdown is also truncated :( tix [here](https://linear.app/dydx/issue/CT-1265/more-dropdown-gets-cut-off)
| w/o flag | w/ flag |
| <img width="1203" alt="Screenshot 2024-10-22 at 5 57 49 PM" src="https://github.com/user-attachments/assets/6415432a-b2a2-4d05-8f5c-ac863d47b4a7"> | <img width="1217" alt="Screenshot 2024-10-22 at 5 58 36 PM" src="https://github.com/user-attachments/assets/daed0354-9807-44f4-a5cb-4ab6bea9c7c2"> |

feat(uirefresh): update navigation bar tab styling

---

src/views/MarketFilter.tsx

| before | after | 
| <img width="690" alt="Screenshot 2024-10-22 at 6 36 55 PM" src="https://github.com/user-attachments/assets/f479b7ab-22f4-420a-85e1-85c13d184ca8"> | <img width="660" alt="Screenshot 2024-10-22 at 6 38 24 PM" src="https://github.com/user-attachments/assets/a265cb88-aa42-4d95-abc0-a7e8632a4193"> |

fix: match launch market button to updated search filter size

---

src/pages/trade/HorizontalPanel.tsx

Fix non ui-refresh toolbar
---
- `<HorizontalPanel>`
- use `getDisplayableAssetFromBaseAsset` on `currentMarketAssetId`
---

fix(horizontal-panel): Use displayable asset in Toolbar

---

src/hooks/useSubaccount.tsx

the memo was overriding the recipient param.

fix: withdrawFromSubaccount was broken

---

src/components/Button.tsx
src/views/dialogs/OnboardingDialog/GenerateKeys.tsx

figma [mock](https://www.figma.com/design/fMQodZKzn9B5aZTN5G0fLJ/dYdX-%E2%80%BA-Web?node-id=42754-198329&node-type=frame&t=iPyae9XP1sscvOTU-0). 
figured we could get away with not flagging since it's not a big diff / mainly just swapping the side of the check mark and text.
Updated `Button` `withContentOnLoading` behavior.
https://github.com/user-attachments/assets/c25ec4a9-a48a-46d1-ba72-794dccedff2e

feat(uirefresh): new user wizard - generate keys

---

src/components/AssetIcon.tsx
src/constants/localStorage.ts
src/hooks/useMarketsData.ts
src/pages/trade/LaunchableMarket.tsx
src/state/configs.ts
src/state/configsSelectors.ts
src/views/MarketFilter.tsx
src/views/MarketsDropdown.tsx
src/views/forms/TradeForm/PlaceOrderButtonAndReceipt.tsx
src/views/forms/TradeForm/TradeSizeInputs.tsx
src/views/tables/MarketsTable.tsx

- Fix `shouldHideLaunchableMarkets` toggle and convert from useState to redux state
- Give `AssetIcon` white background
- Fix position of `<AccountInfo>` component
- Fix tooltips that use `AssetId`
---
- `<PlaceOrderAndButtonReceipt>`, `<TradeSizeInputs>`
- use `getDisplayableAssetFromBaseAsset` to fix display of tooltip
- `<MarketFilter>`
- Fix toggle (it was inverted)
- Use dispatch and selector for `shouldHideLaunchableMarkets`
- `<LaunchableMarket>`
- keep UI refresh conditional consistent with `<Trade>` page 
- `<AssetIcon>`
- give `img` a white background for icons that use transparency
- `constants/localStorage`
- add `shouldHideLaunchableMarkets` localStorageKey
- `hooks/useMarketsData`
- use redux version of `shouldHideLaunchableMarkets`
- `state/configs`, …

fix(pml-toggle): Fix Toggle + misc

---

src/pages/vaults/VaultPositionsTable.tsx

KEEP THE MISC FIXES TRAIN GOING

fix: misc vault fixes 7

---

src/components/visx/SparklineChart.tsx
src/components/visx/TimeSeriesChart.tsx
src/pages/vaults/VaultPnlChart.tsx
src/pages/vaults/VaultPositionsTable.tsx
src/views/charts/DepthChart/index.tsx
src/views/charts/FundingChart/index.tsx
src/views/charts/LaunchableMarketChart.tsx
src/views/charts/PnlChart.tsx
src/views/charts/TradingRewardsChart.tsx
src/views/tables/MarketsTable.tsx

the library lies about the types and sometimes passes undefined so we should be forced to handle it to prevent errors.

fix: accessors sometimes receive undefined apparently

---

src/lib/abacus/index.ts
src/lib/testFlags.ts

it can be useful to explicitly set a test flag to false to check if that's the culprit e.g. static typing, or easier testing during dev to switch test flags on or off
added a helper function `booleanFlag(flag, defaultTrueEnvironment)`

chore: support negative boolean test flags

---

src/components/Table/AssetTableCell.tsx
src/components/Table/TablePaginationRow.tsx
src/hooks/useMarketsData.ts
src/views/MarketsStats.tsx
src/views/tables/MarketsCompactTable.tsx
src/views/tables/MarketsTable.tsx

markets table polish and fixes, especially on mobile: show volume (and sorted by that), truncate asset name in compact table + shorten pagination row so they don't overflow weridly
hide recently listed table when no markets are new (currently defined by having less than 7d sparklines historical data)

fix: markets table improvements

---

src/styles/themes.ts
src/views/CanvasOrderbook/CanvasOrderbook.tsx
src/views/CanvasOrderbook/OrderbookControls.tsx

1. Remove transparency on tooltips + popovers
2. Update orderbook row:
- Unflagged - add borders on top and bottom just cuz I think it looks better, feel free to disagree if you don't, I sorta went rogue here
- Flagged - updated buttons to more toggle style cuz I think it matches the overall UI vibe better
| Unflagged | Flagged |
| <img width="334" alt="Screenshot 2024-10-28 at 6 14 41 PM" src="https://github.com/user-attachments/assets/926fb100-4677-4197-bb32-3c645abb3276"> | <img width="335" alt="Screenshot 2024-10-28 at 6 19 32 PM" src="https://github.com/user-attachments/assets/328ce4df-424f-4f83-aec3-0f6eaf01d909"> |

chore(uiRefresh): remove transparency on tooltips, polish orderbook row

---

src/constants/analytics.ts
src/hooks/usePotentialMarkets.tsx
src/hooks/useSubaccount.tsx
src/pages/trade/LaunchableMarket.tsx
src/views/charts/LaunchableMarketChart.tsx
src/views/forms/NewMarketForm/index.tsx
src/views/forms/NewMarketForm/v7/NewMarketSelectionStep.tsx

Add analytics for PML flow to study feature popularity/engagement.
---
- `<NewMarketForm>`
- add `LaunchMarketFormStepChange` tracking as user progresses through flow
- `<NewMarketSelectionStep>`
- add `LaunchMarketFormSelectedAsset` tracking when user selects an asset
- `<LaunchableMarket>`
- add `LaunchMarketViewFromTradePage` tracking views
- `<LaunchableMarketChart>`
- add `LaunchMarketPageChangePriceChartTimeframe` tracking timeframe changes
- `constants/analytics`
- Add 5 new AnalyticsEvents around PML flow
- `hooks/usePotentialMarketsData`
- update `hasPotentialMarketsData` to include testFlag for pml boolean
- `hooks/useSubaccount`
- add  track for `LaunchMarketTransaction`
---

chore(pml-analytics): Add analytics events to PML flow

---

src/pages/LaunchMarket.tsx
src/pages/trade/TradeHeaderMobile.tsx
src/views/charts/LaunchableMarketChart.tsx

| Before | After |
| --- | --- |
| <img width="602" alt="Screen Shot 2024-10-30 at 12 47 28 PM" src="https://github.com/user-attachments/assets/04612b35-eec3-43e9-aa15-af3ae7c4742c"> | <img width="611" alt="Screen Shot 2024-10-30 at 12 47 50 PM" src="https://github.com/user-attachments/assets/e3eb65d1-6683-4438-acd6-76c09cfeaa4d"> |
Update LaunchMarket page for mobile view
---
- `<TradeMobileHeader>`
- `border-r` is border-right and not border-radius
- `<LaunchMarket>`, `<LaunchableMarketChart>`
- Update padding and widths of components
---

chore(pml-mobile): update mobile LaunchMarket page

---

src/views/LaunchableMarketStatsDetails.tsx
src/views/MarketStatsDetails.tsx
src/views/MarketsDropdown.tsx
src/views/MidMarketPrice.tsx
src/views/PositionInfo.tsx
src/views/PositionTile.tsx
src/views/charts/LaunchableMarketChart.tsx
src/views/dialogs/DetailsDialog/FillDetailsDialog.tsx
src/views/forms/AdjustIsolatedMarginForm.tsx
src/views/notifications/TradeNotification/FillDetails.tsx
src/views/tables/FillsTable.tsx
src/views/tables/FundingPaymentsTable.tsx
src/views/tables/MarketsTable.tsx
src/views/tables/OrdersTable.tsx
src/views/tables/PositionsTable.tsx
src/views/tables/PositionsTable/PositionsTriggersCell.tsx
src/views/tables/PositionsTable/PositionsTriggersCellDeprecated.tsx

Use `withSubscript` prop for most `<Output>` components that use `tickSizeDecimals` as it's `fractionDigits`.
This should cutdown on the width of rendered prices in multiple places.
---

style(with-subscript): Add withSubscript prop to rendered prices

---

package.json
pnpm-lock.yaml
public/configs/v1/env.json
src/hooks/useURLConfigs.ts
src/views/forms/NewMarketForm/v7/NewMarketPreviewStep.tsx

Replace acknowledgement step with checkbox
---
- `<NewMarketPreviewStep>`
- replace acknowledgement step with checkbox
- `hooks/useUrlConfigs`
- add and expose `launchMarketTos` from env.json
- `v4-localization`
- updated: v1.1.237 -> v1.1.238
---

chore(pml-ack): use checkbox w/ link

---

src/hooks/tradingView/useBuySellMarks.ts
src/hooks/tradingView/useChartLines.tsx
src/hooks/tradingView/useChartMarketAndResolution.ts
src/hooks/tradingView/useOrderbookCandles.ts
src/hooks/tradingView/useTradingView.ts
src/hooks/tradingView/useTradingViewLaunchable.ts
src/hooks/tradingView/useTradingViewTheme.ts
src/views/charts/TradingView/BaseTvChart.tsx
src/views/charts/TradingView/TvChart.tsx
src/views/charts/TradingView/TvChartLaunchable.tsx

- refactors instances of isChartReady usage to just run in tvWidget.onChartReady() callbacks to keep the widget and callbacks more atomic to the actual instance of the widget being used
- removes one check for clearing chart lines bcuz we have no idea why its being done this way: https://github.com/dydxprotocol/v4-web/blob/main/src/hooks/tradingView/useChartLines.tsx#L493

chore: fix usage of isChartReady in trading view charts

---

src/hooks/tradingView/useBuySellMarks.ts
src/hooks/tradingView/useChartLines.tsx
src/hooks/tradingView/useChartMarketAndResolution.ts
src/hooks/tradingView/useOrderbookCandles.ts
src/hooks/tradingView/useTradingView.ts
src/hooks/tradingView/useTradingViewLaunchable.ts
src/hooks/tradingView/useTradingViewTheme.ts
src/views/charts/TradingView/BaseTvChart.tsx
src/views/charts/TradingView/TvChart.tsx
src/views/charts/TradingView/TvChartLaunchable.tsx

fixes an issue where loading states for launchable markets weren't updating when tvWidget was ready

fix: change tvWidget into react state instead of ref

---

src/views/CanvasOrderbook/CanvasOrderbook.tsx
src/views/forms/ClosePositionForm.tsx

I just threw it in the middle: 
https://linear.app/dydx/issue/CT-1274/[close-positions]-make-orderbook-toggleable-smaller

fix: mobile close position orderbook toggle

---

src/pages/trade/MobileTopPanel.tsx

https://linear.app/dydx/issue/CT-1303/[wallet]-consider-aligning-better-using-the-space
Before:

fix: reasonable sizing for mobile wallet info

---

src/components/SortIcon.tsx
src/pages/portfolio/Fees.tsx
src/styles/breakpoints.ts

- invisible sort icons dont take up space
- make exclusive breakpoints non-overlapping
- make fees look nicer
Before:

fix: nicer tables in a few ways

---

src/hooks/tradingView/useChartMarketAndResolution.ts
src/hooks/tradingView/useTradingView.ts
src/hooks/tradingView/useTradingViewLaunchable.ts
src/state/perpetuals.ts
src/state/perpetualsSelectors.ts
src/views/charts/TradingView/TvChart.tsx
src/views/charts/TradingView/TvChartLaunchable.tsx

- this PR removes struct from perpetual slice that saves resolutions per market, because they arent really being used
- this fixes logic with initial resolutions when changing markets

fix: default resolution logic + remove data for saving resolution per market

---

package.json
pnpm-lock.yaml
src/pages/trade/LaunchableMarket.tsx
src/pages/trade/Trade.tsx
src/views/forms/TradeForm/TargetLeverageInput.tsx

fix: isolated leverage, bump abacus, reposition the account info

---

src/components/Link.tsx
src/pages/portfolio/Overview.tsx
src/views/Affiliates/cards/AffiliateStatsCard.tsx
src/views/Affiliates/community-chart/ProgramChartContainer.tsx
src/views/AffiliatesBanner.tsx

The links should redirect to /affiliates instead of to the Fuul page
Portfolio page:
|Desktop|Mobile|
|---------|------|
|<img width="1055" alt="image" src="https://github.com/user-attachments/assets/11bff170-19ca-48de-ae3f-fcb68b113ba1">|<img width="822" alt="image" src="https://github.com/user-attachments/assets/e02a8396-9782-4db6-afef-9a72eef85057">|
Affiliates page:

fix(affiliates): banner links

---

src/hooks/useNotificationTypes.tsx
src/layout/NotificationsToastArea/NotifcationStack.tsx

To prevent outdated `fills` notifications. Block all historic notifications that occurred before App initialization.
---
- `<NotificationStack>`
- Add const var `NOTIFICATIONS_INIT_TIME` at `useNotificationTypes` initialization
- Block toast notifs that occur before app init.
---

fix(notifs): Block historic Abacus generated notifs

---

scripts/inject-google-tag-manager.js

The existing version always used a dummy container ID: `GTM-ABCDEFGH`. This PR fixes the issue by inserting the value from the `GOOGLE_TAG_MANAGER_CONTAINER_ID` environment variable.

fix: Fix Google Tag Manager parameter injection

---

src/views/forms/NewMarketForm/index.tsx
src/views/forms/NewMarketForm/v7/NewMarketPreviewStep.tsx

Clean up NewMarketForm and v7/NewMarketPreviewStep
- Remove `setParentIsLoading` prop since we no longer have a Dialog View
- Block alertMessage if form is in `loading` state

chore(newmarket-preview-step): hide alertInfo if loading

---

src/lib/__test__/numbers.spec.ts
src/lib/numbers.ts
src/pages/markets/MarketsBanners.tsx
src/views/tables/MarketsCompactTable.tsx
src/views/tables/MarketsTable.tsx

https://github.com/user-attachments/assets/a7a92325-d8e3-4d49-8b41-ef5b2619ba31
- Update tickSizeDecimal calculation when given a reference price
- Fix MarketsTable and MarketsCompactTable
https://linear.app/dydx/issue/BUG2-60/mobile-web-biggest-movers-table-markets-page-clipping
https://linear.app/dydx/issue/BUG2-62/mobile-web-market-list-with-meme-filter-table-overlap-not-viewable
---
- `<MarketsCompactTable>`
- Remove 3rd column at mobile breakpoint
- `<MarketsBanners>`
- hide hedgie img at mobile breakpoint
- `<MarketsTable>`
- overflow on asset name at mobile breakpoint 
- `lib/numbers`, `lib/__test__/numbers.spec.ts`
- add `getTickSizeFromPrice` helper and add test
- use to retrieve tickSizeDecimals
---

fix: tickSizeDecimal calc and mobile view of markets tables

---

src/App.tsx
src/constants/launchableMarkets.ts
src/views/forms/NewMarketForm/index.tsx
src/views/forms/NewMarketForm/v7/NewMarketSuccessStep.tsx
src/views/notifications/PermissionlessMarketsLiveNotification.tsx

Remove LaunchMarket entry points entirely.
Update wait time from 30s -> 1m
---
- `<App>`, `<NewMarketSuccessStep>`, `<PermissionlessMarketsLiveNotification>`
- remove entry point to `AppRoute.LaunchMarket`
- `constants/launchableMarkets`
- 30s delay -> 60s
---

fix(pml): Remove remaining LaunchMarket entrypoints

---

src/hooks/useMarketsData.ts
src/pages/markets/Markets.tsx
src/pages/markets/MarketsBanners.tsx
src/views/MarketFilter.tsx
src/views/tables/MarketsTable.tsx

- Add onClick back to PML banner
- Filter markets by Abacus MarketStatus
---
- `<MarketsBanners>`
-  Add on click to PmlBanner to set filter and scroll to table
- `<MarketsPage>`
- Add ref to MarketsTable to help with scroll
- `<MarketFilter>`, `<MarketsTable>`
- wrap component in forwardRef
- `hooks/useMarketsData`
- filter out any market that does not have `canTrade`.
- Markets that have `canReduce` and not `canTrade` will still be accessible through open positions
---

fix(pml-banner): banner on click and filter settled markets

---

src/constants/markets.ts
src/hooks/tradingView/useTradingViewLaunchable.ts
src/hooks/useLaunchableMarkets.ts
src/hooks/useMarketsData.ts
src/hooks/useMetadataService.ts
src/hooks/userPerpetualMarkets.ts
src/pages/trade/TradeHeaderMobile.tsx
src/styles/constants.css
src/views/LaunchableMarketStatsDetails.tsx
src/views/MarketDetails/LaunchableMarketDetails.tsx
src/views/MarketLinks.tsx
src/views/MarketsDropdown.tsx
src/views/charts/LaunchableMarketChart.tsx
src/views/forms/NewMarketForm/v7/NewMarketPreviewStep.tsx
src/views/tables/MarketsTable.tsx

Display spot volume and market cap within markets table and market dropdown.
---
- `<MarketDropdown>`, `<MarketsTable>`
- add new columns
- `styles/constants.css`
- Give MarketDropdown additional horizontal space
- `constants/markets`
- add `spotVolume24H` and `marketCap`
- new `hooks/useMetadataService`
- move all metadataService queries to new file
- `hooks/useLaunchableMarkets`
- import `metadataService` queries
- `hooks/useMarketsData`
- add spotVolume24H and marketCap to Market object 
---

feat(spot-volume): show spot-volume and market cap

---

public/configs/v1/env.json
src/views/tables/FillsTable.tsx
src/views/tables/OrdersTable.tsx
src/views/tables/PositionsTable.tsx

Quiet ref errors in Table components and re-introduce Governance variables.
- Due to Abacus w/ StaticTyping
- Any removal of fields within env.json will also need a prerequisite Abacus change so there are no serialization errors
- Need to figure out why Abacus swallows these errors

fix: re-introduce governance variables

---

src/layout/DialogManager.tsx

I couldn't reproduce infinite re-renders but this made there be many fewer renders.

chore(nit): protect dialogmanager from parent rerenders

---

src/hooks/useAffiliatesInfo.ts
src/hooks/useAffiliatesLeaderboard.ts
src/pages/affiliates/AffiliatesPage.tsx
src/views/Affiliates/AffiliatesLeaderboard.tsx
src/views/Affiliates/ShareAffiliateBanner.tsx
src/views/Affiliates/cards/AffiliateStatsCard.tsx
src/views/Affiliates/cards/ProgramStatusCard.tsx

This PR fixes a bunch of things on the affiliates page
- Changes the loading display to be more granular instead of making the whole page load
- Adds `staleTime` to some react-query calls so that affiliates calls will not be re-requested on some component mounting
- Fixes some styling
Disconnected view:
Not affiliate view:
Affiliate view:
Loading metadata:

feat: more sane loading states for affiliate page

---

src/hooks/useReferralCode.ts
src/views/dialogs/ReferralDialog.tsx

isPending will be false if theres no current `dydxAddress`, as some of these queries are paused until `dydxAddress` is defined, so dont rely on that as a loading indicator if theres no connected wallet yet

fix: get rid of pending checks in affiliate flow

---

src/App.tsx
src/components/RestrictionWarning.tsx
src/hooks/useComplianceState.tsx
src/styles/constants.css
src/views/MarketsDropdown.tsx

Add restriction warning height to css vars in order to be used in css calcs.
---
- `<App>`
- set the restriction warning current height css var
- `<MarketDropdown>`
- include restriction warning height in sticky positioning calc
- `<RestrictionWarning>`
- wrap contents in span in order to vertically center after giving a fixed height
- `styles/constants.css`
- add restriction warning heights
- `hooks/useComplianceState`
- return boolean on whether to display compliance warning
---

fix: compliance banner hides table pagination

---

src/hooks/useAffiliatesInfo.ts

this is so that every time the user goes to the referrals tab, we should update their metadata query, even if the staleTime hasn't been reached yet. we should still keep the staleTime because that prevents re-requests on rerenders

fix: always refetch affiliates metadata query on mount

---

src/pages/affiliates/AffiliatesPage.tsx
src/views/Affiliates/AffiliatesLeaderboard.tsx

this handles the connected -> disconnected state better, where your accountStats query may be still lingering from a previously connected dydxAddress

fix: check for dydxAddress in affiliates leaderboard

---

.env.example
src/constants/localization.ts
src/hooks/tradingView/useTradingView.ts
src/hooks/tradingView/useTradingViewLaunchable.ts
src/hooks/useLocaleSeparators.tsx
src/lib/consistentAssetSize.ts
src/lib/objectHelpers.ts
src/pages/settings/Settings.tsx
src/state/localizationMiddleware.ts
src/views/menus/LanguageSelector.tsx

Clean up localization code and use a single config object.
Allow deployers to set configure available locales from those supported.
---
- `<LanguageSelector>`, `<Settings>`
- update to use new config 
- `constants/localization`
- Add localization config
- `.env.example`
- add `VITE_APP_RESTRICTED_LOCALES`. No spaces
- example:
- `VITE_APP_RESTRICTED_LOCALES=en,zh-CN,fr,de`
- `consistentAssetSizing`
- update to use new config 
- `lib/objectHelpers`
- add typed object.fromEntries 
- `useTradingView`, `useTradingViewLaunchable`, `useLocaleSeparators`
- update to use new config 
- `localizationMiddleware`
- update to use new config 
---

refactor(localization): Consolidate mappings to one config object

---

src/layout/Header/HeaderDesktop.tsx

Instead of disabling, just hide Deposit Modal entry
---
- `<HeaderDesktop>`
- Hide Deposit button if Account is not connected

chore: hide deposit button in header prior to connection

---

src/views/tables/LiveTrades.tsx

Use displayableAssetId instead of id to prevent long form tickers from messing up UI.
---
- `<LiveTrades>`
- use displayableAssetId
- update dep array
---

fix: use displayable assetId in live trades

---

package.json
pnpm-lock.yaml

- Remove deprecated stylesheets in Tv zip
- Bump Abacus
---
- `v4-abacus`
- Onboarding changes for routes & priceImpact
- updated: v1.13.35 -> v1.13.39
---

chore: update packages and re-zip tradingview

---

src/constants/wallets.ts
src/hooks/useDisplayedWallets.ts

Stop always showing Metamask if the user doesn't have metamask. This makes no sense in the mobile web app context (not in-app browser) because there is no metamask extension available on mobile web, but confuses users into thinking it would auto connect their mobile metamask wallet (they should use walletconnect instead).

feat: remove metamask option if user doesnt have metamask

---

src/components/DetailsDialog.tsx
src/components/Dialog.tsx
src/components/DropdownHeaderMenu.tsx
src/components/DropdownMenu.tsx
src/components/DropdownSelectMenu.tsx
src/components/NavigationMenu.tsx
src/components/Popover.tsx
src/components/Tabs.tsx
src/components/Toast.tsx
src/layout/Footer/FooterDesktop.tsx
src/layout/Footer/FooterMobile.tsx
src/layout/Header/HeaderDesktop.tsx
src/pages/portfolio/EquityTiers.tsx
src/pages/portfolio/Fees.tsx
src/pages/trade/HorizontalPanel.tsx
src/pages/trade/TradeDialogTrigger.tsx
src/pages/trade/VerticalPanel.tsx
src/styles/formMixins.ts
src/styles/layoutMixins.ts
src/views/AccountInfo/AccountInfoSection.tsx
src/views/CanvasOrderbook/CanvasOrderbook.tsx
src/views/MarketsDropdown.tsx
src/views/charts/DepthChart/index.tsx
src/views/charts/TradingView/BaseTvChart.tsx
src/views/forms/AccountManagementForms/DepositForm.tsx
src/views/forms/AccountManagementForms/TestnetDepositForm.tsx
src/views/forms/AccountManagementForms/WithdrawForm.tsx
src/views/forms/TradeForm/PlaceOrderButtonAndReceipt.tsx
src/views/forms/TransferForm.tsx
src/views/tables/OrderbookTradesTable.tsx

Clean up styling nits around the app.
---
- `<EquityTiers>`, `<Fees>`
- consistent `theader` background color
- `<FooterDesktop>`, `<HeaderDesktop>`
- solid background color
- `<AccountInfoSection>`
- give deposit/withdraw button hover effect 
- `<MarketsDropdown>`
- solid thead and pagination-footer background color
- `<TvChartBase>`
- remove being able to interact with tvChart when overlay is present 
- `<FooterMobile>`, `<TradeDialogTrigger>`
- solid background 
- `<Tabs>`
- Fix hiding `forceMount` views (Orderbook)
- `<DropdownMenu>`, `<DropdownSelectMenu>`, `<DropdownHeaderMenu>`, `<Popover>`
- remove backdrop overlay
- `styles/formMixins`, `styles/layoutMixins`, 
- deprecate `withStickyFooterBackdrop`. Remove css vars on forms/dialogs for this style
---

style(nits): remove sticky transparency, fix ui nits

---

src/views/forms/AccountManagementForms/SourceSelectMenu.tsx

Invalid filter on allowed withdrawal chains when user is connected via Keplr.
---
- `<SourceSelectMenu>`
- do not filter for CCTP chains only when withdrawing while having Keplr connected.
- Allow withdraws to Coinbase
---

fix(keplr-withdrwa): allow withdrawals to exchange and fix cctp filter

---

public/configs/v1/env.json

This is completely optional.  Adding this as an example for the deployer.

chore: Add an example of configuring wallets that show up in the walletconnect modal list

---

src/pages/trade/HorizontalPanel.tsx
src/views/MarketDetails/CurrentMarketDetails.tsx
src/views/tables/FillsTable.tsx
src/views/tables/OrdersTable.tsx

I will revert this PR after break.

feat: undo ui-facing new abacus changes

---

src/abacus-ts/lib/resourceCacheManager.ts
src/abacus-ts/websocket/lib/indexerWebsocket.ts
src/abacus-ts/websocket/lib/reconnectingWebsocket.ts
src/hooks/useInitializePage.ts

- restart on visibility change and network reconnect
- properly avoid race conditions that might create multiple concurrent websockets or handle events from stale websockets

fix: refactor bonsai websocket layer

---

src/abacus-ts/rest/lib/useIndexer.ts

make sure to use key as part of your query key so that changes in network cause new fetch and use client != null for isActive.

feat: client grabber helpers

---

src/components/Output.tsx
src/constants/unicode.ts
src/hooks/Orderbook/useDrawOrderbook.ts
src/views/CanvasOrderbook/OrderbookControls.tsx
src/views/CanvasOrderbook/OrderbookRow.tsx

Add subscript support to Orderbook controls and canvas.
---
- `<OrderbookControls>`, `<OrderbookRow>`
- `withSubscript` on `<Output>`
- `useDrawOrderbook`
- use `withSubscript` in  `formatNumberOutput`
- `<Output>`
- Add `withSubscript` parameter to  `formatNumberOutput`. Uses formatZeroNumbers to inject subscript unicode into a string.
- This change is only for the formatting function and not `<Output>` component, which will rely on `<NumberValue>` component.
---

chore: subscript on orderbook

---

src/abacus-ts/websocket/lib/indexerWebsocket.ts
src/abacus-ts/websocket/lib/reconnectingWebsocket.ts

Simple retry logic: retry if it's been more than a minute since last retry.

fix(bonsai-core): retry channels who fail initial subscription

---

src/abacus-ts/lib/resourceCacheManager.ts
src/abacus-ts/websocket/lib/indexerValueManagerHelpers.ts
src/abacus-ts/websocket/lib/reconnectingWebsocket.ts
src/abacus-ts/websocket/lib/websocketDerivedValue.ts
src/abacus-ts/websocket/markets.ts
src/abacus-ts/websocket/orderbook.ts
src/abacus-ts/websocket/parentSubaccount.ts
src/abacus-ts/websocket/trades.ts

Now we keep all subscriptions open for an extra 20 seconds to prevent churn. Before if you flipped back and forth quickly (sub, unsub, resub) you'd run into weird race conditions and break things. Now when you unsub we hold onto that subscription for 20 seconds and then destroy it. If you re-sub before destruction we just hand you back the sub we kept around.

fix(bonsai-core): work around indexer race condition by managing websocket value lifecycles more clearly

---

src/hooks/useDydxClient.tsx

Ask for 1k per request, limit to 20 requests so we don't get rate limited and fail the whole operation.

fix: better tx/transfer download logic

---

src/abacus-ts/websocket/lib/indexerWebsocket.ts
src/abacus-ts/websocket/lib/missingMessageDetector.ts

Logs indicate sometimes websockets drop messages and Roy did some digging last week and found that this is indeed possible even though websockets are using TCP which shouldn't drop messages since websocket<>tcp connection isn't 1:1.

feat(bonsai-core): restart websocket if a message is missing for 10s

---

src/abacus-ts/websocket/lib/missingMessageDetector.ts

Turns out the backend chooses a subscribed message_id BEFORE actually doing anything so it is potentially delayed by up to 20s

fix: bump timeout because message_ids actually aren't in order at all

---

src/constants/chains.ts
src/hooks/transfers/skipClient.tsx
src/lib/viem.ts
src/lib/wagmi.ts
src/views/dialogs/DepositDialog2/DepositDialog2.tsx
src/views/dialogs/DepositDialog2/DepositForm.tsx
src/views/dialogs/DepositDialog2/utils.ts

UI IS STILL UGLY!
this PR adds logic for preparing the different steps that the user will need to take in order for their deposit to complete. the bulk of the logic is in `src/views/dialogs/DepositDialog2/utils.ts`
note this is mostly just relevant for evm users, since solana/keplr dont really have concept of switching chains or token approvals.

feat: Add logic for deposit steps

---

package.json
pnpm-lock.yaml

Bump `@funkit/connect` from `v4.1.6` -> `v4.1.7`. See [CHANGELOG.md](https://www.npmjs.com/package/@funkit/connect?activeTab=code) for version changes. 
- Key callout: Binance flow improvements
--- 
[Connect wallet] option no longer shows up if underlying wagmi connection is dropped (e.g. pure solana wallet connected or user deliberately disconnect via MM & not dydx)

chore(funkit): bump funkit version 4.1.7

---

src/bonsai/calculators/fills.ts

We were sorting by a string so it was only right if all your fills happen to have the same number of digits

fix: fills sort

---

src/bonsai/calculators/accountActions.ts
src/components/QrCode.tsx
src/views/dialogs/DepositDialog2/DepositDialog2.tsx
src/views/dialogs/DepositDialog2/DepositForm.tsx
src/views/dialogs/DepositDialog2/DepositStatus.tsx
src/views/dialogs/DepositDialog2/TokenSelect.tsx
src/views/dialogs/DepositDialog2/queries.ts

This PR adds info about difference in free collateral given a certain deposit amount in USD. It also syncs the success state of the `DepositStatus` modal to wait for the subaccount sweep to complete.

feat: add free collateral diffs and sync deposit success state with free collateral updates

---

package.json
pnpm-lock.yaml
src/components/AssetIcon.tsx
src/hooks/transfers/skipClient.tsx
src/state/transfers.ts
src/views/dialogs/DepositDialog2/AmountInput.tsx
src/views/dialogs/DepositDialog2/DepositStatus.tsx
src/views/dialogs/DepositDialog2/TokenSelect.tsx
src/views/dialogs/DepositDialog2/utils.ts

This upgrades to the newest versions of viem / wagmi so we can use their updated signer logic that allows us to send requests for a specific chain
Note: i already ran pnpm dedupe

chore: upgrade viem, wagmi, and use updated signer logic

---

package.json
pnpm-lock.yaml
src/components/Dialog.tsx
src/views/dialogs/DepositDialog2/DepositDialog2.tsx
src/views/dialogs/DepositDialog2/utils.ts

Use new `bypassApprovalCheck: true` flag in executeRoute because we already manually handle allowances

feat: Upgrade skip client to 0.16.8

---

src/components/Output.tsx
src/constants/tokens.ts
src/state/transfers.ts
src/views/dialogs/DepositDialog2/DepositForm.tsx
src/views/dialogs/DepositDialog2/RouteOptions.tsx
src/views/dialogs/WithdrawDialog2/ChainSelect.tsx
src/views/dialogs/WithdrawDialog2/WithdrawDialog2.tsx
src/views/dialogs/WithdrawDialog2/WithdrawForm.tsx
src/views/dialogs/WithdrawDialog2/queries.ts
src/views/dialogs/WithdrawDialog2/utils.ts

Add route execution logic, loading states, and small UI fixes.
- Only support Solana if sourceAccount is sol based
- Remove cosmos withdrawals except Noble
- separate DepositRouteOptions and WithdrawRouteOptions as they diverge in fees/estimatedTime
- If user has not manually inputted an address, Automatically populate address field depending on chain selected

feat(withdraw-ui): route execution, loading states, and small fixes

---

src/views/dialogs/DepositDialog2/utils.ts

sometimes metamask will return that it successfully switched chains but its ACTUALLY NOT DONE YET

feat: try awaiting network switching because METAMASK is so bad

---

src/lib/abacus/stateNotification.ts

Not sure why this wasn't caught by typescript, must be because it's assuming we're implementing a different method or something?

fix: type of last order

---

src/views/dialogs/TransferDialogs/WithdrawDialog2/WithdrawForm.tsx
src/views/dialogs/TransferDialogs/WithdrawDialog2/withdrawHooks.ts
src/views/dialogs/TransferDialogs/utils.ts

Update `getUserAddressesForRoute` so that the last object in `UserAddress[]` is the destination address when withdrawing.

fix: destinationAddress for withdraw execution

---

package.json
pnpm-lock.yaml
src/constants/dialogs.ts
src/hooks/useNotificationTypes.tsx
src/hooks/useSubaccount.tsx
src/hooks/useUpdateTransfers.tsx
src/layout/DialogManager.tsx
src/state/transfers.ts
src/state/transfersSelectors.ts
src/views/dialogs/TransferDialogs/DepositDialog2/DepositDialog2.tsx
src/views/dialogs/TransferDialogs/DepositDialog2/DepositStatus.tsx
src/views/dialogs/TransferDialogs/DepositDialog2/OtherDepositOptions.tsx
src/views/dialogs/TransferDialogs/DepositDialog2/TokenSelect.tsx
src/views/dialogs/TransferDialogs/DepositDialog2/depositHooks.ts
src/views/dialogs/TransferDialogs/TransferStatusDialog.tsx
src/views/dialogs/TransferDialogs/WithdrawDialog2/WithdrawForm.tsx
src/views/dialogs/TransferDialogs/WithdrawDialog2/WithdrawStatus.tsx

- Add `TransferStatusDialog` with entry points through the notifications created when initializing a Deposit or a Transfer
- Update some of the missed localization
- Added a fn that blocks auto-deposits if a pending withdraw is taking place (unless 10 min has elapsed while a subtransaction is still idle)
- add explorer links when updating a Deposit or Withdraw
- explorer links will now be rendered in DepositStatus and WithdrawStatus views 🎉 
- Fix executeStep dependency array so it actually uses the selected route (always defaulted to GO FAST)
- Fixed spacing within form (TY Alex)

feat: Transfer fixes, Explorer URL

---

src/bonsai/rest/height.ts
src/state/raw.ts

react query actually double-dispatches for each load - one for status: success and fetchStatus: fetching then status: success and fetchStatus: idle

fix: don't store duplicate height results

---

src/layout/DialogManager.tsx
src/views/dialogs/TestnetFaucetDialog.tsx

- We only had a TestnetDepositForm, pulled it into its own dialog and handling at the DialogManager level

feat: re-add testnet faucet as its own dialog

---

src/views/dialogs/OnboardingTriggerButton.tsx

Broken here: https://github.com/dydxprotocol/v4-web/pull/1551/files#diff-3b56b92474ce34542f3ba0c8dfc5b7998bf2817778dba10974d188e82ff2aa63R56
Need Jared to validate my logic here is right but it seems good.
Issue: https://linear.app/dydx/issue/BUG2-305/unable-to-click-on-recover-keys

fix: recover keys disabled

---

src/views/dialogs/TransferDialogs/WithdrawDialog2/AddressInput.tsx
src/views/dialogs/TransferDialogs/WithdrawDialog2/WithdrawDialog2.tsx
src/views/dialogs/TransferDialogs/WithdrawDialog2/WithdrawForm.tsx
src/views/dialogs/TransferDialogs/WithdrawDialog2/withdrawHooks.ts
src/views/dialogs/TransferDialogs/utils.ts

- Update invalidAddress warning so it does not need a setState
- move check for valid address outside of getUserAddressesForRoute
- update address population side effect

fix: crash when sourceAccount address is invalid

---

src/bonsai/logs.ts

It's hard to parse messages in datadog sadly

fix: add log source to new bonsai logs

---

src/state/_store.ts
src/state/account.ts
src/state/autoBatchHelpers.ts
src/state/localOrders.ts
src/state/perpetuals.ts
src/state/raw.ts

Raw data updates are fine to delay, so we use redux-toolkit batching to reduce the number of react re-renders to at most 4/second. All user input actions should not be batched so still respond instantly to user input.

feat(performance): batch store notifications for fewer rerenders

---

package.json
pnpm-lock.yaml
src/views/dialogs/TransferDialogs/WithdrawDialog2/AddressInput.tsx
src/views/dialogs/TransferDialogs/WithdrawDialog2/WithdrawStatus.tsx

- bumping skip-go/client fixes Simulation Tx error when depositing using Phantom
- add `min-w-0` to fix flex blowout on Mozilla Firefox
- use length comparison so that `0` does not get rendered when list is empty

fix: bump skip-go/client

---

src/bonsai/rest/assets.ts
src/bonsai/rest/geo.ts
src/bonsai/rest/lib/indexerQueryStoreEffect.ts
src/bonsai/rest/lib/safeSubscribe.ts

It turns out calling observer.subscribe() only gets you future updates which is typically fine since we just created the observer and refetchOnMount is usually true so it fires off a load but if the query key is warm then the observer creation will fire off an update with the value to no listeners then the subscribe gets nothing until the next staleTime. 
This line: https://github.com/TanStack/query/blob/main/packages/query-core/src/queryObserver.ts#L106 is supposed to account for this case but since refetchOnMount is true we miss that rescue attempt. 
I note that the way useQuery accounts for this is even stranger and I can't quite get it to work: 
https://github.com/TanStack/query/blob/main/packages/react-query/src/useBaseQuery.ts#L94
they call getOptimisticResult on every render (which …

fix: safe sub to react query observers

---

src/lib/timeOffset.ts

This is important imo because it's basically a test for whether the user's internet is working and will provide a baseline for how often we should expect queries to fail.

chore: log time query success

---

src/bonsai/AccountTransactionSupervisor.ts
src/bonsai/rest/lib/compositeClientManager.ts
src/bonsai/rest/lib/indexerQueryStoreEffect.ts
src/bonsai/rest/lib/useIndexer.ts
src/bonsai/socketSelectors.ts
src/hooks/useInitializePage.ts
src/state/raw.ts

New features:
* retry initialization for all clients up to 3 times with exponential backoff starting at 1s and doubling each retry
* refresh client initialization on visible/network status change in case best network changes - but only trigger query refresh when the actual validator url changes
* parallelize client initialization for speed and so we can be in partial success states (not all or nothing)

chore: rewrite client managers again

---

src/bonsai/logs.ts
src/lib/telemetry.ts

* log more long duration queries 
* make sure we are logging at least one log every five minutes when we could potentially be causing errors so we can correctly calculate error frequency

chore: better telemetry

---

src/bonsai/forms/trade/tradeInfo.ts
src/bonsai/forms/trade/types.ts
src/views/forms/TradeForm/AmountCloseInput.tsx

Most important change: we don't use current oracle price to determine slippage equity impact, we use estimated (worst case) oracle price at execution time.

fix: misc trade fixes 3

---

src/bonsai/forms/trade/errors.ts
src/bonsai/forms/trade/fields.ts
src/bonsai/forms/trade/summary.ts
src/bonsai/forms/trade/tradeInfo.ts
src/bonsai/forms/trade/types.ts
src/constants/trade.ts
src/views/forms/TradeForm/useTradeTypeOptions.tsx

We just infer TP/SL based on the relationship between current oracle price and trigger price.

fix: simplify triggers - stop orders subsume take profit

---

src/bonsai/lifecycles/cancelTriggerOrdersLifecycle.ts
src/bonsai/lifecycles/reclaimChildSubaccountBalancesLifecycle.ts
src/bonsai/selectors/accountTransaction.ts

Some lifecycle methods should be available to those in a close-only state.
- Add additional selector for authorizing accounts to complete those lifecycle methods

feat: allow close-only accounts to cancel + sweep child funds

---

src/bonsai/AccountTransactionSupervisor.ts
src/bonsai/calculators/apiState.ts
src/bonsai/selectors/apiStatus.ts
src/constants/numbers.ts
src/hooks/useWithdrawalInfo.ts
src/pages/vaults/VaultLockedSharesTable.tsx

To fix issues with some users submitting market orders that are already expired. This happens if the validatorHeight in the state gets old or fails once or twice or is slow.

fix: estimate chain height

---

src/bonsai/forms/trade/tradeInfo.ts

RIP rewards - it's like 8x smaller than we currently show

fix: rewards formulas

---

src/bonsai/rest/height.ts

Seems like we're missing height errors since these functions (purposefully) swallow errors.

fix: height logs

---

src/constants/candles.ts
src/views/charts/TradingView/BaseTvChart.tsx
src/views/charts/TradingView/ResolutionSelector.tsx

Use unitStringKeys to clean up the ResolutionSelector
- before it would read `60` instead of `1h` or `240` instead of `4h`

chore: abstract component into resolution selector and fix labels

---

src/views/dialogs/TransferDialogs/WithdrawDialog2/AddressInput.tsx
src/views/dialogs/TransferDialogs/WithdrawDialog2/WithdrawDialog2.tsx
src/views/dialogs/TransferDialogs/WithdrawDialog2/WithdrawForm.tsx
src/views/dialogs/TransferDialogs/WithdrawDialog2/WithdrawStatus.tsx

- CTA button and receipts moved  to the bottom
- Update input styling

feat(withdraw-ui): match deposit refresh

---

src/views/dialogs/ComplianceConfigDialog.tsx

context: let geo-bound stuff go through in dev mode if you untick the box

fix: lets go to the beach

---

src/App.tsx
src/components/AlertMessage.tsx
src/components/ComplianceBanner.tsx
src/components/RestrictionWarning.tsx
src/hooks/useComplianceState.tsx
src/hooks/useNotificationTypes.tsx
src/pages/markets/simple-ui/MarketsMobile.tsx
src/pages/markets/simple-ui/markets-view/MarketList.tsx
src/pages/portfolio/SimpleUiHistory.tsx
src/pages/trade/simple-ui/AssetHeader.tsx
src/pages/trade/simple-ui/AssetPage.tsx

- Overhaul Restriction Warning by bundling everything into a Compliance Banner
- Remove compliance toast notifications completely
- Disable Long/Short button when not FULL_ACCESS
- Desktop
- Mobile
- 
- Simple UI

feat: create compliance banner

---

src/views/tables/MarketsTable.tsx

fix: show empty market cap instead of zero for markets with 0 market cap because untrusted source on cmc

---

src/components/AssetIcon.tsx

fix: asset icon background a tiny bit smaller

---

src/pages/markets/MarketsBanners.tsx

Updated url to point to https://dydx.trade/DYDX?utm_source=markets&utm_medium=markets-banner&utm_campaign=13082025-markets-surge-banner-dydx&utm_term=&utm_content=surge-banner

fix: update surge banner URL to dydx.trade/DYDX

---

src/bonsai/AccountTransactionSupervisor.ts

TURNS OUT datadog doesn't index any field other than error.message so search totally fails now

fix: log errors correctly by reconstructing an error and shoving a message in

---

src/views/dialogs/TransferDialogs/WithdrawDialog2/AddressInput.tsx
src/views/dialogs/TransferDialogs/WithdrawDialog2/WithdrawForm.tsx

- Fix placeholder for embedded addresses
- Do not always show slippage warning. Only display warning if there is a viable route.

fix: update placeholder and slippage warning conditional

---

src/bonsai/calculators/subaccount.ts
src/bonsai/forms/trade/errors.ts
src/bonsai/types/summaryTypes.ts

Main case is preventing users who just made their account and have 0 funds from placing trades

fix: don't allow trades that are taking you from invalid account state to MORE invalid

---

src/views/dialogs/ShareAffiliateDialog.tsx

- safari's relatedTarget on blur events returns the dialog element instead of the clicked button
- switch cancel handler to only fire when explicitly clicking the cancel button

fix: only cancel referral code edits explicitly via the cancel button
